Update Keycloak to 3.4.3.Final version
eclipse/che pull request #10165
Opened 2018-06-23 12:38 UTC by mkuznyetsov

### What does this PR do?
Update Keycloak image to 3.4.3. Final version. Adapt .ftl templates due to changes bringing with it

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/10100

#### Release Notes

#### Docs PR

2018-06-23 13:47 UTC, ghost approved these changes

2018-06-25 05:29 UTC, skabashnyuk approved these changes

2018-06-25 05:38 UTC, benoitf approved these changes

2018-06-25 06:00 UTC, ghost reviewed
Please update this one too https://github.com/eclipse/che/blob/master/dockerfiles/keycloak/Dockerfile#L8

This Dockerfile is used to build an image for used for OpenShift deployment.

And make sure you check it on OpenShift.

2018-06-25 06:48 UTC, mkuznyetsov commented
ci-test

2018-06-25 07:56 UTC, riuvshin requested changes

2018-06-25 07:56 UTC, riuvshin commented on dockerfiles/cli/version/nightly/images
> +IMAGE_KEYCLOACK=jboss/keycloak-openshift:3.4.3.Final
please apply same changes to latest

2018-06-27 12:29 UTC, riuvshin approved these changes

2018-07-02 06:49 UTC, merged