allow to set che ws agent inacive timeout in helm
eclipse/che pull request #10705
Opened 2018-08-08 15:57 UTC by riuvshin

allow to set che ws agent inacive timeout in helm

2018-08-08 18:09 UTC, ghost approved these changes

2018-08-08 22:10 UTC, ghost approved these changes

2018-08-09 06:01 UTC, sleshchenko requested changes
Please consider using new property instead of deprecated one

2018-08-09 08:13 UTC, riuvshin commented on deploy/kubernetes/helm/che/templates/configmap.yaml
> +  CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS: {{ .Values.global.wsAgentInactiveStopTimeout }}
ah! nice catch, btw I thought 0 is a default value.

2018-08-09 08:27 UTC, sleshchenko approved these changes
Now LGTM. Thanks for adding such an ability :+1: :+1: :+1:

2018-08-09 08:37 UTC, merged