Quick fix for formatting
eclipse/che pull request #10793
Opened 2018-08-15 16:35 UTC by musienko-maxim

-->

#### Release Notes

#### Docs PR

2018-08-15 17:50 UTC, riuvshin commented
ci-build

2018-08-15 19:59 UTC, riuvshin requested changes
this PR does not fix formatting issue.

2018-08-16 05:33 UTC, dmytro-ndp approved these changes

2018-08-16 05:49 UTC, dmytro-ndp commented
@riuvshin you are basing on https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-build/4602 report, but locally build doesn't fail. That is strange.

2018-08-22 12:49 UTC, closed without merging