Provide a way to annotate rest endpoint functions to enable Machine Auth
eclipse/che pull request #11370
Opened 2018-09-26 19:39 UTC by davidfestal

### What does this PR do?

This PR allows extends the newly-added mechanism that limits the scope of allowed operations with machine token to workspace related ones only.

We should be able to provide, in a custom assembly for example, additional wsmaster endpoints that would be considered as workspace-related.
This is a strong requirement to enable updating RhChe to upstrea Che 6.12.0 version.
For more details about the RhChe case, see [this comment](https://github.com/redhat-developer/rh-che/pull/902#issuecomment-424645862)

The proposed solution defines a `MachineAuthorized` annotation that can be added on an new REST endpoint method, so that it would support Machine-token-based authentication coming from agent requests. 

### What issues does this PR fix or reference?

This is a pre-requisite for issue https://github.com/redhat-developer/rh-che/issues/927

2018-09-27 06:40 UTC, ibuziuk commented
[ci-test]

2018-09-27 06:42 UTC, ibuziuk commented
ci-test

2018-09-27 06:42 UTC, ibuziuk approved these changes

2018-09-27 07:14 UTC, skabashnyuk commented
@davidfestal please do not merge this pr.  We are discussing with @mshaposhnik @sleshchenko some alternative way to configure a list of services/methods. We would like to make services independent from authentification/authorization. I hope we will provide some details today.

2018-09-27 07:18 UTC, davidfestal commented
@skabashnyuk BTW what do you think of the annotation approach. That seems quite secured, no ? That means that no one can change the permissions of an upstream endpoint in a customized assembly, which seems rather important. wdyt ?

2018-09-27 08:15 UTC, skabashnyuk commented
@davidfestal not really. I do like the separation between services and filters and the fact that they should not know about each other. What I see is that we have low flexibility in a configuration of KeycloakAuthenticationFilter and MachineTokenAccessFilter. I think we should provide an ability to easily customize this filters without the need dig into MethodInterceptor, etc.

2018-09-27 08:19 UTC, skabashnyuk commented
@davidfestal FYI https://github.com/eclipse/che/issues/11374

2018-09-27 08:39 UTC, skabashnyuk commented
Yes sure it's easy from one hand from another hand it breaks distinctions between filter and service that I would like to keep. 
For example, WorkspaceService should know about machine tokens, authentification/authorization etc.

FYI @mshaposhnik has some prototypes for https://github.com/eclipse/che/issues/11374 I hope we will have some solution today/tomorrow. It's supposed to be based on configuration property/ environment variable.

2018-09-27 08:39 UTC, skabashnyuk requested changes
Please wait for https://github.com/eclipse/che/issues/11374

2018-09-27 09:39 UTC, riuvshin commented
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/875/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/875//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11370
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

2019-07-31 09:33 UTC, musienko-maxim commented
Can one of the admins verify this PR?

2019-07-31 13:18 UTC, vparfonov commented
not actual

2019-07-31 13:18 UTC, closed without merging