Adopt  the "TransitiveDependencyTest" selenium test for changes from "5730_java_ls_poc" branch
eclipse/che pull request #11534
Opened 2018-10-08 13:49 UTC by Ohrimenko1988

### What does this PR do?
Adopt  the "TransitiveDependencyTest" selenium test for changes from "5730_java_ls_poc" branch

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/6157
PR: https://github.com/eclipse/che/pull/10863

#### Release Notes

#### Docs PR

2018-10-08 13:51 UTC, dmytro-ndp approved these changes

2018-10-08 14:28 UTC, musienko-maxim approved these changes

2018-10-08 15:22 UTC, tsmaeder approved these changes

2018-10-08 15:23 UTC, tsmaeder requested changes
Please fix the ip problem.

2018-10-09 09:54 UTC, Ohrimenko1988 commented
@tsmaeder Fixed

2018-10-09 10:01 UTC, tsmaeder approved these changes

2018-10-09 10:01 UTC, merged