Factory plugin
eclipse/che pull request #11718
Opened 2018-10-24 08:51 UTC by sunix

### What does this PR do?
- Removes the legacy Che-Theia factory extension.
- Includes the che-theia-factory plugin.
- Adding `make` and `gcc-c++` to be able to compile Theia from the che-theia image

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/11249

#### Release Notes
Che-theia clones projects that are defined in the workspace definition.
Che-theia performs factory cloning and execute post loading actions.

2018-10-24 10:05 UTC, AndrienkoAleksandr approved these changes

2018-10-25 07:12 UTC, benoitf commented on dockerfiles/theia/Dockerfile
> +RUN yum install -y rh-git29 scl-utils sudo java-1.8.0-openjdk-devel bzip2 which make gcc-c++ && \
the theia-ide image is only a runtime image so make, gcc and c++ should not be there

2018-10-25 07:13 UTC, benoitf requested changes
theia-ide image should not contains any compilation stuff.
(probably it may go in https://github.com/ws-skeleton/che-plugin-dev-tooling which is the "development image for plug-ins, etc) which is in che7 stack

2018-10-25 07:55 UTC, sunix commented
@benoitf ok but
at the same time
- it is the image where we do self hosting
- the way we build in docker should be the closest to the way we build in our dev environment.
- why do we include node_modules in /node_modules in this case ?
- why do we have jdk stuff in this image ?

My point is that we are adding restriction that are not so important to me. We should give the choice to the developer to build image anywhere and if for some reason developer prefers to build in che-theia image, why restricting him ?

2018-10-25 14:41 UTC, sunix commented
@benoitf I have updated the PR without make and gcc-c++

2018-10-25 14:57 UTC, benoitf approved these changes

2018-10-26 08:07 UTC, merged

2018-10-26 12:16 UTC, riuvshin commented
@sunix no `ci-build` / `ci-test` ??? this broke master :)