Fix licence year for some files.
eclipse/che pull request #13082
Opened 2019-04-05 14:02 UTC by AndrienkoAleksandr

### What does this PR do?
Fix licence year for some files.

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

2019-04-05 14:04 UTC, AndrienkoAleksandr commented
ci-build

2019-04-05 14:23 UTC, amisevsk commented
Does the maven-license-plugin not support these files? It'd be much easier to use the existing functionality than remembering to do this again in 8 months.

2019-04-08 00:33 UTC, monaka commented on wsmaster/che-core-sql-schema/src/main/resources/che-schema/5.6.0/1__add_exec_agent_where_terminal_agent_is_present.sql
> +-- Copyright (c) 2012-2019 Codenvy, S.A.
Just a making sure. Codenvy is acquired by Red Hat, right? Why the latest year is updated?

```suggestion
-- Copyright (c) 2012-2019 Red Hat, Inc.
```
or

```suggestion
-- Copyright (c) 2012-2017 Codenvy, S.A.
-- Copyright (c) 2017-2018 Red Hat, Inc.
```

is better ?

2019-04-08 05:43 UTC, skabashnyuk commented
FYI. We can't change anything in existed sql files. Otherwise, SQL migration will fail. Hash from file content stored in the database.

2019-04-08 05:58 UTC, monaka commented
@skabashnyuk Ah I see. Thanks for the information.

2019-04-09 07:07 UTC, sleshchenko requested changes
Please revert changes in sql scripts.
Let me know if you need more details why it should be done, or how to test that it breaks existing Che installations

2019-04-09 07:07 UTC, sleshchenko commented on wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.4.0/postgresql/2__add_signature_key.sql
> +-- Copyright (c) 2012-2019 Red Hat, Inc.
Please revert changes in sql scripts because it will break all existing Che Installation

2019-04-09 13:41 UTC, sleshchenko approved these changes
LGTM

2019-04-09 14:01 UTC, skabashnyuk approved these changes

2019-04-10 10:09 UTC, AndrienkoAleksandr commented
ci-build

2019-04-10 14:03 UTC, AndrienkoAleksandr commented
ci-test

2019-04-10 14:52 UTC, AndrienkoAleksandr commented
ci-test

2019-04-11 07:09 UTC, artaleks9 commented
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1706/) doesn't show any regression against this Pull Request.

2019-04-11 07:14 UTC, merged