Deprecate /api/devfile REST API
eclipse/che pull request #13868
Opened 2019-07-16 13:53 UTC by skabashnyuk

### What does this PR do?
Deprecate /api/devfile REST API

### What issues does this PR fix or reference?
need for https://github.com/eclipse/che/issues/13867

#### Release Notes
n/a

#### Docs PR
n/a

2019-07-16 13:59 UTC, skabashnyuk commented
ci-test

2019-07-16 15:02 UTC, metlos reviewed
I'm generally OK with returning 400 with a meaningful error message but I think we should consider the following:

* we should remove the swagger docs from the methods
* what about returning 301 (or maybe even 308) instead?

2019-07-17 13:19 UTC, skabashnyuk commented
>we should remove the swagger docs from the methods

ok

>what about returning 301 (or maybe even 308) instead?

My intention was a bit different. It's not just to keep it working it's to identify a place what it used and fix it. I next release we want to remove this api at all because we have analog ```/api/workspace/devfile```. 

AFAIK there are no places where we use this api.

2019-07-17 13:20 UTC, skabashnyuk commented
@rhopp @nickboldt @sleshchenko @mshaposhnik thoughts?

2019-07-17 13:27 UTC, nickboldt commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileService.java
> +        "This is an outdated method please use /api/workspace/devfile to create a new workspace");
Run-on sentence and does not explain WHY user should use other api.

Preferred: "This method is deprecated and may be removed at any time. Please use ..."

2019-07-17 13:28 UTC, nickboldt commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileService.java
> +        "This is an outdated method please use /api/workspace/devfile to create a new workspace");
Run-on sentence; does not explain WHY user should use other api.

Preferred: "This method is deprecated and may be removed at any time. Please use ..."

2019-07-17 13:28 UTC, nickboldt requested changes
Please tweak the error messages to explain the need for the call to action, and to fix the English syntax.

2019-07-18 06:25 UTC, skabashnyuk commented
@nickboldt your comments have been addressed

2019-07-18 06:26 UTC, skabashnyuk commented
ci-test

2019-07-18 09:34 UTC, rhopp approved these changes

2019-07-18 11:16 UTC, skabashnyuk commented
@nickboldt are you ok with the current state of pr?
@eclipse/eclipse-che-qa can I ignore results of crw-ci-e2e-happy-path-test ?

2019-07-18 14:24 UTC, SkorikSergey commented
> @eclipse/eclipse-che-qa can I ignore results of crw-ci-e2e-happy-path-test ?

Yes, it is test problem(20 sec was not enough for starting Java language server).

2019-07-19 11:30 UTC, skabashnyuk commented
@nickboldt ping

2019-07-22 15:33 UTC, nickboldt approved these changes
+1

2019-07-22 15:34 UTC, nickboldt commented
@skabashnyuk sorry for slow response. You'd do better to ping on MM, slack, IRC, hangouts or anything that doesn't produce email but a notification of unread messages. :) 

Email is the thing I do LAST after all the other hailing frequencies are done.

2019-07-22 19:41 UTC, merged