Add missing registration for git preferences provisioner
eclipse/che pull request #14488
Opened 2019-09-09 13:05 UTC by vzhukovskii

### What does this PR do?
Add missing registration in OpenShift instrastructure for the git preferences provisioner.

Signed-off-by: Vlad Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
#13876

#### Release Notes
N/A

#### Docs PR
N/A

2019-09-09 13:22 UTC, sleshchenko approved these changes

2019-09-09 13:23 UTC, metlos approved these changes

2019-09-09 13:51 UTC, amisevsk requested changes
PR should not be merged before https://github.com/eclipse/che/pull/14442 or it will introduce https://github.com/eclipse/che/issues/14436 on OpenShift.

2019-09-10 13:19 UTC, vzhukovskii commented
@amisevsk this PR is ready to merge. #14442 has been already merged into master.

2019-09-10 14:46 UTC, amisevsk approved these changes
Thanks @vzhukovskii

2019-09-10 14:47 UTC, merged