Used latest official jre8-slim image for che master
eclipse/che pull request #15203
Opened 2019-11-15 15:17 UTC by skabashnyuk

### What does this PR do?
Used the latest community-supported java8 JRE image for che server.
After we have this pr https://github.com/eclipse/che/pull/15201 merged nothing is preventing us to use jre instead of jdk.

### What issues does this PR fix or reference?
n/a

#### Release Notes
n/a

#### Docs PR
n/a

2019-11-22 08:41 UTC, sleshchenko approved these changes
I can't say that I really understand all the options we could go with here

But I'm OK with the proposed way and I don't have any objections :+1:

2019-11-22 08:46 UTC, skabashnyuk commented
>I can't say that I really understand all the options we could go with here

- latest patches from the official repository for JVM and for operation system by itself.
- latest options for JVM. There are a lot of efforts to backport container-related features from new versions.
-  We don't need jdk components in runtime.

2019-11-22 15:26 UTC, benoitf requested changes

2019-11-22 15:27 UTC, benoitf commented on dockerfiles/che/Dockerfile
> +FROM openjdk:8-jre-slim
I forgot to hit send last week so sorry for late notification

2019-11-22 18:34 UTC, skabashnyuk commented
@benoitf your comments have been addressed.

2019-11-22 19:35 UTC, benoitf approved these changes

2019-11-23 12:19 UTC, skabashnyuk commented
ci-test

2019-11-23 14:17 UTC, merged