Provides RELEASE.md file with the release instructions.
eclipse/che pull request #15668
Opened 2020-01-13 10:59 UTC by vparfonov

Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### What does this PR do?

Provides RELEASE.md file with the release instructions.

### What issues does this PR fix or reference?

#### Release Notes

#### Docs PR

2020-01-13 14:51 UTC, ibuziuk commented
@vparfonov  what about the bug-fix / service release process? are you going to provide this info in a separate PR ?

2020-01-13 15:00 UTC, vparfonov commented
> @vparfonov what about the bug-fix / service release process? are you going to provide this info in a separate PR ?

Good catch, I will add here

2020-01-13 15:31 UTC, ibuziuk commented
@vparfonov does che-parent / che-docs update suppose to be covered by this RELEASE.md?

2020-01-28 02:47 UTC, nickboldt commented
OH NO! Happy path tests are failing for a new, document-only file. 

Why are the happy paths failing for a file that isn't part of the build?

2020-01-28 02:48 UTC, nickboldt commented on RELEASE.md
> + https://oss.sonatype.org/#stagingRepositories
Can this be scripted?

2020-01-28 02:49 UTC, nickboldt commented on RELEASE.md
> +##### 4. Start pre-release testing.
Link to job? trigger instructions? Who to talk to? deadline for review? Criteria for rejection/approval?

2020-01-28 02:50 UTC, nickboldt commented on RELEASE.md
> +
Could you list actual files that are changed or provide a link to PRs for 7.7.0 and 7.7.1?

2020-01-28 02:50 UTC, nickboldt commented on RELEASE.md
> +* Create PR
link to samples please. See https://github.com/eclipse/che-machine-exec/blob/master/RELEASE.md for examples of how to do this.

2020-01-28 02:51 UTC, nickboldt commented on RELEASE.md
> +##### 4. Start pre-release testing.
See https://github.com/eclipse/che-machine-exec/blob/master/RELEASE.md for example of how to link to the job(s) that run the builds/tests so we an immediate see status.

2020-01-28 02:51 UTC, nickboldt requested changes
Good start, but needs fleshing out with more details, links, samples, etc.

2020-01-28 02:53 UTC, nickboldt commented
Is this RELEASE.md for all three Che projects (parent, docs, che) ? What about che-dev or che-lib? Will you also create RELEASE.md files for those repos? 

Or does the Che release process handle all 4 projects in one operation?

2020-01-28 15:54 UTC, nickboldt approved these changes
Unblocking so we can merge; remaining items to be done as enhancement as part of the doc generated from tomorrow's collab release with @mkuznyetsov and @vparfonov

2020-01-28 15:55 UTC, merged