Load tests Jenkins job
eclipse/che pull request #16992
Opened 2020-05-22 06:29 UTC by Katka92

### What does this PR do?
Add Jenkins job for load tests. Also remove using ffmpeg from load tests to decrease memory usage.

2020-05-22 10:32 UTC, dmytro-ndp requested changes
[There is a problem with screencast recording](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/2833/console):
```
09:14:36.745 INFO [ActiveSessions$1.onStop] - Removing session b0955a780b82852a8908b46e73f6033e (org.openqa.selenium.chrome.ChromeDriverService)
+ EXIT_CODE=0
+ kill_ffmpeg
+ echo 'Killing ffmpeg with PID='
+ kill -2 ''
Killing ffmpeg with PID=
/tmp/entrypoint.sh: line 7: kill: `': not a pid or valid job spec
+ wait ''
/tmp/entrypoint.sh: line 8: wait: `': not a pid or valid job spec
+ mkdir -p /tmp/e2e/report/
+ cp '/tmp/ffmpeg_report/*' /tmp/e2e/report/
cp: cannot stat '/tmp/ffmpeg_report/*': No such file or directory
+ exit 0
```
Please, fix it before merging the changes into the **master** branch.

2020-05-22 10:46 UTC, dmytro-ndp commented on tests/.infra/crw-ci/load-tests/Jenkinsfile
> +                script {
you can enclose whole _steps_ section into _script_{} block

2020-05-22 10:50 UTC, dmytro-ndp commented on tests/.infra/crw-ci/load-tests/Jenkinsfile
> +        string(name: 'emails',
`emails` parameter is unused in pipeline

2020-05-22 10:52 UTC, dmytro-ndp commented on tests/.infra/crw-ci/load-tests/Jenkinsfile
> +                  ROOT=`pwd`
Actually, it's not simple to read to code ten rows long.
I would suggest to divide logical blocks by empty rows to improve readability.

2020-05-22 10:57 UTC, dmytro-ndp commented
crw-ci-test

2020-05-22 13:37 UTC, Katka92 commented
@dmytro-ndp The problem is fixed: https://github.com/eclipse/che/pull/16992#issuecomment-632662318 I've reverted the image.

2020-05-22 13:47 UTC, dmytro-ndp approved these changes
Screencast problem has been fixed https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/2836/console

2020-05-25 09:26 UTC, dmytro-ndp approved these changes
Latest changes look good.

2020-05-25 11:02 UTC, Katka92 commented
[ci-build]

2020-05-25 12:19 UTC, merged