Fix bugs - constant and error throwing
eclipse/che pull request #18894
Opened 2021-01-27 07:25 UTC by Katka92

### What does this PR do?
Fix timeout constant for waiting on workspace startup. Fix error throwing when waiting for a workspace to be up and running times out.

### What issues does this PR fix or reference?
Currently, when waiting for the workspace to be running & switched to IDE fails, you can see in the logs that it passed:

```
Validation of workspace start
          ▼ DriverHelper.navigateToUrl https://che-eclipse-che.10.0.101.167.nip.io/dashboard/#/ide/admin/petclinic-dev-environment
    ✓ Open workspace (92ms)
          ▼ Ide.waitAndSwitchToIdeFrame
          ▼ Ide.waitIde
          ▼ ProjectTree.openProjectTreeContainer
          ▼ Ide.waitLeftToolbarButton
    1) Wait for workspace readiness
```

### How to test this PR?
Run Happy path or some devfile test.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

2021-01-27 07:31 UTC, dmytro-ndp approved these changes
Looks good.

2021-02-08 08:40 UTC, Katka92 commented
[crw-ci-test]

2021-03-09 17:44 UTC, ScrewTSW requested changes

2021-03-10 07:05 UTC, Katka92 commented on tests/e2e/pageobjects/ide/Ide.ts
> +                throw err;
Hm, good point, will add.

2021-03-10 07:08 UTC, Katka92 commented on tests/e2e/testsLibrary/ProjectAndFileTests.ts
> +        await ide.waitIde(TimeoutConstants.TS_SELENIUM_START_WORKSPACE_TIMEOUT);
Yes, but in this case, this method is used to wait for a workspace to spin up AND load ide, so we need to have TS_SELENIUM_START_WORKSPACE_TIMEOUT there.

2021-03-10 08:19 UTC, ScrewTSW commented on tests/e2e/testsLibrary/ProjectAndFileTests.ts
> +        await ide.waitIde(TimeoutConstants.TS_SELENIUM_START_WORKSPACE_TIMEOUT);
I see

2021-03-10 08:19 UTC, ScrewTSW approved these changes
LGTM

2021-03-10 08:29 UTC, merged