Backport to 7.28.x Language review on che.properties (#19263)
eclipse/che pull request #19590
Opened 2021-04-14 11:53 UTC by themr0c

* Language review on che.properties

* Apply suggestions from code review

Co-authored-by: Yana Hontyk <yhontyk@redhat.com>

### What does this PR do?

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

### How to test this PR?

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

2021-04-14 11:54 UTC, themr0c commented
@skabashnyuk Please validate and tell when we can merge.

2021-04-15 06:41 UTC, skabashnyuk approved these changes

2021-04-15 06:57 UTC, skabashnyuk requested changes
Do not merge without https://github.com/eclipse/che/pull/19600

2021-05-20 13:22 UTC, themr0c commented
We'll do better next time.

2021-05-20 13:22 UTC, closed without merging