Che Java Test Runner Plugin
eclipse/che pull request #2157
Opened 2016-08-17 18:13 UTC by Mirage20

### What does this PR do?

This pull request implements Java unit test runner plugin for che, which enables users to easily run Java unit tests within the IDE and view/navigate the test results.

#### Features

- Supports common test frameworks : JUnit 3.x, JUnit 4.x, TestNG
- Supports Maven project types.
- Main menu and context menu items for running test cases.
- Able to run per class and per project tests. (Or per suite if TestNG with testng.xml suite)
- UI notification about the progress and result.
- UI (Information view) for show the test results.
- Easy navigation for failing results. (Tree navigation for classes and methods)
- Able to view stack trace and assertion difference.
- Able to jump to the failing class and the line from the test result view.
- Provide extensible framework for adding new test engines.

### Tests written?
Yes

### Documentation
Plugin Documentration: https://docs.google.com/document/d/1BclPyGRjgExWwgxqBmb-CoHuRMxKsW8yRVVa3gP7pYI/edit?usp=sharing

2016-08-17 20:32 UTC, vparfonov commented
@Mirage20  Great job! We will review it soon

2016-09-05 14:36 UTC, biogerm commented
Can't wait to have it

2016-09-13 15:49 UTC, biogerm commented
@vparfonov Do you know when approximately will this commit been merged into Eclipse Che release?

2016-09-26 11:13 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/src/main/java/org/eclipse/che/ide/ext/java/testing/core/server/classpath/TestClasspathRegistry.java
> +        System.out.println("inititilaized TestClasspathRegistry " + testClasspathProviders.size() + " wkwkwkwkwk " +
Use logger if you need to log something

2016-09-26 11:13 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/src/main/java/org/eclipse/che/ide/ext/java/testing/core/server/framework/TestFrameworkRegistry.java
> +        System.out.println("inititilaized TestFrameworkRegistry " + runners.size() + " fefef " + runners.toString());
Use logger if you need to log something

2016-09-26 11:13 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/src/main/java/org/eclipse/che/ide/ext/java/testing/core/server/inject/TestGuiceModule.java
> +        System.out.println("TestGuiceModule binder");
Use logger if you need to log something

2016-09-26 11:30 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/core/client/view/TestResultViewImpl.java
> +        String testSrcPath = project.getPath() + "/src/test/java/";
I think not good hardcode here path to tests classes. We can use some attributes from projecttype

2016-09-26 11:43 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/pom.xml
> +            <version>4.11</version>
remove version here

2016-09-26 11:44 UTC, vparfonov reviewed
Please remove all system.out

2016-09-26 13:25 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunClassTestAction.java
> +//        presenter.showDialog();
remove

2016-09-26 13:25 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunTestXMLAction.java
> +//        presenter.handleResponse(null);
remove?

2016-09-26 13:26 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunTestXMLAction.java
> +        parameters.put("testngXML", project.getPath() + "/src/test/resources/testng.xml");
will it work without testng.xml in project sources?

2016-09-26 13:26 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-server/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/server/TestNGRunner.java
> +                String className = path.replace('/', '.');
path separator?

2016-09-26 13:27 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-server/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/server/TestNGRunner.java
> +
why so many spaces?

2016-09-26 13:27 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-server/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/server/TestNGRunner.java
> +            System.out.println(failMethod);
remove debug info?

2016-09-26 13:28 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-server/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/server/TestNGRunner.java
> +            System.out.println(failMethod);
debug info?

2016-09-26 13:28 UTC, skabashnyuk requested changes
A lot of debug information. Some cleanup needed.

2016-09-26 19:32 UTC, skabashnyuk commented
BTW we can't accept this PR until  you'll  pass Eclipse validation

2016-10-11 13:42 UTC, TylerJewell commented
@sunix @Mirage20 - any update please?  We would like to close this off and prepare a merge.  But we need to have these improvements done so we can integrate it.

2016-10-14 13:28 UTC, benoitf commented
@skabashnyuk now Eclipse Validation has passed, @Mirage20 updated his pull request

2016-10-15 10:57 UTC, skabashnyuk requested changes
Please respond to all my comments.

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-classpath/che-java-testing-classpath-maven-server/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-classpath/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/core/client/view/navigation/factory/TestResultNodeFactory.java
> + *
?

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/core/client/view/navigation/nodes/TestResultClassNode.java
> + *
javadoc

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/core/client/view/navigation/nodes/TestResultGroupNode.java
> + *
javadoc

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/core/client/view/navigation/nodes/TestResultMethodNode.java
> + *
javadoc

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/resources/org/eclipse/che/ide/ext/java/testing/core/client/TestLocalizationConstant.properties
> +title.testResultPresenter.toolTip="Test Runner Results"
new line

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/src/main/java/org/eclipse/che/ide/ext/java/testing/core/server/TestingService.java
> +        Map<String, String> queryParameters = getMap(uriInfo.getQueryParameters());
?

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-shared/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-ide/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-server/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-shared/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-shared/src/main/java/org/eclipse/che/ide/ext/java/testing/junit4x/shared/JUnitTestResult.java
> + *
javadoc

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-shared/src/main/java/org/eclipse/che/ide/ext/java/testing/junit4x/shared/JUnitTestResult.java
> +    String getFrameworkVersion();
javadoc

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-shared/src/main/java/org/eclipse/che/ide/ext/java/testing/junit4x/shared/JUnitTestResult.java
> +    void setFrameworkVersion(String framework);
javadoc

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-junit/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-server/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 10:57 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
sync with version in master

2016-10-15 17:37 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunTestXMLAction.java
> +        parameters.put("testngXML", project.getPath() + "/src/test/resources/testng.xml");
yes. but when a project requires testng xml, it should be named as testng.xml

2016-10-15 18:06 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunTestXMLAction.java
> +        parameters.put("testngXML", project.getPath() + "/src/test/resources/testng.xml");
@vparfonov Do we have a way to figure out path to test resource if they are configured differently? I mean path is different.

2016-10-15 18:26 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/src/main/java/org/eclipse/che/ide/ext/java/testing/core/server/TestingService.java
> +        Map<String, String> queryParameters = getMap(uriInfo.getQueryParameters());
Query parameters vary with test framework implemntation

2016-10-15 18:37 UTC, Mirage20 commented on assembly/assembly-ide-war/pom.xml
> +            <!--<scope>provided</scope>-->
Sorry, I forget to un-comment. now updated

2016-10-15 18:39 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/pom.xml
> +            <version>4.11</version>
removed

2016-10-15 18:39 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/client/action/RunClassContextTestAction.java
> +        //Log.info(RunClassContextTestAction.class, possibleNode.toString());
removed

2016-10-15 18:39 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/client/action/RunClassContextTestAction.java
> +//        presenter.showDialog();
removed

2016-10-15 18:39 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/client/action/RunClassTestAction.java
> +//        presenter.showDialog();
removed

2016-10-15 18:40 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-server/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/server/JUnitTestRunner.java
> +//        Result r = JUnitCore.runClasses(clsTest);
removed

2016-10-15 18:40 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-server/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/server/JUnitTestRunner.java
> +                String className = path.replace('/', '.');
updated with file separator

2016-10-15 18:40 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-server/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/server/inject/JunitGuiceModule.java
> +        System.out.println("JunitGuiceModule binder");
removed

2016-10-15 18:40 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/core/client/view/TestResultViewImpl.java
> +//
removed

2016-10-15 18:40 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/core/client/view/navigation/factory/TestResultNodeFactory.java
> + *
updated

2016-10-15 18:41 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/src/main/java/org/eclipse/che/ide/ext/java/testing/core/server/TestingService.java
> +        System.out.println("inititilaized TestingService");
removed

2016-10-15 18:41 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/src/main/java/org/eclipse/che/ide/ext/java/testing/core/server/TestingService.java
> +        System.out.println(absoluteProjectPath);
removed

2016-10-15 18:42 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/client/action/RunAllTestAction.java
> +//        presenter.handleResponse(null);
removed

2016-10-15 18:42 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunAllTestAction.java
> +//        presenter.handleResponse(null);
removed

2016-10-15 18:42 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunClassContextTestAction.java
> +        //Log.info(RunClassContextTestAction.class, possibleNode.toString());
removed

2016-10-15 18:43 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunClassTestAction.java
> +//        presenter.showDialog();
removed

2016-10-15 18:43 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunTestXMLAction.java
> +//        presenter.handleResponse(null);
removed

2016-10-15 18:44 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-server/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/server/TestNGRunner.java
> +                String className = path.replace('/', '.');
updated with file seperator

2016-10-15 18:44 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-server/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/server/TestNGRunner.java
> +            System.out.println(failMethod);
removed

2016-10-15 18:45 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-server/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/server/TestNGRunner.java
> +            System.out.println(failMethod);
removed

2016-10-15 18:46 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-classpath/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
updated

2016-10-15 18:46 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
updated

2016-10-15 18:46 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/core/client/view/navigation/nodes/TestResultClassNode.java
> + *
updated

2016-10-15 18:46 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/core/client/view/navigation/nodes/TestResultGroupNode.java
> + *
updated

2016-10-15 18:46 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-ide/src/main/resources/org/eclipse/che/ide/ext/java/testing/core/client/TestLocalizationConstant.properties
> +title.testResultPresenter.toolTip="Test Runner Results"
updated

2016-10-15 18:46 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
updated

2016-10-15 18:46 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-shared/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
updated

2016-10-15 18:47 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
updated

2016-10-15 18:47 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-ide/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
updated

2016-10-15 18:47 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-server/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
updated

2016-10-15 18:47 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-shared/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
updated

2016-10-15 18:47 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-shared/src/main/java/org/eclipse/che/ide/ext/java/testing/junit4x/shared/JUnitTestResult.java
> +    String getFrameworkVersion();
updated

2016-10-15 18:47 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
updated

2016-10-15 18:48 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/pom.xml
> +        <version>4.7.0-RC2-SNAPSHOT</version>
updated

2016-10-26 19:26 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/src/main/java/org/eclipse/che/ide/ext/java/testing/core/server/TestingService.java
> +        Map<String, String> queryParameters = getMap(uriInfo.getQueryParameters());
but "testFramework" and "projectPath" can be explicit, no?

2016-10-26 19:39 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/client/action/RunAllTestAction.java
> +import static org.eclipse.che.ide.api.notification.StatusNotification.Status.*;
avoid "*" imports

2016-10-26 19:39 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/client/action/RunClassContextTestAction.java
> +import static org.eclipse.che.ide.api.notification.StatusNotification.Status.*;
avoid "*" imports

2016-10-26 19:39 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunAllTestAction.java
> +    protected void updateProjectAction(ActionEvent e) {
do we need empty method here?

2016-10-26 19:39 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunClassTestAction.java
> +import static org.eclipse.che.ide.api.notification.StatusNotification.Status.*;
avoid "*" imports

2016-10-26 19:39 UTC, vparfonov commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunTestXMLAction.java
> +    protected void updateProjectAction(ActionEvent e) {
do we need empty method here?

2016-10-26 19:43 UTC, vparfonov commented
@Mirage20 please answer on our comments, we want to make QA circle with your branch and merge it 

thanks for your work

2016-10-31 03:46 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/client/action/RunAllTestAction.java
> +import static org.eclipse.che.ide.api.notification.StatusNotification.Status.*;
removed wildcard imports

2016-10-31 03:46 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/client/action/RunClassContextTestAction.java
> +import static org.eclipse.che.ide.api.notification.StatusNotification.Status.*;
removed wildcard imports

2016-10-31 03:46 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunClassTestAction.java
> +import static org.eclipse.che.ide.api.notification.StatusNotification.Status.*;
removed wildcard imports

2016-10-31 03:47 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-ide/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/client/action/RunTestXMLAction.java
> +    protected void updateProjectAction(ActionEvent e) {
removed

2016-10-31 07:38 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/src/main/java/org/eclipse/che/ide/ext/java/testing/core/server/TestingService.java
> +        Map<String, String> queryParameters = getMap(uriInfo.getQueryParameters());
>Query parameters vary with test framework implemntation.
It doesn't change anything.
Please declare all implemented parameters in javadoc.

2016-10-31 07:43 UTC, skabashnyuk requested changes
Please answer to my comments.

2016-10-31 07:43 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-server/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/server/JUnitTestRunner.java
> + *
Please declare all parameters with class can accept in ```execute``` method.

2016-10-31 07:43 UTC, skabashnyuk commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-server/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/server/TestNGRunner.java
> + *
Please declare all parameters with class can accept in ```execute``` method.

2016-11-02 05:16 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-junit/che-java-testing-junit-server/src/main/java/org/eclipse/che/ide/ext/java/testing/junit/server/JUnitTestRunner.java
> + *
Updated the javadoc with parameters.

2016-11-02 05:16 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-testng/che-java-testing-testng-server/src/main/java/org/eclipse/che/ide/ext/java/testing/testng/server/TestNGRunner.java
> + *
Updated the javadoc with parameters.

2016-11-02 05:31 UTC, Mirage20 commented on plugins/plugin-java-test-runner/che-java-testing-core/che-java-testing-core-server/src/main/java/org/eclipse/che/ide/ext/java/testing/core/server/TestingService.java
> +        Map<String, String> queryParameters = getMap(uriInfo.getQueryParameters());
I updated the javadocs.

2016-11-09 08:02 UTC, skabashnyuk approved these changes

2016-11-09 08:04 UTC, skabashnyuk commented
@Mirage20  I think we good to go to the next step.
We will deploy your PR in one of our acceptance server and will run our selenium tests. 
If we would not see any regressions we will accept this pr.

2016-11-09 08:07 UTC, vparfonov approved these changes

2016-11-16 22:55 UTC, vparfonov commented
@Mirage20 Hello again I fix few error in your code and merge with master. Create new one branch in che for merge your Test Plugin to Che. So please review changes here https://github.com/eclipse/che/pull/3095 you can merge my branch to your. 
FYI: we started QA circle on your PR

2016-11-22 13:47 UTC, vparfonov commented
merged here https://github.com/eclipse/che/pull/3095

2016-11-22 13:47 UTC, closed without merging

2016-11-23 08:23 UTC, kaloyan-raev commented
Is this implementation tightly coupled to Java?

Can we use it for PHPUnit - a PHP unit testing framework, which from design point of view is similar to the Java unit testing frameworks?

2016-11-23 15:15 UTC, vparfonov commented
For now it coupled to Java and it's pretty new plugin form community not much functionality covered. But you question really, will provide some API for testing  framework like we did with debugger