Add property machine.docker.local_node_host.external
eclipse/che pull request #2402
Opened 2016-09-09 15:45 UTC by l0rd

### What does this PR do?
Introduce a new property, `machine.docker.local_node_host.external` (along with the environment variable `CHE_DOCKER_MACHINE_HOST_EXTERNAL`), that allow to configure the external URL browsers need to use to connect with containers that are not directly pingable. This happens for example with Docker for Mac.

```properties
machine.docker.local_node_host.external=localhost
```

When this property is set the browser will use it to connect to the containers. Note that the wsmaster won't use that value to connect to the containers.

If this property is not set Che behaves as before.

This PR introduce a change to the API: [Server class](https://github.com/eclipse/che/blob/master/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Server.java) has a couple of new attributes: `internalUrl` and `internalAddress`. On the other there no particular change is needed client side and all clients will benefit of this change.

```json
"servers": {
      "4401/tcp": {
                "url": "http://localhost:32906/wsagent/ext", 
                "internalUrl": "http://192.168.65.2:32906/wsagent/ext", 
                "address": "localhost:32906",
                "internalAddress": "192.168.65.2:32906",
                "path": "/wsagent/ext",
                "protocol": "http",
                "ref": "wsagent"
     }
}
```

This PR takes into account some feedbacks from PR #2004:
- There are no changes on client side
- Works on configurations where the wsagent and docker containers are on different hosts

I will not close PR #2004. I want to continue the work to integrate Traefik in the che-launcher there. But containous/traefik#444 should be fixed first.   

### What issues does this PR fix or reference?
#1644 

### Previous behavior
Running Che on Docker for Mac required some networking hacking

### New behavior
Remove the need for the networking hack when running Che on Docker for Mac and make running Che as simple as `docker run -v /var/run/docker.sock:/var/run/docker.sock codenvy/che-launcher start` on all platforms.

### PR type
- [x] Minor change = no change to existing features or docs
- [ ] Major change = changes existing features or docs

### Minor change checklist
- [ ] New API required?
- [x] API updated
- [x] Tests updated
- [x] Tests passed

2016-09-09 19:18 UTC, TylerJewell commented
Nice work!  Excited to have this get into master.  I reviewed the changes for the che-launcher and they all look good.

2016-09-09 22:45 UTC, TylerJewell commented
@garagatyi - this resolves a big inconvenience that users have with Docker for Mac. This eliminates a painful setup of the loopback alias on Macs. Your +1 here will be helpful.

2016-09-10 21:23 UTC, garagatyi commented
In my opinion changing API for that workaround is not a good way to go. It will add pain sooner or later.
I've just figured out that we can try to play with IPTables in Che container. 
For example we can try to redirect traffic inside of Che container from 32000-xxxxx to IP of xhyve machine. And let expose machines ports as localhost. In that case browser will be able to connect to machines on localhost and Che-server will use localhost also. But IPTables rules in che-server container will forward all traffic to another IP.
As I understand we can do that even after start of che-server, so we will be able to do that in che launcher and not change base che-server which works fine in all cases except `che in container on mac`.
Here is an example that I googled:
```iptables -t nat -A OUTPUT -i lo -p tcp --dport 32000:65000 -j DNAT --to <IP OF XHYVE>:32000-65000```
But I didn't try it and have no experience with IPTables, so not sure that I found correct (and complete) set of rules for out case.

2016-09-10 22:23 UTC, l0rd commented
@garagatyi can you please be more specific? Where do you want to run this `iptable` command: OSX, xyve VM, che-server container, agent container? What do you mean when you say "let expose machines ports as localhost"?

2016-09-11 05:14 UTC, garagatyi commented
Add iptables rules in che-server container.

Configure che-server in such a way that **localhost** is host in servers provided by Che API.
I think we just should not set CHE_DOCKER_MACHINE_HOST variable to achieve that.

So all traffic from che-server container to localhost with ports 32000-xxxxx will go through IPTables redirection to IP of xhyve where ports of all containers are available.

2016-09-11 20:26 UTC, l0rd commented
Ok thanks for clarifying @garagatyi. I understand now. It's a smart solution :-) I will test that tomorrow.

2016-09-12 15:58 UTC, l0rd commented
Bingo! I've struggled to apply the IP tables rules but I've finally found the following command that work if executed inside `che-sever` container!
```
apk update
apk install iptables
sysctl -w net.ipv4.conf.eth0.route_localnet=1
iptables -t nat -A OUTPUT -p tcp -d localhost -o lo --dport 32000:65000 -j DNAT --to ${XHYVE_VM_IP}:32000-65000
iptables -t nat -A POSTROUTING -o eth0 -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE
```

2016-09-12 16:19 UTC, l0rd commented
I've created a new PR to address the Docker for Mac problem: eclipse/che-dockerfiles#12

@garagatyi I will let you choose which one of these 2 PR is more suitable but let me explain why I believe we should keep this one and close eclipse/che-dockerfiles#12. Apart [some concerns](https://github.com/eclipse/che-dockerfiles/pull/12#issuecomment-246398648) with the iptables solution I also think that changing the Server class, adding an internal url attribute, is not just a patch to solve the Docker for Mac issue but a solution for a recurring problem.

![image](https://cloud.githubusercontent.com/assets/606959/18443241/4ce96fe4-7914-11e6-862b-4106153dfabc.png)

In the current model there is only one address to reach the wsagent server. That same address is used by the browser and the wsmaster. In the diagram I've called this address "Post Office". Depending on the platform the "Post Office" can be `docker0`, the IP of the docker host or just `localhost`. However in most scenarios wsmaster and wsagent are close and there is a shorter path to reach the wsagent (the red path in the diagram). Most important this red path avoid some scary mountains that can be tricky to cross (firewalls, routers, IPtables etc...). That's the case with Docker for Mac but that's also the case with Ubuntu (#2030) or Kubernetes or Openshift etc...This PR is to add the address of this red path to the attributes of the Server class.

2016-09-12 16:44 UTC, TylerJewell commented
I tend to agree with Mario that having the internal sokution is more optimal for the longer term.  And that we can continue to layer in the iptables solution where necessary.

Great graphic :)

2016-09-14 16:52 UTC, l0rd commented
I've updated the PR. I've added a new ServerProperties class where I moved servers `path`, `internalUrl` and `internalAddress` fields. That's the new Server API:

```json
"servers": {
    "4401/tcp": {
        "ref": "wsagent",
        "protocol": "http",
        "address": "localhost:32929",
        "url": "http://localhost:32929/wsagent/ext",
        "port": "32929",
        "properties": {
            "internalUrl": "http://192.168.65.2:32929/wsagent/ext",
            "internalAddress": "192.168.65.2:32929",
            "path": "/wsagent/ext"
        }
    }
}
```
@garagatyi  please review

2016-09-14 16:55 UTC, benoitf commented
I like it also
 I would say that timeframe for updating json format as we're in process for 5.x release and still in milestone,is the right time. After it would be too late

2016-09-14 17:28 UTC, TylerJewell commented
I am ok with this approach.  I want to target this for M2 - solving this problem simplifies a lot of scenarios for us with Mac.

2016-09-15 07:22 UTC, garagatyi commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/ServerProperties.java
> +    String getInternalAddress();
Looks like all fields in that object are nullable.

2016-09-15 07:26 UTC, garagatyi commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/ServerProperties.java
> +     * Internal address of the server in form <b>host:port</b>
Line break by entering 'enter' key doesn't work in javadocs. Please add dot and `<p/>` or `<br/>`

2016-09-15 07:27 UTC, garagatyi commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Server.java
> +     * External address of the server in form <b>host:port</b>
Line break by entering 'enter' key doesn't work in javadocs. Please add dot and `<p/>` or `<br/>`

2016-09-15 07:28 UTC, garagatyi commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/DevMachineServerProperties.java
> + * Describe development machine server instance.
Line break by entering 'enter' key doesn't work in javadocs. Please add `<p/>` or `<br/>`

2016-09-15 07:33 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceRuntimeInfo.java
> +                                     @Assisted String containerExternalHostname,
Not named assisted injection doesn't work when several arguments have the same class

2016-09-15 08:00 UTC, garagatyi commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Server.java
> +     * Port of the server, e.g. 8080
I'm not sure should this port contain `8080` or `8080/tcp`.

2016-09-15 08:01 UTC, garagatyi commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Server.java
> +     * Port of the server, e.g. 8080
And it is external port. Please explain that in javadocs.

2016-09-15 08:03 UTC, garagatyi commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/DevMachineServer.java
> +        public ServerProperties getProperties() { return properties; };
Please add equals/hashcode/toString methods

2016-09-15 08:03 UTC, garagatyi commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/DevMachineServerProperties.java
> +}
Please add equals/hashcode/toString methods

2016-09-15 08:07 UTC, garagatyi commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/DevMachineServerProperties.java
> +    public DevMachineServerProperties(ServerProperties dto) {
Argument doesn't have to be DTO object. Please rename parameter to not confuse developers.

2016-09-15 08:08 UTC, garagatyi commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/DevMachineServerProperties.java
> + * {@link ServerProperties}
Curly brackets are used when link is inlined into description. When it is used as a separate tag it has the same syntax as `@author`

2016-09-15 08:10 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceRuntimeInfo.java
> +                                     @Assisted String containerExternalHostname,
Also please check what will happen if someone provide null value as one of these parameters. I believe nullable annotation should be declared somewhere.

2016-09-15 09:00 UTC, garagatyi commented on plugins/plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/server/ServerProperties.java
> +    }
Please add equals/hashcode/toString methods

2016-09-15 09:05 UTC, garagatyi requested changes
Overall solution is good. Code requires some cleanups and fixes.

2016-09-15 15:10 UTC, garagatyi commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Server.java
>      String getAddress();
Now this method returns both host and port of the server. Are you going to change the behavior in this PR?

2016-09-15 16:33 UTC, l0rd commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Server.java
>      String getAddress();
No I'm not:
```json
"address": "localhost:32929"
```
Is that ok?

2016-09-15 16:36 UTC, l0rd commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Server.java
> +     * Port of the server, e.g. 8080
It's `8080`, the protocol is not there:
```json
"port": "32929"
```

2016-09-15 20:45 UTC, garagatyi commented
Looks like I'm not fully understand new server object. I'll take a look again tomorrow and ask you if something is not clear.

2016-09-16 16:24 UTC, l0rd commented
@garagatyi I've commited the fixes you have suggested:
- Javadoc improved
- Removed `port` field in `Server` class
- Annotated all fields in `ServerProperties` as nullable
- Overwritten methods `equals`, `hashcode` and  `toString` for classes `DevMachineServer` and `DevMachineServerProperties`
- Fixed unnamed assisted injections
- Added some unit tests
- Restored the license header (I'll submit a distinct PR for that)
- Environment variables have now higher priority then properties

2016-09-19 06:05 UTC, garagatyi commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Server.java
> +     * Url of the server, e.g.&nbsp;http://localhost:8080
Please replace `&nbsp;` with a regular backspace.

2016-09-19 06:17 UTC, garagatyi commented on plugins/plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/server/ServerProperties.java
> +    }
This class still needs equals/hashcode/toString methods

2016-09-19 06:17 UTC, garagatyi commented on plugins/plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/server/ServerTest.java
>  }
Please add trailing new line at the end of file

2016-09-19 06:18 UTC, garagatyi commented on wsmaster/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/DtoConverter.java
> -import org.eclipse.che.api.core.model.machine.MachineLimits;
Wildcard imports are forbidden in Che

2016-09-19 06:19 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
> -import org.eclipse.che.api.machine.server.model.impl.CommandImpl;
Please do not use wildcard imports

2016-09-19 06:22 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstance.java
> +                                                                                                null,
For me it looks like this argument is always null. Am I miss something?

2016-09-19 06:22 UTC, garagatyi requested changes

2016-09-19 08:24 UTC, l0rd commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Server.java
> +     * Url of the server, e.g.&nbsp;http://localhost:8080
I think you mean "regular space". If I add a regular space and I try to generate the Javadoc I have the following result:

![image](https://cloud.githubusercontent.com/assets/606959/18626032/b4237b6c-7e52-11e6-8797-72cb966a3414.png)

If I use `&nbsp;` instead the sentence is not broken:

![image](https://cloud.githubusercontent.com/assets/606959/18625990/70ca2776-7e52-11e6-962c-376815b3153b.png)

2016-09-19 08:35 UTC, l0rd commented on plugins/plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/server/ServerProperties.java
> +    }
Class https://github.com/eclipse/che/blob/master/plugins/plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/server/Server.java had no equals method. Should I add equals/hashcode/toString to existing classes too?

2016-09-19 08:54 UTC, l0rd commented on wsmaster/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/DtoConverter.java
> -import org.eclipse.che.api.core.model.machine.MachineLimits;
Sorry for forgetting that. I've fixed it.

2016-09-19 09:21 UTC, garagatyi commented on plugins/plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/server/ServerProperties.java
> +    }
At least add it in classes added by you.

2016-09-19 09:21 UTC, garagatyi commented on core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Server.java
> +     * Url of the server, e.g.&nbsp;http://localhost:8080
OK, interesting

2016-09-19 09:48 UTC, l0rd commented on wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
> +import org.eclipse.che.api.machine.server.model.impl.*;
I think I alrady fixed that: https://github.com/l0rd/che/blob/a35ccae37ab7fdecf958beb02acbf0e8177c8a3b/wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java

You were probably looking at the outdated version?

2016-09-19 09:49 UTC, benoitf commented on wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
> +import org.eclipse.che.api.machine.server.model.impl.*;
yep it was pending request (I forgot to validate it)

2016-09-19 09:50 UTC, benoitf approved these changes

2016-09-19 11:59 UTC, l0rd commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstance.java
> +                                                                                                null,
Feel free to add more details to your questions if that was not what you meant. I think you are wondering how `Server.url` is ever set if this parameter is always `null`. It should be set using property `machine.docker.local_node_host.external` but it looks as it's always null.

Property `machine.docker.local_node_host.external` is injected in `LocalDockerModule` objects that are binded to `DockerInstanceRuntimeInfo` in `LocalDockerModule`. 

Therefore method `DockerInstance.getRuntime()` is not used by the API to get the machine runtime. That explains why `Server.url` is correctly returned by the API.

2016-09-19 13:57 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstance.java
> +                                                                                                null,
Let me explain how I understand what is happening with these changes. Please correct me if I'm mistaken.
DockerInstance always pass null as external host. DockerInstanceRuntimeInfo doesn't change that. LocalDockerInstanceRuntimeInfo uses assisted injection, so this null is passed here too. 
So I don't see how another than null value can be accepted by DockerInstanceRuntimeInfo.

2016-09-19 13:58 UTC, garagatyi requested changes

2016-09-19 23:10 UTC, l0rd commented on plugins/plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/server/ServerProperties.java
> +    }
I've added for both.

2016-09-19 23:12 UTC, l0rd commented on wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceServiceTest.java
> -import org.eclipse.che.api.machine.server.model.impl.CommandImpl;
Fixed

2016-09-19 23:12 UTC, l0rd commented on wsmaster/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/model/impl/ServerImpl.java
> +        this(server.getRef(), server.getProtocol(), server.getAddress(), server.getUrl(), server.getPort(), (ServerPropertiesImpl) server.getProperties());
Fixed

2016-09-19 23:12 UTC, l0rd commented on plugins/plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/server/ServerTest.java
>  }
Fixed

2016-09-19 23:13 UTC, l0rd commented on plugins/plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/DockerInstanceRuntimeInfoTest.java
> +                                                           null)));
Added a couple of tests

2016-09-19 23:13 UTC, l0rd commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/LocalDockerInstanceRuntimeInfo.java
> +              dockerNodeExternalHostname != null ? dockerNodeInternalHostname : (
Fixed. Env variables are now evaluated first.

2016-09-19 23:14 UTC, l0rd commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/DevMachineServerProperties.java
> +    public DevMachineServerProperties(ServerProperties dto) {
Done

2016-09-19 23:15 UTC, l0rd commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/DevMachineServerProperties.java
> + * {@link ServerProperties}
Done

2016-09-19 23:15 UTC, l0rd commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/DevMachineServer.java
> +        public ServerProperties getProperties() { return properties; };
Done

2016-09-19 23:27 UTC, l0rd commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceRuntimeInfo.java
> +                                     @Assisted String containerExternalHostname,
I've changed to named assisted injection and checked if `containerExternalHostname` is null and set it to `containerHost` in that case.

2016-09-19 23:31 UTC, l0rd commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/DevMachineServerProperties.java
> +}
Done

2016-09-19 23:35 UTC, l0rd commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceRuntimeInfo.java
> +                                                     new ServerPropertiesImpl(null, internalHostname + ":" + externalPort, null)));
After fixup `externalHostname`, `internalHostname` and `externalPorts` can never be `null`.

2016-09-19 23:37 UTC, l0rd commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstance.java
> +                                                                                                null,
As discussed on Slack I've cleaned-up `LocalDockerInstanceRuntimeInfo` class and made it easier to read.

2016-09-21 08:43 UTC, garagatyi commented
@musienko-maxim Please do a QA cycle for this PR

2016-09-21 08:45 UTC, garagatyi approved these changes

2016-09-21 08:46 UTC, garagatyi commented
ci-build

2016-09-22 14:55 UTC, garagatyi commented
QA team has approved this PR. We will merge it when M3 is released

2016-09-28 16:52 UTC, merged