CHE-2498: Improve error handling when read a container logs
eclipse/che pull request #2499
Opened 2016-09-20 07:37 UTC by mmorhun

### What does this PR do?
Improves error handling while getting logs from a container. Adds more information into error log.

### What issues does this PR fix or reference?
#2498 

### Previous behavior
No stop condition when many errors occur

### New behavior
Added parameter to stop trying to get logs and added delay between this attempts

2016-09-20 07:40 UTC, mmorhun commented
@AndrienkoAleksandr @garagatyi take a look please

2016-09-20 08:17 UTC, AndrienkoAleksandr commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ComposeMachineProviderImpl.java
> +                    LOG.error("Failed to get logs from machine {} of workspace {} backed by container {}, because: {}. Cause: {}",
Maybe it would be better to print error in the log after 5 five failed attempts...

2016-09-20 10:03 UTC, mmorhun commented
@sleshchenko take a look, please

2016-09-20 11:55 UTC, garagatyi commented
Have you found the reason of such behavior?

2016-09-20 12:49 UTC, sleshchenko commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ComposeMachineProviderImpl.java
> +                    if (++errorsCounter == 5) {
I'd move harcoded value to constant

2016-09-20 12:49 UTC, sleshchenko commented
OK for me

2016-09-20 13:53 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ComposeMachineProviderImpl.java
> +                    if (++errorsCounter == 5) {
I think it is Ok to hardcode it

2016-09-20 13:54 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ComposeMachineProviderImpl.java
>                                machineId,
Arguments order is incorrect

2016-09-20 13:57 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ComposeMachineProviderImpl.java
> +                              e);
Looks like LOG.warn is misused. This methods accepts 1 string and 1 throwable or multiple strings. Did you use it in such a way on purpose?

2016-09-20 13:58 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ComposeMachineProviderImpl.java
> +                                  machineId,
Check order of arguments and usage of multiple arguments + throwable

2016-09-20 13:59 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ComposeMachineProviderImpl.java
> +                            break;
return is more obvious here

2016-09-20 14:00 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ComposeMachineProviderImpl.java
> +                    if (++errorsCounter == 5) {
What if errors happen once an hour? Please respect timeout.

2016-09-20 14:00 UTC, garagatyi requested changes

2016-09-21 06:04 UTC, mmorhun commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ComposeMachineProviderImpl.java
>                                machineId,
tnx

2016-09-21 07:02 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ComposeMachineProviderImpl.java
> +                    LOG.warn("Failed to get logs from machine {} of workspace {} backed by container {}, because: {}.",
Don't you think that we should set **lastProcessedLogDate** here also?

2016-09-21 07:02 UTC, garagatyi requested changes

2016-09-21 07:28 UTC, garagatyi approved these changes

2016-09-28 07:57 UTC, merged