CHE-2369: add a mechanism which checks state of the ws agent
eclipse/che pull request #2530
Opened 2016-09-21 15:05 UTC by svor

### What does this PR do?
Adds a service which periodically pings ws agent and notify a user when something is happened.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/2369

### Previous behavior
When ws agent stops responding a user don't get any response about this and don't know what is happened.

### PR type
- [x] Minor change = no change to existing features or docs
- [ ] Major change = changes existing features or docs

### Minor change checklist
- [ ] New API required?
- [ ] API updated
- [x] Tests provided / updated
- [x] Tests passed

@vparfonov please take a look

2016-09-21 15:49 UTC, vparfonov commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
> +                                              new ConfirmCallback() {
you can use use null instead empty ConfirmCallback

2016-09-21 16:30 UTC, azatsarynnyy commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
> +                if (object != null && object.containsKey("rootResources")) {
if you move this if-block to the try-block upper
checking _object != null_ will be unnecessary

2016-09-21 16:32 UTC, azatsarynnyy commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
> +                                              new ConfirmCallback() {
ConfirmCallback is nullable so no need to create this ConfirmCallback that does nothing

2016-09-21 16:33 UTC, azatsarynnyy commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
> +                                              new ConfirmCallback() {
ConfirmCallback is nullable so no need to create this ConfirmCallback that does nothing

2016-09-22 07:02 UTC, svor commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
> +                                              new ConfirmCallback() {
fixed, thx!

2016-09-22 07:02 UTC, svor commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
> +                if (object != null && object.containsKey("rootResources")) {
fixed, thx!

2016-09-22 07:03 UTC, svor commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
> +                                              new ConfirmCallback() {
fixed, thx!

2016-09-22 10:03 UTC, vparfonov commented
@garagatyi pls review

2016-09-22 13:03 UTC, garagatyi commented on wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/AgentHealthStateDto.java
> +    String getAgentId();
What is Agent ID?

2016-09-22 13:05 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/AgentHealthChecker.java
> + * Interface which describes mechanism for checking agent's state.
It is not mandatory to explain purpose of interface with interface term

2016-09-22 13:07 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/AgentHealthChecker.java
> +     *         development machine instance
Is it for development machine only?

2016-09-22 13:08 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/AgentHealthChecker.java
> +     * @throws BadRequestException
Please add explanation for this exception

2016-09-22 13:08 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/AgentHealthChecker.java
> +     * @throws ConflictException
Please add explanation for these exception

2016-09-22 13:10 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/AgentHealthCheckerService.java
> +public class AgentHealthCheckerService extends Service {
Please add tests for this class

2016-09-22 13:20 UTC, vparfonov commented on wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/AgentHealthStateDto.java
> +    String getAgentId();
some id of agent or reference, what problem here ?

2016-09-22 13:20 UTC, vparfonov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/AgentHealthChecker.java
> +     *         development machine instance
yep good catch, it can be any machine

2016-09-22 13:35 UTC, gazarenkov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/AgentHealthChecker.java
> +     *         development machine instance
The purpose and life cycle of it has to be properly documented.
In particular:
- why it needed 
- what and when calls check method

2016-09-22 13:38 UTC, garagatyi requested changes

2016-09-22 13:38 UTC, garagatyi commented on wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/AgentHealthStateDto.java
> +    String getAgentId();
My concern is in addition of new terminology -agent ID

2016-09-27 11:43 UTC, vparfonov approved these changes

2016-09-27 12:09 UTC, gazarenkov commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
>  @Singleton
No single word about purpose of this class, the same for public methods.
Please add java docs.

2016-09-27 12:17 UTC, gazarenkov commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
> +        final String url = restContext + "/workspace/" + devMachine.getWorkspace() + "/check";
Can not we put and take this URL from DevMachine?
Such a string concatenation looks bad.
BTW, DevMachine is initialized not in constructor, what if DevMachine == null by any reason?

2016-09-27 12:19 UTC, gazarenkov commented on wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WsAgentHealthStateDto.java
> +    void setReason(String reason);
Could not we remove set methods in DTO (in general)?

2016-09-27 12:20 UTC, skabashnyuk approved these changes

2016-09-27 12:20 UTC, skabashnyuk commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +
extra space

2016-09-27 12:20 UTC, skabashnyuk commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +
extra space

2016-09-27 12:23 UTC, gazarenkov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> + */
Will we really have several implementations of it?

2016-09-27 12:24 UTC, vparfonov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> + */
Yes for codenvy it require authorization token

2016-09-27 12:24 UTC, vparfonov commented on wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WsAgentHealthStateDto.java
> +    /** Returns status code. */
it just HTTP status code

2016-09-27 12:25 UTC, vparfonov commented on wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WsAgentHealthStateDto.java
> +    void setReason(String reason);
ok np

2016-09-27 12:25 UTC, vparfonov commented on wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WsAgentHealthStateDto.java
> +    void setReason(String reason);
ok np

2016-09-27 12:58 UTC, mshaposhnik commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +                wsAgent = server;
can we stop iterations here ?

2016-09-27 12:58 UTC, mshaposhnik commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 404, message = "The workspace with specified id does not exist"),
PLs add status codes for BadRequest (400), Conflict(409), Unauthrorized(401) (btw who is throwing unauthorized?)

2016-09-27 12:58 UTC, mshaposhnik commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +        validateKey(key);
This check is not needed if we accept oly ID's (and no composite keys)

2016-09-27 13:07 UTC, vparfonov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +                wsAgent = server;
+1

2016-09-27 13:26 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 404, message = "The workspace with specified id does not exist"),
ok for 400 and I think don't need to add for other two (409 and 401),we don't have situations where it can be threw.

2016-09-27 13:27 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +                wsAgent = server;
ok, we can

2016-09-27 13:27 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +        validateKey(key);
ok

2016-09-28 10:01 UTC, garagatyi requested changes
PR requires some fixes. Also, please, clarify questions in comments

2016-09-28 10:01 UTC, garagatyi commented on assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
> +        bind(WsAgentHealthChecker.class).to(WsAgentHealthCheckerImpl.class);
We use FQNs in modules

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     *         if the user is not workspace owner
What about workspace workers?

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     * @throws BadRequestException
This exception should not be used outside of REST services.

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     * @throws UnauthorizedException
How it it possible? Is this functionality behind the login filter?

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     * @throws ConflictException
Can you explain in which situation this exception might be thrown?

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +    private static final String WS_AGENT_SERVER_NOT_FOUND_ERROR = "Workspace agent server not found in dev machine.";
This component doesn't control if provided machine is dev-machine or not, so message makes not always correct assumption that provided machine is dev-machine.

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +                                      .withReason("Workspace Agent not available if Dev machine are not RUNNING");
It is not obvious why this code makes assumption that provided machine is dev-machine and that it is not in RUNNING state

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +    protected HttpJsonRequest createPingRequest(Machine machine) throws ServerException {
This method should reuse already found server of ws-agent.

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +        if (wsAgentServer == null) {
Remove this check - it is done already in line 73

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +    @Path("/{id}/check")
This path is not very REST compliant. Consider **/{id}/ws-agent/health**, **/{id}/ws-agent/availability**. @gazarenkov WDYT?

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 403, message = "The user is not workspace owner"),
What about WS workers?

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             IOException,
IOException should not be exposed here

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             UnauthorizedException,
is this method behind login filter?

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             BadRequestException,
Don't see the case when this exception can be thrown

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             ConflictException {
In which case this exception can be thrown?

2016-09-28 10:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                    .withReason("Workspace Agent isn't available if Dev machine isn't RUNNING");
Please check if term **dev-machine** is blessed for error messages

2016-09-28 10:03 UTC, garagatyi commented on wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WsAgentHealthStateDto.java
> +    void setReason(String reason);
Yes

2016-09-28 10:04 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +                               .withReason(response.asString());
Do we want to have a reason as strigified json?

2016-09-28 10:23 UTC, vparfonov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +                               .withReason(response.asString());
no

2016-09-28 10:25 UTC, vparfonov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 403, message = "The user is not workspace owner"),
What about WS workers?

2016-09-28 10:27 UTC, dkuleshov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 403, message = "The user is not workspace owner"),
What about WS workers?

2016-09-28 10:28 UTC, vparfonov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                    .withReason("Workspace Agent isn't available if Dev machine isn't RUNNING");
what?

2016-09-28 10:33 UTC, svor commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
>  @Singleton
done

2016-09-28 10:35 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             BadRequestException,
https://github.com/eclipse/che/pull/2530/files/eb2941a06fde014cb073401ac8fadf6edcdc1f8b#diff-935137151895ccef099e99278ede5dfcR79

2016-09-28 10:35 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             UnauthorizedException,
https://github.com/eclipse/che/pull/2530/files/eb2941a06fde014cb073401ac8fadf6edcdc1f8b#diff-935137151895ccef099e99278ede5dfcR79

2016-09-28 10:35 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 403, message = "The user is not workspace owner"),
What about WS workers?

2016-09-28 10:36 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             IOException,
ok

2016-09-28 10:36 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             ConflictException {
https://github.com/eclipse/che/pull/2530/files/eb2941a06fde014cb073401ac8fadf6edcdc1f8b#diff-935137151895ccef099e99278ede5dfcR79

2016-09-28 10:37 UTC, sleshchenko commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 403, message = "The user is not workspace owner"),
Nothing

2016-09-28 10:39 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +        if (wsAgentServer == null) {
ok

2016-09-28 10:39 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +    protected HttpJsonRequest createPingRequest(Machine machine) throws ServerException {
ok

2016-09-28 10:41 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +                                      .withReason("Workspace Agent not available if Dev machine are not RUNNING");
changed

2016-09-28 10:41 UTC, riuvshin commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 403, message = "The user is not workspace owner"),
![CONFUSED](http://www.travoltaconfused.com/img/c61d512.gif)

2016-09-28 10:44 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +    private static final String WS_AGENT_SERVER_NOT_FOUND_ERROR = "Workspace agent server not found in dev machine.";
changed

2016-09-28 10:44 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     * @throws ConflictException
https://github.com/eclipse/che/pull/2530/files/eb2941a06fde014cb073401ac8fadf6edcdc1f8b#diff-935137151895ccef099e99278ede5dfcR79

2016-09-28 10:45 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     * @throws UnauthorizedException
https://github.com/eclipse/che/pull/2530/files/eb2941a06fde014cb073401ac8fadf6edcdc1f8b#diff-935137151895ccef099e99278ede5dfcR79

2016-09-28 10:45 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     * @throws BadRequestException
https://github.com/eclipse/che/pull/2530/files/eb2941a06fde014cb073401ac8fadf6edcdc1f8b#diff-935137151895ccef099e99278ede5dfcR79

2016-09-28 10:45 UTC, dmytro-ndp commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 403, message = "The user is not workspace owner"),
Who is WS woker?

2016-09-28 10:46 UTC, svor commented on assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
> +        bind(WsAgentHealthChecker.class).to(WsAgentHealthCheckerImpl.class);
fixed

2016-09-28 12:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     * @throws BadRequestException
It is not reason to expose that exception

2016-09-28 12:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     * @throws UnauthorizedException
It is not reason to expose that exception

2016-09-28 12:01 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     * @throws ConflictException
It is not reason to expose that exception

2016-09-28 12:02 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 403, message = "The user is not workspace owner"),
They are users who also can use IDE but they are not owners of WS, so description looks not complete

2016-09-28 12:04 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             BadRequestException,
It should not be thrown by REST this service, so should not be exposed in this method

2016-09-28 12:04 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             UnauthorizedException,
It should not be thrown by REST this service, so should not be exposed in this method

2016-09-28 12:04 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                                                                                             ConflictException {
It should not be thrown by REST this service, so should not be exposed in this method

2016-09-28 12:05 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                    .withReason("Workspace Agent isn't available if Dev machine isn't RUNNING");
I think the most modern term ws-machine, but I'm not sure. @eivantsov can you help with that?

2016-09-28 12:08 UTC, gazarenkov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> + */
I doubt it worth another implementation. I'd say we need a policy for it - like if there are no token it is taken as "allowed". I suppose Codenvy always includes token and Che always does not. Is not it?

2016-09-28 12:09 UTC, gazarenkov commented on wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WsAgentHealthStateDto.java
> +    /** Returns status code. */
Why not to say it is java-docs and name the parameter accordingly?

2016-09-28 12:43 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     *         if the user is not workspace owner
fixed

2016-09-28 12:43 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +     * @throws BadRequestException
fixed

2016-09-28 12:57 UTC, vparfonov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> + */
Yes we include token in other implementation that provided in codenvy repository. Or i don't understand your notes

2016-09-29 08:14 UTC, eivantsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                    .withReason("Workspace Agent isn't available if Dev machine isn't RUNNING");
dev-machine is what's it's called in consoles panel right now

2016-09-29 08:42 UTC, svor commented on wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WsAgentHealthStateDto.java
> +    /** Returns status code. */
updated jdoc

2016-09-29 08:45 UTC, garagatyi requested changes

2016-09-29 08:45 UTC, garagatyi commented on assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
> +import org.eclipse.che.api.agent.server.WsAgentHealthChecker;
Remove unneeded imports

2016-09-29 08:46 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +        final Map<String, ? extends Server> servers = machine.getRuntime().getServers();
Consider moving of this line to getWsAgent method since it is not used anywhere else.

2016-09-29 09:18 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +        final Map<String, ? extends Server> servers = machine.getRuntime().getServers();
done!

2016-09-29 09:21 UTC, svor commented
@garagatyi  I've applied your remarks, take a look please again!

2016-09-29 09:22 UTC, garagatyi requested changes

2016-09-29 09:53 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +            final HttpJsonResponse response = pingRequest.request();
Agree with internal server error

2016-09-29 09:53 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +        if (!wsAgentPingUrl.endsWith("/")) {
added

2016-09-29 09:53 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +    @ApiOperation(value = "Get state of the workspace agent by the workspace id and agent id")
removed

2016-09-29 09:53 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 400, message = "Missed required parameters, parameters are not valid"),
removed

2016-09-29 09:54 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
> +                   @ApiResponse(code = 404, message = "The workspace with specified id does not exist"),
in this case it's internal server error

2016-09-29 10:10 UTC, garagatyi requested changes

2016-09-29 10:10 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +    WsAgentHealthStateDto check(Machine machine) throws NotFoundException, ServerException;
please remove not found exception from method declaration

2016-09-29 10:10 UTC, garagatyi commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
> +                Log.error(getClass(), arg.getMessage());
Will it handle internal server error in appropriate way?

2016-09-29 10:10 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +            final HttpJsonResponse response = pingRequest.request();
This pinging miss super new feature of internal/external urls of agents contributed by Mario. So if it is possible please create single component for pinging and use it here and in WsAgentlauncherImpl.

2016-09-29 13:04 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthChecker.java
> +    WsAgentHealthStateDto check(Machine machine) throws NotFoundException, ServerException;
ok

2016-09-29 13:04 UTC, svor commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/machine/WsAgentStateController.java
> +                Log.error(getClass(), arg.getMessage());
yes

2016-09-29 13:04 UTC, svor commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/WsAgentHealthCheckerImpl.java
> +            final HttpJsonResponse response = pingRequest.request();
done

2016-09-29 13:33 UTC, garagatyi approved these changes
Great job!

2016-10-10 08:06 UTC, merged