CODENVY-587: Handle closed consumers in composite line comsumer
eclipse/che pull request #2549
Opened 2016-09-22 13:49 UTC by mmorhun

### What does this PR do?
Fix wrong behaviour of composite line consumer

### What issues does this PR fix or reference?
https://github.com/codenvy/codenvy/issues/587

### Previous behavior
Composite line consumer tried to write into all subconsumers

### New behavior
Composite line consumer writes only to non-closed subconsumers

### PR type
- [ ] Minor change = no change to existing features or docs
- [ ] Major change = changes existing features or docs

### Minor change checklist
- [ ] New API required?
- [ ] API updated
- [ ] Tests provided / updated
- [ ] Tests passed

2016-09-22 13:52 UTC, mmorhun commented
@garagatyi @skabashnyuk review please

2016-09-23 07:10 UTC, benoitf commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +        Arrays.stream(lineConsumers).forEach(this.lineConsumers::add);
is Arrays.asList(lineConsumers) not working ?

2016-09-23 07:12 UTC, benoitf commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    LOG.error(String.format("An error occurred while writing line to the line consumer %s", lineConsumer), e);
is LineConsumer always have nice toString() ? Could we say also the line that we tried to log ?

2016-09-23 08:18 UTC, mmorhun commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +        Arrays.stream(lineConsumers).forEach(this.lineConsumers::add);
@benoitf `Arrays.asList` returns immutable list, which is not fit here

2016-09-23 08:19 UTC, mmorhun commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    LOG.error(String.format("An error occurred while writing line to the line consumer %s", lineConsumer), e);
@benoitf, we have default `toString()` here, but I think that it is enough. We'll have consumer implementation class name and exception stacktrace.

2016-09-23 08:19 UTC, mmorhun commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    LOG.error(String.format("An error occurred while writing line to the line consumer %s", lineConsumer), e);
@benoitf, do you think we need to log that? For example, an output of user's command?

2016-09-23 08:44 UTC, benoitf commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    LOG.error(String.format("An error occurred while writing line to the line consumer %s", lineConsumer), e);
maybe not I was just trying to see which error message could be helpful to debug/understand what was the issue

2016-09-23 12:07 UTC, mmorhun commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    LOG.error(String.format("An error occurred while writing line to the line consumer %s", lineConsumer), e);
@benoitf thank you, sometimes logged information isn't enough, but the problem here is the reason why it happens.

2016-09-23 12:11 UTC, benoitf commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +        Arrays.stream(lineConsumers).forEach(this.lineConsumers::add);
why it's an issue to have immutable list ?

2016-09-26 10:56 UTC, mmorhun commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +        Arrays.stream(lineConsumers).forEach(this.lineConsumers::add);
because we have to remove closed consumers from the list

2016-09-26 15:20 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +        this.lineConsumers = new ArrayList<>(lineConsumers.length);
Arrays.asList();

2016-09-26 15:22 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +    private       boolean            isClosed;
Will it work in multi-threaded environment?

2016-09-26 15:25 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    lineConsumers.remove(lineConsumer); // consumer is already closed, so we cannot write into it any more
Is it an appropriate way to remove from source while you are iterating through it?

2016-09-26 15:30 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/ConsumerAlreadyClosedException.java
> + * @author Mykola Morhun
Javadocs

2016-09-26 15:30 UTC, garagatyi requested changes

2016-09-28 06:41 UTC, benoitf commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    lineConsumers.remove(lineConsumer); // consumer is already closed, so we cannot write into it any more
I would say a test is required with isClosed and writeLine throwing exceptions

2016-09-28 13:46 UTC, garagatyi requested changes

2016-09-28 13:46 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +            isClosed = true;
These operations are not atomic. Consider usage of AtomicBoolean

2016-09-28 13:46 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    LOG.error(String.format("An error occurred while closing the line consumer %s", lineConsumer), e);
I think that toString in line consumers returns pointer to memory area. Do we need that in error message?

2016-09-28 13:46 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
>   * @author andrew00x
Please add javadocs

2016-09-28 13:46 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
>      public void close() throws IOException {
Please add javadoc that explains behavior of this implementation of consumer for writeLine and close methods

2016-09-28 13:46 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    lineConsumers.remove(lineConsumer); // consumer is already closed, so we cannot write into it any more
@mmorhun Please address my comment

2016-09-28 13:46 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                } catch (ConsumerAlreadyClosedException | ClosedByInterruptException e) {
If ClosedByInterruptException is thrown this class should not continue work

2016-09-28 13:46 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    LOG.error(String.format("An error occurred while writing line to the line consumer %s", lineConsumer), e);
agree with Florent - toString here has no sense

2016-09-28 13:46 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/ProgressMonitor.java
> -    void updateProgress(ProgressStatus currentProgressStatus);
Throwing this exception here doesn't make sense because this class doesn't declare any dependency on line consumer

2016-09-28 13:46 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/FileLineConsumer.java
> +        try {
please check closing status here

2016-10-04 14:26 UTC, mmorhun commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    lineConsumers.remove(lineConsumer); // consumer is already closed, so we cannot write into it any more
Fixed by using `CopyOnWriteArrayList`

2016-10-04 14:28 UTC, mmorhun commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +                    LOG.error(String.format("An error occurred while writing line to the line consumer %s", lineConsumer), e);
I think it is still usable, because we will know consumer implementation

2016-10-04 14:29 UTC, mmorhun commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> +    private       boolean            isClosed;
thx, fixed

2016-10-31 15:33 UTC, garagatyi requested changes

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentCompositeLineConsumer.java
> +        if (isOpen) {
Is this thread-safe?

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentCompositeLineConsumer.java
> +        if (isOpen && lock.readLock().tryLock()) {
Is this thread-safe?

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentFileLineConsumer.java
> + * @author andrew00x
Javadocs?

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/CompositeLineConsumer.java
> + * Is used when lines should be written into two or more consumers.
Add a note that it is not thread-safe

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/FileLineConsumer.java
>   * @author andrew00x
Javadocs? And add a note that it is not thread-safe

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/FileLineConsumer.java
> +
Why you added these empty lines?

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentFileLineConsumer.java
> +        if (isOpen) {
I suppose that convenient way to do that is AtomicBoolean.compareAndSet()

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/CompositeLineConsumerTest.java
> +    public void shouldCloseSubConsumerOnConsumerAlreadyClosedException(Throwable exception) throws Exception {
Name of the method describes only 1 situation

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/CompositeLineConsumerTest.java
> +        doThrow(exception.getClass()).when(closedConsumer).writeLine(anyString());
Why not throw exception instance?

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/CompositeLineConsumerTest.java
> +            doNothing().when(lineConsumer).writeLine(anyString());
I think that it is default behavior. Do we need to declare that in additionally?

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/CompositeLineConsumerTest.java
> +        for (int i = 0; i < subConsumers.length; i++) {
Looks too complicated, try to simplify.

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/CompositeLineConsumerTest.java
> +        for (int i = 0; i < subConsumers.length; i++) {
Why existing sub consumers take part in this code? Looks like they are unrelated

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/FileLineConsumerTest.java
> +    private final File file = new File(System.getProperty("java.io.tmpdir") + System.getProperty("file.separator") + "tmp.file");
I suppose java has something special for such a case

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/FileLineConsumerTest.java
> +        injectWriterMock(fileLineConsumer, writer);
Is it better to do that in single place?

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentCompositeLineConsumerTest.java
> +        for (LineConsumer subConsumer : subConsumers) {
The same comments to the whole class as to the non multi-threaded version.

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentCompositeLineConsumerTest.java
> +
I don't see any multi-threaded tests

2016-10-31 15:33 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentFileLineConsumerTest.java
> +}
See comments above. I don't see multi-threaded tests

2016-10-31 15:33 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/ProgressMonitor.java
> +import java.io.IOException;
Please clean up this class

2016-10-31 16:30 UTC, mmorhun commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentCompositeLineConsumer.java
> +        if (isOpen) {
thx, I forgot volatile

2016-10-31 17:01 UTC, mmorhun commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/CompositeLineConsumerTest.java
> +            doNothing().when(lineConsumer).writeLine(anyString());
ok, I'll remove it

2016-11-01 07:51 UTC, mmorhun commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/FileLineConsumerTest.java
> +    private final File file = new File(System.getProperty("java.io.tmpdir") + System.getProperty("file.separator") + "tmp.file");
I like hard way :)

2016-11-02 08:44 UTC, garagatyi commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/FileLineConsumer.java
> + * Also see multithreaded implementation {@link org.eclipse.che.api.core.util.lineconsumer.ConcurrentFileLineConsumer}
Links to other classes can be formatted with **@see** annotation

2016-11-02 09:45 UTC, garagatyi approved these changes
Nice job!
Please consider suggested improvements

2016-11-02 09:45 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentCompositeLineConsumerTest.java
> +        List<LineConsumer> allElements = new ArrayList<>(Arrays.asList(base));
See comment above

2016-11-02 09:45 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentCompositeLineConsumerTest.java
> +    public void shouldIgnoreWriteToSubConsumersWhenLockForCloseIsLocked() throws Exception {
afterCloseWasCalled?

2016-11-02 09:45 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentCompositeLineConsumerTest.java
> +        waitingAnswer2.completeAnswer();
Please ensure that close methods weren't called before all writes are finished

2016-11-02 09:45 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentCompositeLineConsumerTest.java
> +            verify(consumer).writeLine(eq(message2));
what about verifying that close methods of internal consumers were called?

2016-11-02 09:45 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentFileLineConsumerTest.java
> +        executor.execute(this::closeConsumer);
I'm not sure that it is OK to ignore possible exception here

2016-11-02 09:45 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentFileLineConsumerTest.java
> +        writeIntoConsumer("Test line");
I'm not sure that it is OK to ignore possible exception here

2016-11-02 09:45 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentFileLineConsumerTest.java
> +        executor = Executors.newFixedThreadPool(5);
Do you really use 5 threadds here?

2016-11-02 09:45 UTC, garagatyi commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentCompositeLineConsumerTest.java
> +        executor = Executors.newFixedThreadPool(5);
Do you really use 5 threads here?

2016-11-03 11:15 UTC, mmorhun commented on core/che-core-api-core/src/test/java/org/eclipse/che/api/core/util/lineconsumer/ConcurrentFileLineConsumerTest.java
> +        writeIntoConsumer("Test line");
I think, that it is OK. IMO, good test shouldn't know about an implementation, but be able to verify correct work of functionality. Here we shouldn't care about implementation behaviour in the test case (do nothing, log warning/error or throw an exception). All what we need to know that method which prints message in subconsumer wasn't invoked.

2016-11-15 07:52 UTC, skabashnyuk approved these changes

2016-11-15 13:00 UTC, merged