CHE-1754: improve ide loader
eclipse/che pull request #2589
Opened 2016-09-26 12:28 UTC by olexii4

### What does this PR do?
IDE loader Improving  (it changed loader widget content and its styles).

![selection_012](https://cloud.githubusercontent.com/assets/6310786/18833798/1ee5e310-83fb-11e6-89ea-2725b66b6027.png)

Signed-off-by: Oleksii Orel <oorel@codenvy.com>

2016-09-26 12:32 UTC, benoitf commented on dashboard/src/app/ide/ide.html
> +          <span>Loader idea</span>
Could you attach an animated gif ?
Because I'm not sure we should display "loader idea" text

2016-09-26 12:32 UTC, benoitf requested changes

2016-09-26 12:33 UTC, slemeur commented on dashboard/src/app/ide/ide.html
> +          <span>Loader idea</span>
We should definitely not show it.

2016-09-26 15:29 UTC, benoitf approved these changes
ok for technical part
for UI I let @slemeur

2016-09-27 06:16 UTC, benoitf commented on .gitignore
> +dashboard/src/**/*.js
I don't have on my side the typescript built source in the same folder so I'm not sure about this exclude ?

2016-09-27 06:17 UTC, ashumilova approved these changes

2016-09-27 07:15 UTC, akurinnoy approved these changes

2016-09-27 07:48 UTC, olexii4 commented on .gitignore
> +dashboard/src/**/*.js
Sorry. It needed for some built in compiler. It very useful to go through to resources. I have removed this commit.

2016-09-27 07:48 UTC, olexii4 commented
@benoitf Sorry. It needed for some built in compiler. It very useful to go through to resources. I have removed this commit.

2016-09-27 07:51 UTC, benoitf commented
@olexii4 is that builtin compiler could generate in a separate folder ? because I think it should be difficult to have all files in same folders no ?
Also is that sourceMaps isn't working ?

2016-09-27 08:00 UTC, olexii4 commented
@benoitf  It is configurable. I have removed this commit.

2016-09-27 08:17 UTC, slemeur commented
It looks okay for me.
We need to try to use this loader in other areas - where we has the small vertical bars loader.
In this case, I would think that the Che logo must have to be white.

2016-09-28 12:52 UTC, slemeur commented
So looking at the changes in the animation, I'm -1 for changing the vertical bar from other places than the splash-screen. (ie, the left navbar and in the IDE)

2016-09-29 07:53 UTC, olexii4 commented
![anim](https://cloud.githubusercontent.com/assets/6310786/18945389/04d6072c-8633-11e6-845e-f1381efe5859.gif)

2016-09-29 07:55 UTC, slemeur approved these changes

2016-09-29 09:18 UTC, merged