CHE-2524: Change parameter type in JpaUserDao
eclipse/che pull request #2743
Opened 2016-10-10 08:49 UTC by vinokurig

### What does this PR do?
Change `skipCount` parameter type from `int` to `long` in `UserManager` `getAll()` method.

It is needed for https://github.com/codenvy/codenvy/blob/ec392104ad069fda236ddb347020658eaccafe56/wsmaster/codenvy-hosted-api-audit/src/main/java/com/codenvy/api/audit/server/AuditManager.java#L170

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/2524

2016-10-11 08:19 UTC, sleshchenko commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/jpa/JpaUserDao.java
> +            throw new IllegalArgumentException("Skip count parameter must not be more than " + Integer.MAX_VALUE);
WDYT about using Preconditions#checkArgument here?

2016-10-11 08:31 UTC, vinokurig commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/jpa/JpaUserDao.java
> +            throw new IllegalArgumentException("Skip count parameter must not be more than " + Integer.MAX_VALUE);
Yes, looks much better, thanks, changed.

2016-10-12 10:40 UTC, evoevodin commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/jpa/JpaUserDao.java
> +        /* 'managerProvider.get().setFirstResult(int)' requires int value in its parameters
i'd say that comment is useless here + i don't think that commenting all the check where page is returned may be useful either, can you please remove it ?

2016-10-12 10:44 UTC, voievodin requested changes
check out my comments

2016-10-12 10:45 UTC, evoevodin commented
Add yourself as author to those classes you change

2016-10-12 12:36 UTC, evoevodin commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/spi/UserDao.java
> + * @author Igor Vinokur
you didn't change this interface, why did you add yourself as author?

2016-10-12 12:37 UTC, evoevodin commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/jpa/JpaUserDao.java
> +        checkArgument(skipCount <= Integer.MAX_VALUE, "Skip count parameter must not be greater than " + Integer.MAX_VALUE);
can we use a single checkArgument for skipCount ?

2016-10-12 12:39 UTC, evoevodin commented on wsmaster/che-core-api-user/src/test/java/org/eclipse/che/api/user/server/jpa/JpaUserDaoTest.java
> +        Field field = JpaUserDao.class.getDeclaredField("managerProvider");
Can you please use `@InjectMocks` instead

2016-10-12 12:40 UTC, evoevodin commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/UserManager.java
> + * @author Igor Vinokur
Did you change the manager?

2016-10-12 13:18 UTC, vinokurig commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/jpa/JpaUserDao.java
> +        checkArgument(skipCount > Integer.MAX_VALUE, "Skip count parameter must not be more than " + Integer.MAX_VALUE);
done

2016-10-12 13:21 UTC, vinokurig commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/spi/UserDao.java
> + * @author Igor Vinokur
Actually changed, but a little, removed

2016-10-12 13:21 UTC, vinokurig commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/jpa/JpaUserDao.java
> +        checkArgument(skipCount <= Integer.MAX_VALUE, "Skip count parameter must not be greater than " + Integer.MAX_VALUE);
done

2016-10-12 13:21 UTC, vinokurig commented on wsmaster/che-core-api-user/src/test/java/org/eclipse/che/api/user/server/jpa/JpaUserDaoTest.java
> +        Field field = JpaUserDao.class.getDeclaredField("managerProvider");
done

2016-10-12 13:24 UTC, vinokurig commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/UserManager.java
> + * @author Igor Vinokur
Yes, but a little, removed the `@author`

2016-10-13 10:52 UTC, skabashnyuk commented
Can you add test to skip Integer.MAX_NUMBER+1

2016-10-13 10:57 UTC, skabashnyuk requested changes

2016-10-13 10:57 UTC, skabashnyuk commented on wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/jpa/JpaUserDao.java
> +                                                       .setFirstResult((int)skipCount)
I don't see any point in this pr because of this cast.

2016-10-13 12:15 UTC, vinokurig commented
@skabashnyuk The test is already present: https://github.com/eclipse/che/blob/8ce0f5c45d7d3614012e42d563d63790fd8b871c/wsmaster/che-core-api-user/src/test/java/org/eclipse/che/api/user/server/jpa/JpaUserDaoTest.java#L68-L72

2016-10-15 18:09 UTC, skabashnyuk commented
Ok. Can you describe purpose of this issue? To move cast from https://github.com/codenvy/codenvy/blob/ec392104ad069fda236ddb347020658eaccafe56/wsmaster/codenvy-hosted-api-audit/src/main/java/com/codenvy/api/audit/server/AuditManager.java#L170
to  .setFirstResult((int)skipCount) ?

2016-10-17 06:53 UTC, vinokurig commented
@skabashnyuk Yes, for `Audit manager`, and for future, when it will be needed to list all users.

2016-10-24 14:22 UTC, evoevodin commented on ide/commons-gwt/src/main/java/org/eclipse/che/ide/websocket/AbstractMessageBus.java
> +            ws = WebSocket.create("ws://localhost:8080/wsmaster/api/ws/workspace");
What's that?

2016-10-24 14:23 UTC, voievodin approved these changes

2016-10-24 15:03 UTC, sleshchenko approved these changes

2016-10-25 09:55 UTC, skabashnyuk approved these changes

2016-10-25 11:22 UTC, merged