CHE-2816. Correctly applying exclude filters at indexing files
eclipse/che pull request #2857
Opened 2016-10-21 09:36 UTC by RomanNikitenko

### What does this PR do?
- avoid to duplicate '*' for searching request
- correctly applying exclude filters at indexing files

### What issues does this PR fix or reference?
#2816 

Signed-off-by: Roman Nikitenko <rnikitenko@codenvy.com>

2016-10-24 06:42 UTC, skabashnyuk requested changes
`correctly applying exclude filters at indexing files`
This is an unclear statement. Please specify why and how are you going to fix it.

2016-10-24 07:38 UTC, RomanNikitenko commented
@skabashnyuk I've added some explanation to clarify how I'm going to fix it

2016-10-24 12:28 UTC, skabashnyuk approved these changes

2016-10-25 13:35 UTC, vparfonov approved these changes

2016-10-25 15:09 UTC, merged