CHE-2832: Add servers to Agent description and propagate them to Workspace Runtime
eclipse/che pull request #2868
Opened 2016-10-24 11:30 UTC by tolusha

### What does this PR do?
Adds servers to Agent description and propagates them to Workspace Runtime

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/2832

2016-10-24 11:32 UTC, tolusha commented
@vparfonov @garagatyi 
pls review

2016-10-27 08:17 UTC, garagatyi requested changes

2016-10-27 08:17 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/MachineInstanceProvider.java
> +                          List<? extends ServerConf> providedServers) throws ServerException;
This class works with kinda docker terminology. It knows nothing about serversConf and other Che model staf. So it is better to move this code into CheEnvironmentEngine that should apply serverConf to CheServiceImpl to describe docker container. Then server conf can be recovered from docker container labels/exposed ports. You can find that logick in DockerInstanceRuntimeInfo class

2016-10-27 11:53 UTC, tolusha commented
@garagatyi 
updated

2016-10-27 16:10 UTC, garagatyi requested changes

2016-10-27 16:10 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/CheEnvironmentEngine.java
> +                addAgentsProvidedServers(machine, agents);
Looks like it is not called on start of the whole environment

2016-10-28 12:56 UTC, tolusha commented
@garagatyi 
updated

2016-10-28 13:08 UTC, slemeur commented
nice!

2016-10-28 13:50 UTC, garagatyi approved these changes
Good job!

2016-10-31 07:17 UTC, merged