CHE-1878: Remove workspace id from websocket connection path to master
eclipse/che pull request #2907
Opened 2016-10-27 07:09 UTC by vinokurig

### What does this PR do?
Removes workspace id from websocket connection path to master.

### What issues does this PR fix or reference?
#1787

### Previous behavior
Separate web-socket connection was created for each workspase.

### New behavior
All workspaces are using one web-socket connection.

@vparfonov @akurinnoy @ashumilova Please review

2016-10-27 08:55 UTC, benoitf requested changes

2016-10-27 08:55 UTC, benoitf commented on dashboard/src/components/api/che-websocket.factory.ts
> +  getBus() {
this kind of change needs to be applied on getRemoteBus as well

2016-10-27 08:56 UTC, benoitf commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/web.xml
> +        <param-value>/ws</param-value>
could we have http redirect from /ws/<id> to /ws ?
for backward compliance for existing clients ?

2016-10-27 11:56 UTC, vinokurig commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/web.xml
> +        <param-value>/ws</param-value>
This is a network issue. This needs investigation.

2016-10-27 11:58 UTC, benoitf commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/web.xml
> +        <param-value>/ws</param-value>
ok

2016-10-27 11:59 UTC, benoitf approved these changes
Except the fact that I would want to have a redirect from /ws/<id> to /ws for any existing clients, ok for me

2016-10-27 12:35 UTC, akurinnoy approved these changes

2016-10-28 06:11 UTC, vparfonov approved these changes

2016-10-31 07:57 UTC, ashumilova approved these changes

2016-10-31 14:24 UTC, merged

2016-11-02 10:25 UTC, benoitf commented
@vinokurig  is that https://github.com/eclipse/che/blob/47193dc85bcfd00f2dc03dc7f86c22f4cf6dd4e4/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceServiceLinksInjector.java#L133-135 should have been updated ?

2016-11-02 10:44 UTC, vinokurig commented
@benoitf Thank you, I will fix that.

2016-11-02 10:45 UTC, benoitf commented
@vinokurig I've found another location, I will provide PR to fix it

2016-11-02 10:49 UTC, vinokurig commented
@benoitf ok, thanks