CHE-2874 Let users configure the 'Z' flag when mouting a volume
eclipse/che pull request #2921
Opened 2016-10-27 18:57 UTC by snjeza

### What does this PR do?

It adds the following two properties:

machine.docker.volumes.projects.options (Z by default)

that is used when che mounts the /projects volume

machine.docker.volumes.workspace.options (ro,Z by default)

used when mounting the following volumes:

/mnt/che/terminal
/mnt/che/ws-agent.tar.gz
/mnt/che/conf

Notice:
che-launcher also uses the Z option. I haven't changed it.

### What issues does this PR fix or reference?
#2874

Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

2016-10-27 18:59 UTC, TylerJewell commented
@snjeza - thanks for this contribution.  You may not have seen it, but there was a major merge this morning where we renamed all of the che.properties so that they all start with `che.` and we simplified them to make them clearer for users to understand.   Let me dig up the new che.properties and the merge, and perhaps you can propose a new name and location for these properties?

2016-10-31 16:34 UTC, l0rd commented
LGTM @garagatyi @benoitf can you please have a look at this PR that fixes #2874

2016-10-31 16:44 UTC, benoitf commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/MachineProviderImpl.java
> +            if (volumeOptions != null && !volumeOptions.isEmpty()) {
you should use guava helper isNullOrEmpty / com.google.common.base.Strings.isNullOrEmpty;

2016-10-31 16:44 UTC, benoitf commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/MachineProviderImpl.java
> +                projectFolderVolume = projectFolderVolume + ":" + volumeOptions;
use of += to add to current ?

2016-10-31 16:44 UTC, benoitf commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/DockerExtConfBindingProvider.java
> +            volumeOptions="ro,Z";
IMHO default options should be in properties file or to be a constant

2016-10-31 16:44 UTC, benoitf commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/DockerExtConfBindingProvider.java
> +            return extConfDir.getAbsolutePath() + CONTAINER_TARGET + ":" + volumeOptions;
small concern : maybe to have a getTargetOptions() helper method as there are some duplicates between unix and windows

2016-10-31 16:44 UTC, benoitf commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/WsAgentVolumeProvider.java
> +                volumeOptions="ro,Z";
constants or directly as default properties ?

2016-10-31 16:44 UTC, benoitf commented on plugins/plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/MachineProviderImplTest.java
> +            volumeOptions = "Z";
I think it might be hard to find these value

2016-10-31 17:47 UTC, snjeza commented
I have updated the patch.

2016-10-31 18:16 UTC, benoitf commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/DockerExtConfBindingProvider.java
> +	public static final String EXT_CHE_LOCAL_CONF_DIR = "/mnt/che/conf";
indent is not correct

2016-10-31 18:16 UTC, benoitf commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/DockerExtConfBindingProvider.java
> +        if (volumeOptions == null) {
as @Inject on volumeOptions is not optional, I think that we could get rid of default value from the code as it becomes a mandatory parameter

2016-10-31 18:16 UTC, benoitf commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/TerminalVolumeProvider.java
> +        if (volumeOptions == null) {
same here, as it's a required parameter it needs to be provided so we don't have to handle this

2016-10-31 18:19 UTC, benoitf commented
ci-build

2016-10-31 18:32 UTC, snjeza commented
The patch has been updated.

2016-10-31 19:21 UTC, benoitf approved these changes
need to sync before merging this property for codenvy properties

2016-10-31 20:01 UTC, TylerJewell commented
Nicely done @snjeza - @l0rd - will you be managing the merge process + milestone selection + QA communications?

2016-11-01 00:53 UTC, l0rd commented
@TylerJewell can you be more explicit on the QA communications? I would like to help but I'm not sure to understand what is expected.
@benoitf in what repository are codenvy properties? Should @snjeza update them?

2016-11-01 04:38 UTC, TylerJewell commented
Yes, sure thing.  When you merge the issue that is targeted for a particular milestone, please talk to @vkuznyetsov about whether there should be any additional QA or integration tests added into the CI system that can be run regularly to test this behavior.

All of the "base" che.properties are in `assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes`.

Note that there is a new che.properties that has a new naming scheme. They are all designed to be user friendly.  There is an alias file which maps the new names to the old names so that if you still use the old properties then they will still work for awhile.

2016-11-01 08:55 UTC, garagatyi requested changes
Overall PR is good. Please address my comments

2016-11-01 08:55 UTC, garagatyi commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +che.machine.docker.volumes.workspace.options=ro,Z
According to a comment it related to agents rather to workspace. Probably property name should be aligned with the comment.

2016-11-01 08:55 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/json/HostConfig.java
> +    private String         volumeOptions;
I don't see such field in Docker Create container API. Can you point me out where it is?

2016-11-01 08:55 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/MachineProviderImpl.java
> +                               @Nullable @Named("che.machine.docker.volumes.projects.options") String volumeOptions)
We use dots to separate categories of implementation. We use underscores to separate words of single term. Please ensure that you are following that policy

2016-11-01 08:55 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/DockerExtConfBindingProvider.java
> +    @Named("che.machine.docker.volumes.workspace.options")
Please ensure that you are following properties naming policy described above

2016-11-01 15:43 UTC, snjeza commented
I have changed the names of the properties and added the volumeOptions field to the Docker Create container API.

2016-11-02 08:10 UTC, garagatyi commented
Probably we misunderstand each other. I meant that I can't find volumeOptions in Docker API documentation. So I don't understand why you added such a field in HostConfig object which is our representation of Docker API model.

Can you elaborate?

2016-11-02 14:12 UTC, snjeza commented
I have reviewed the che.docker.privilege property and implemented the che.docker.volumes_projects_options property in a similar way.

2016-11-03 11:24 UTC, garagatyi commented
che.docker.privilege property represents a flag from Docker API documentation, whereas  **volumeOptions** is not present in HostConfig representation.

2016-11-03 15:15 UTC, snjeza commented
I will try to move the volumeOptions property to another class.

2016-11-03 18:41 UTC, snjeza commented
I have removed the volumeOptions property from Docker API documentation.

2016-11-08 15:20 UTC, bmicklea commented
M7 needs to be complete by tomorrow (Nov 8) pushing to M8 but if it's merged tomorrow it can be reassigned to M7.

2016-11-11 14:00 UTC, l0rd commented
@snjeza please let me know when you have confirmed that this PR will [fix the issue when running Che on CentOS 7 with RH packaged Docker](https://issues.jboss.org/browse/CHE-35?focusedCommentId=13308898&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13308898).

2016-11-14 10:24 UTC, garagatyi commented
Sorry for delay, @snjeza. I've refactored code around container bootstrapping for simplifying code for environment SPI implementation. Please rework your PR because of that.

Now volume for projects is bound in LocalCheInfrastructureProvisioner. Other changes in this PR looks good to me

2016-11-15 00:11 UTC, snjeza commented
I have updated the patch.
@l0rd 
I will test the new patch with centos 7. Currently, I can't start the workspace when using the master branch with or without my patch.

2016-11-15 09:07 UTC, garagatyi approved these changes
Good job!

2016-11-17 13:08 UTC, snjeza commented
@l0rd,
I have tested the patch with centos 7. It works. I have had to use the overlay driver to start che with and without the patch.

2016-11-17 13:51 UTC, l0rd commented
Thank you @snjeza 🎉 LGTM

2016-11-17 13:51 UTC, merged

2016-11-17 13:54 UTC, TylerJewell commented
@benoitf - very important that we capture these changes and merge them as part of the CLI consolidation.