Make it possible to use relative links to recipe in workspace environment
eclipse/che pull request #3002
Opened 2016-11-07 13:51 UTC by mshaposhnik

### What does this PR do?
To ease data migration between domains, we should store local recipe links in a relative form. And when necessary, downloader should current domain by itself.

### What issues does this PR fix or reference?
Fixes #2769

2016-11-08 08:45 UTC, skabashnyuk approved these changes

2016-11-08 09:03 UTC, voievodin approved these changes

2016-11-08 09:05 UTC, garagatyi requested changes

2016-11-08 09:05 UTC, garagatyi commented on wsmaster/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/util/RecipeDownloader.java
> +                                .replacePath(apiEndpoint.getPath() + location);
Is it possible that api endpoint doesn't have trailing slash? In that case I suppose it would be better to use .replacePath().path()

2016-11-08 09:05 UTC, garagatyi commented on wsmaster/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/util/RecipeDownloader.java
> +                                .replacePath(apiEndpoint.getPath() + location);
See above

2016-11-08 09:05 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/environment/server/CheEnvironmentEngineTest.java
> -        String additionalServiceComposeFilePart = "\n  " + machineName + ":\n    build:\n      context: " + API_ENDPOINT + "/recipe/12345";
I assume that your changes should not influence these tests

2016-11-08 09:18 UTC, mshaposhnik commented on wsmaster/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/util/RecipeDownloader.java
> +                                .replacePath(apiEndpoint.getPath() + location);
AFAIK api endpoint never contain trailing slash

2016-11-08 09:18 UTC, mshaposhnik commented on wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/environment/server/CheEnvironmentEngineTest.java
> -        String additionalServiceComposeFilePart = "\n  " + machineName + ":\n    build:\n      context: " + API_ENDPOINT + "/recipe/12345";
I's due to regexp change in CheEnvironmentEngine.

2016-11-08 12:41 UTC, garagatyi commented on wsmaster/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/util/RecipeDownloader.java
> +                                .replacePath(apiEndpoint.getPath() + location);
ok

2016-11-09 08:34 UTC, garagatyi approved these changes

2016-11-10 14:56 UTC, merged