Improve default services start strategy.
eclipse/che pull request #3006
Opened 2016-11-07 17:31 UTC by AndrienkoAleksandr

### What does this PR do?
Improve services start strategy. Add detail message when user create compose environment with circle dependency to itself.

@garagatyi please review.
Signed-off-by: Aleksandr Andrienko <aandrienko@codenvy.com>

2016-11-09 21:42 UTC, AndrienkoAleksandr commented
ci-build

2016-11-21 11:39 UTC, AndrienkoAleksandr commented
ci-build

2016-11-21 15:37 UTC, garagatyi requested changes

2016-11-21 15:37 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/DefaultServicesStartStrategy.java
> +                checkDependency(dependsOn, serviceEntry.getKey(), services, "A service can not depend on itself");
We don't have 'service' entity in our public API. User would not understand what that mean if environment is not docker compose.
And message doesn't point to a machine with the error.

2016-11-21 15:37 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/DefaultServicesStartStrategy.java
> +                checkDependency(dependency, serviceEntry.getKey(), services, "A service can not link to itself");
We don't have 'service' entity in our public API. User would not understand what that mean if environment is not docker compose.
And message doesn't point to a machine with the error.

2016-11-21 15:37 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/DefaultServicesStartStrategy.java
> +                checkDependency(dependency, serviceEntry.getKey(), services, "A service can not contain 'volumes_from' to itself");
We don't have 'service' entity in our public API. User would not understand what that mean if environment is not docker compose.
And message doesn't point to a machine with the error.

2016-11-21 15:37 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/DefaultServicesStartStrategy.java
> +                Map.Entry<String, Set<String>> serviceEntry = it.next();
I think that extracting key and value here would make code more readable

2016-11-23 14:50 UTC, AndrienkoAleksandr commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/DefaultServicesStartStrategy.java
> +                Map.Entry<String, Set<String>> serviceEntry = it.next();
Done.

2016-11-30 07:39 UTC, garagatyi approved these changes

2016-12-13 07:43 UTC, skabashnyuk approved these changes

2016-12-13 23:28 UTC, AndrienkoAleksandr commented
ci-build

2016-12-14 05:31 UTC, merged