CHE-3129 - Project can't be created without Z option
eclipse/che pull request #3130
Opened 2016-11-19 23:41 UTC by snjeza

### What does this PR do?

It fixes #3129

### What issues does this PR fix or reference?

#3129

Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

2016-11-20 10:13 UTC, benoitf commented
ci-build

2016-11-21 06:06 UTC, tolusha commented
@garagatyi 
Could you have a look pls. A think it is matter of `che.docker.volumes_projects_options` configuration not code changing.

2016-11-21 08:31 UTC, l0rd commented
@tolusha I think that #3129 needs code changing (in the default config [the property is set](https://github.com/eclipse/che/blob/b7682ddde70f40597cf208f8296e529fbbe4c6c3/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L137)).

@snjeza I think you need do the same check for property `che.docker.volumes_agent_options` and if you could flag the fields/parameters with `@Nullable` it would be nice.

2016-11-21 08:48 UTC, garagatyi requested changes
@snjeza Nice catch!
@tolusha No, code have to be changed in any case.
@l0rd Agree with you, Mario!

@snjeza Please consider comments of Mario and mine. Please also rename volumeOptions argument of constructor to projectsVolumeOptions

2016-11-21 08:48 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/LocalCheInfrastructureProvisioner.java
> +            if (Strings.isNullOrEmpty(volumesOptions)) {
Let's form suffix in constructor. Then you won't need this clause in main code.

2016-11-21 11:48 UTC, snjeza commented
I have updated the patch.

2016-11-21 12:19 UTC, garagatyi requested changes

2016-11-21 12:19 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/LocalCheInfrastructureProvisioner.java
> +	private final String                      projectsVolumeOptions;
Please replace tab character with spaces. Someone put it here but it is not allowed for indentation in Che.

2016-11-21 12:19 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/DockerExtConfBindingProvider.java
> +        if (!Strings.isNullOrEmpty(agentVolumeOptions)) {
Please create constructor and put this code there as you did in LocalCheInfrastructureProvisioner

2016-11-21 12:19 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/TerminalVolumeProvider.java
> +        if (!Strings.isNullOrEmpty(agentVolumeOptions)) {
Please create constructor and put this code there as you did in LocalCheInfrastructureProvisioner

2016-11-21 12:19 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/WsAgentVolumeProvider.java
> +        if (!Strings.isNullOrEmpty(agentVolumeOptions)) {
Please create constructor and put this code there as you did in LocalCheInfrastructureProvisioner

2016-11-21 13:12 UTC, snjeza commented
The patch updated.

2016-11-21 13:23 UTC, garagatyi requested changes
Sorry that still asking you to change your PR, but there are few minor changes to be made.

2016-11-21 13:23 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/DockerExtConfBindingProvider.java
> +        if (!Strings.isNullOrEmpty(agentVolumeOptions)) {
Constructor is called before field injection in Guice. So here we will have null value always. Can you replace field injection with a constructor injection.

2016-11-21 13:23 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/TerminalVolumeProvider.java
> +        if (!Strings.isNullOrEmpty(agentVolumeOptions)) {
Constructor is called before field injection in Guice. So here we will have null value always. Can you replace field injection with a constructor injection.

2016-11-21 13:23 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/WsAgentVolumeProvider.java
> +        if (!Strings.isNullOrEmpty(agentVolumeOptions)) {
Constructor is called before field injection in Guice. So here we will have null value always. Can you replace field injection with a constructor injection.

2016-11-21 16:07 UTC, snjeza commented
The patch updated.
I wasn't able to inject the che.docker.volumes_agent_options option to the DockerExtConfBindingProvider constructor because DockerExtServerModule created it with the empty constructor.
Che doesn't start when I try to bind DockerExtConfBindingProvider to DockerExtServerModule.

2016-11-22 08:01 UTC, garagatyi approved these changes
Good job, Snjezana!

2016-11-22 08:01 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/DockerExtConfBindingProvider.java
> +    @Nullable @Named("che.docker.volumes_agent_options")
OK, then leave it as it is now, I'll fix that in one of my next PRs.

2016-11-22 08:40 UTC, sleshchenko commented
Looks like DockerExtConfBindingProvider shouldn't work correctly because instance is created with default constructor and requestInjection method is not invoked for it. Please make sure that it works correctly

2016-11-22 13:24 UTC, snjeza commented
> Looks like DockerExtConfBindingProvider shouldn't work correctly because instance is created 
> with default constructor and requestInjection method is not invoked for it. Please make sure 
> that it works correctly

That's why I haven't injected the che.docker.volumes_agent_options option to the DockerExtConfBindingProvider constructor.
I have tested the build with and without the Z option. It works properly.

2016-11-22 13:27 UTC, garagatyi commented
If instance of class is created manually and injection is not requested it should not work if I understand how it works. Can you describe how did you test that?

2016-11-22 13:32 UTC, snjeza commented
I have created che-server, started it with different che.properies, created a project, reviewed mounted volumes using "docker inspect". Everything works as expected.

2016-11-22 13:41 UTC, garagatyi commented
@sleshchenko correct me if I'm mistaken but looks like ws-agent configuration works in a different way.

2016-11-22 14:09 UTC, snjeza commented
When excluding the Z option, the volumes are mounted in the following way:

```
 "Mounts": [
            {
                "Source": "/data/workspaces/wksp-8t9p",
                "Destination": "/projects",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/tmp/data/lib/linux_amd64/terminal",
                "Destination": "/mnt/che/terminal",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/tmp/data/lib/ws-agent.tar.gz",
                "Destination": "/mnt/che/ws-agent.tar.gz",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
```

2016-11-22 14:13 UTC, sleshchenko commented
@snjeza Please create folder plugin-conf in CHE_LOCAL_CONF_DIR. As far as I understand it can be empty. And then mounts should include extra one with `"Destination": /mnt/che/conf""`. Please make ensure that it is mounted with 'Z' suffix when configuration contains it. If no, please try to add `requestInjection(extConfBindingProvider);` in DockerExtServerModule

2016-11-22 14:31 UTC, snjeza commented
The following are the mounted volumes:

```
 "Mounts": [
            {
                "Source": "/data/workspaces/wksp-8t9p",
                "Destination": "/projects",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/tmp/data/lib/linux_amd64/terminal",
                "Destination": "/mnt/che/terminal",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/tmp/data/lib/ws-agent.tar.gz",
                "Destination": "/mnt/che/ws-agent.tar.gz",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/conf/plugin-conf",
                "Destination": "/mnt/che/conf",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
```

2016-11-22 15:20 UTC, garagatyi commented
It is interesting. We debugged DockerExtConfBindingProvider usage and guice injected dependencies between 1st and 2nd calls of get method of this class. Sorry that we asked you to check more and more but we missed that Guice behavior with singleton classes.

2016-11-22 16:03 UTC, sleshchenko approved these changes

2016-11-24 12:12 UTC, garagatyi commented
ci-build

2016-12-15 13:05 UTC, vparfonov approved these changes

2016-12-15 13:06 UTC, merged