#3038 invoke content assist on trigger characters
eclipse/che pull request #3230
Opened 2016-12-01 10:31 UTC by evidolob

### What does this PR do?
 invoke content assist on trigger characters
### What issues does this PR fix or reference?
#3038

Signed-off-by: Evgen Vidolob <evidolob@codenvy.com>

2016-12-01 10:32 UTC, benoitf commented on plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/editor/codeassist/LanguageServerCodeAssistProcessor.java
> +        if(serverCapabilities.getCompletionProvider() !=null){
code formatting issue (spaces)

2016-12-01 10:33 UTC, benoitf commented on plugins/plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorInit.java
> +import org.eclipse.che.ide.api.editor.events.*;
we shouldn't use wildcard imports

2016-12-01 11:12 UTC, vparfonov commented on plugins/plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorInit.java
> +                if (editorPropertiesManager.getEditorProperties().get(EditorProperties.SHOW_CONTENT_ASSIST_AUTOMATICALLY.toString()).isBoolean().booleanValue()) {
Is possible NPE here?

2016-12-01 11:57 UTC, kaloyan-raev requested changes

2016-12-01 11:57 UTC, kaloyan-raev commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/editor/codeassist/CodeAssistProcessor.java
> +    char[] getTriggerCharacters();
Please consider trigger character sequences of more than one char. See https://github.com/Microsoft/language-server-protocol/issues/138 for details. This means the return type should be `String[]`.

2016-12-01 12:07 UTC, evidolob commented on ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/editor/codeassist/CodeAssistProcessor.java
> +    char[] getTriggerCharacters();
OK, I will update pull request with this

2016-12-01 15:58 UTC, kaloyan-raev approved these changes

2016-12-19 08:30 UTC, vparfonov approved these changes

2017-01-07 17:34 UTC, TylerJewell commented
@evidolob - please plan to merge asap.

2017-02-26 11:17 UTC, TylerJewell commented
@vparfonov - what is the merge plan?

2017-03-07 09:06 UTC, vparfonov commented
details https://github.com/eclipse/che/pull/4135

2017-03-07 09:06 UTC, closed without merging