[WIP] Replace manually publishing cascade operation instead of using EntityListeners
eclipse/che pull request #3342
Opened 2016-12-09 16:08 UTC by sleshchenko

### What does this PR do?
Replaces manually publishing cascade operation instead of using EntityListeners

### What issues does this PR fix or reference?

### Previous behavior
(Remove this section if not relevant)

### New behavior
(Explain the PR as it should appear in the release notes)

2016-12-13 15:17 UTC, akorneta approved these changes

2016-12-13 15:53 UTC, voievodin approved these changes

2016-12-14 16:47 UTC, voievodin requested changes
This approach won't propagate the original exception

2016-12-22 13:16 UTC, mshaposhnik commented on core/che-core-db/src/main/java/org/eclipse/che/core/db/cascade/CascadeContext.java
> +    private ApiException cause;
For me, REST-api oriented exception looks a bit strange here.

2016-12-22 13:44 UTC, mshaposhnik commented on wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/jpa/JpaFactoryDao.java
> +        manager.flush();
Is those changes are necessary if we didn't publish any events here?

2016-12-22 13:46 UTC, sleshchenko commented on core/che-core-db/src/main/java/org/eclipse/che/core/db/cascade/CascadeContext.java
> +    private ApiException cause;
The same as throwing REST-api oriented exception from Dao. But we do it. :) And we should rethrow original REST-api oriented exception from another Dao

2016-12-22 13:47 UTC, sleshchenko commented on wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/jpa/JpaFactoryDao.java
> +        manager.flush();
Yes, because this operation can be performed by listener. And then integrity exception will be catched in wrong place

2016-12-22 13:54 UTC, mshaposhnik commented on wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/jpa/JpaFactoryDao.java
> +        manager.flush();
I can hardly imagine the listener which will create factory in some case :)) But for purposes of uniformity it's ok.

2016-12-26 12:33 UTC, evoevodin commented on core/che-core-db/src/main/java/org/eclipse/che/core/db/cascade/CascadeEventSubscriber.java
> +     * or it can be wrapped in {@link SecurityException} instance.
`SecurityException` ?

2016-12-26 12:33 UTC, sleshchenko commented on core/che-core-db/src/main/java/org/eclipse/che/core/db/cascade/CascadeEventSubscriber.java
> +     * or it can be wrapped in {@link SecurityException} instance.
Oooops :smile:

2016-12-27 15:56 UTC, voievodin approved these changes

2016-12-27 16:12 UTC, akorneta approved these changes

2017-01-12 13:57 UTC, skabashnyuk approved these changes

2017-01-12 15:33 UTC, merged