CHE-3216: Fix kill terminal process and its children on closing terminal.
eclipse/che pull request #3395
Opened 2016-12-14 23:38 UTC by AndrienkoAleksandr

### What does this PR do?
Create new type websocket message to realise ability to kill terminal process and its child processes. 

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/3216

@evoevodin and @garagatyi review please.

Signed-off-by: Aleksandr Andrienko <aandrienko@codenvy.com>

2016-12-23 09:54 UTC, garagatyi requested changes
Looks good. Please address my comments.

2016-12-23 09:54 UTC, garagatyi commented on plugins/plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/terminal/TerminalPresenter.java
> +     * Sends 'kill' command on server side to stop terminal.
It actually closes terminal

2016-12-23 09:54 UTC, garagatyi commented on plugins/plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/terminal/TerminalPresenter.java
> +            jso.addField("type", "kill");
please rename to close

2016-12-23 09:54 UTC, garagatyi commented on exec-agent/src/term/server.go
> +		fmt.Println("Pty file closed.")
Please also log if closing failes

2016-12-23 09:54 UTC, garagatyi commented on exec-agent/src/term/server.go
> +			if msg.Type == "kill" {
please rename to close

2016-12-23 09:54 UTC, garagatyi commented on exec-agent/src/term/server.go
> +				wp.Stop(finalizer);
Please rename to close

2016-12-23 09:54 UTC, garagatyi commented on exec-agent/src/term/server.go
> +	closeFile(wp.PtyFile, finalizer)
Please comment this function well as it is not obvious and we will forget why it is implemented in such a way

2016-12-27 12:04 UTC, voievodin approved these changes

2016-12-28 07:38 UTC, garagatyi approved these changes

2017-01-11 12:56 UTC, AndrienkoAleksandr commented
ci-build

2017-01-11 15:21 UTC, merged