Added documentation.
eclipse/che pull request #3407
Opened 2016-12-15 21:43 UTC by JamesDrummond

### What does this PR do?
The markdown and configuration files are used by jekyll to generate static html. This static html can be used both in the eclipse che product with the already include tomcat server and on web hosting sites such as github.io .

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/3406

### Current generated website:  
http://45.33.14.150:84/docs/index.html

This can be move to che.github.io repo once it is created.

2016-12-15 22:35 UTC, bmicklea approved these changes

2016-12-16 14:56 UTC, benoitf requested changes

2016-12-16 14:56 UTC, benoitf commented on docs/_config.yml
> +repository: https://github.com/codenvy/codenvy
repository is invalid, it's che there

2016-12-16 14:56 UTC, benoitf commented on docs/_config.yml
> +#google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
please remove these comments

2016-12-16 14:56 UTC, benoitf commented on docs/_config.yml
> +name: Codenvy Docs
invalid name

2016-12-16 14:56 UTC, benoitf commented on docs/_config.yml
> +url: https://codenvy.com
invalid url

2016-12-16 14:56 UTC, benoitf commented on docs/_config.yml
> +  username: codenvyhq
invalid username : @eclipse_che

2016-12-16 14:56 UTC, benoitf commented on docs/_config.yml
> +      categories: [ "artik" ]
missing newline

2016-12-16 14:56 UTC, benoitf commented on docs/_data/artik.yml
> +- title: ARTIK IDE
artik shouldn't be in artik repository ?

2016-12-16 14:56 UTC, benoitf commented on docs/_data/artik.yml
> +  - artik-download-ide
missing newline

2016-12-16 14:56 UTC, benoitf commented on docs/_data/docs.yml
> +  - che-data-model-samples
missing newline

2016-12-16 14:56 UTC, benoitf commented on docs/_data/openshift.yml
> +  - openshift-user-guide
missing newline

2016-12-16 14:56 UTC, benoitf commented on docs/_docs/setup-alternatives/che-setupalt-docker-server.md
> +# To run the nightly version of Che, replace codenvy/che with
codenvy/che ? seems not ok

2016-12-16 14:56 UTC, benoitf commented on docs/_docs/setup-alternatives/che-setupalt-docker-server.md
> +# To run a specific tagged version of Che, replace codenvy/che with
codenvy/che ?

2016-12-16 14:56 UTC, benoitf commented on docs/dev/Dockerfile
> +# Copyright (c) 2012-2016 Codenvy, S.A.
what is the purpose of that dockerfile ?
now Dockerfile are in /dockerfiles folder

2016-12-16 14:56 UTC, benoitf commented on docs/dev/default.prf
> +# Arguments
what is this file ? 
there is no copyright

2016-12-16 14:56 UTC, benoitf commented on docs/dev/docker-compose.yml
> +    network_mode: "bridge"
missing newline
dockerfiles are in /dockerfiles folder in che

2016-12-16 14:56 UTC, benoitf commented on docs/dev/jekyll.sh
> +#!/bin/sh
what is this file ?

2016-12-16 14:56 UTC, benoitf commented on docs/pom.xml
> +     [2012] - [2016] Codenvy, S.A.
I think license is invalid there it should be EPL

2016-12-16 14:56 UTC, benoitf commented on docs/pom.xml
> +        <artifactId>onpremises-assembly-parent</artifactId>
the parent is invalid

2016-12-16 14:58 UTC, benoitf commented
```
docs/assets/fonts/FontAwesome.eot
docs/assets/fonts/FontAwesome.svg
docs/assets/fonts/FontAwesome.ttf
docs/assets/fonts/FontAwesome.woff
```

what is the version of FontAwesome ? is it one for which we have CQs ?

2016-12-16 19:30 UTC, JamesDrummond commented on docs/_config.yml
> +#google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
removed

2016-12-16 19:30 UTC, JamesDrummond commented on docs/_config.yml
> +repository: https://github.com/codenvy/codenvy
updated

2016-12-16 19:30 UTC, JamesDrummond commented on docs/_config.yml
> +name: Codenvy Docs
updated

2016-12-16 19:30 UTC, JamesDrummond commented on docs/_config.yml
> +url: https://codenvy.com
Updated

2016-12-16 19:31 UTC, JamesDrummond commented on docs/_config.yml
> +  username: codenvyhq
Updated

2016-12-16 19:31 UTC, JamesDrummond commented on docs/_data/docs.yml
> +  - che-data-model-samples
Added.

2016-12-16 19:31 UTC, JamesDrummond commented on docs/_data/openshift.yml
> +  - openshift-user-guide
Added.

2016-12-16 19:31 UTC, JamesDrummond commented on docs/_docs/setup-alternatives/che-setupalt-docker-server.md
> +# To run the nightly version of Che, replace codenvy/che with
Replaced

2016-12-16 19:31 UTC, JamesDrummond commented on docs/_docs/setup-alternatives/che-setupalt-docker-server.md
> +# To run a specific tagged version of Che, replace codenvy/che with
Replaced.

2016-12-16 19:39 UTC, JamesDrummond commented
@benoitf Please see changes in new commit.

2016-12-16 19:45 UTC, JamesDrummond commented
Review my repo if viewing PR is difficult due to the number of files. Folder /docs content is all new. https://github.com/JamesDrummond/che/tree/jekyll-docs/docs versus master.

2016-12-16 21:23 UTC, TylerJewell approved these changes

2016-12-16 21:52 UTC, merged

2016-12-16 22:22 UTC, benoitf commented
https://github.com/eclipse/che/blob/master/docs/assembly/build_war.yml has reference to codenvy
Also pr was merged while I was still requesting changes