CHE-55: Adding kubernetes-client / kubernetes-model dependencies. Sorting pom.xml
eclipse/che pull request #3454
Opened 2016-12-20 22:27 UTC by ibuziuk

2016-12-21 12:29 UTC, ibuziuk commented
@l0rd could you please apply ?

2016-12-21 12:37 UTC, skabashnyuk requested changes
Need crosslink to https://github.com/eclipse/che-dependencies/blob/master/pom.xml and CQs

2016-12-21 12:37 UTC, skabashnyuk commented on plugins/plugin-docker/che-plugin-docker-client/pom.xml
> +            <version>1.4.26</version>
move this variable to https://github.com/eclipse/che-dependencies/blob/master/pom.xml

2016-12-21 12:37 UTC, skabashnyuk commented on plugins/plugin-docker/che-plugin-docker-client/pom.xml
> +            <artifactId>kubernetes-model</artifactId>
https://github.com/eclipse/che-dependencies/blob/master/pom.xml

2016-12-21 13:31 UTC, ibuziuk commented
@skabashnyuk ok, lets probably wait for https://github.com/eclipse/che-dependencies/pull/23 been merged

2016-12-23 11:28 UTC, ibuziuk commented
not relevant any more. Closing

2016-12-23 11:28 UTC, closed without merging