Do not fetch runtimes when getting list of all workspaces
eclipse/che pull request #3557
Opened 2016-12-28 12:05 UTC by mkuznyetsov

### What does this PR do?
Removes getting workspace runtimes info on 'get all workspaces' service

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/3082

2016-12-28 12:42 UTC, garagatyi approved these changes

2016-12-28 12:47 UTC, voievodin requested changes
Returned workspaces must still contain correct status

2016-12-30 09:58 UTC, garagatyi requested changes

2016-12-30 09:58 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
> +    public WorkspaceStatus getStatus(String workspaceId) {
Please add tests

2017-01-06 07:58 UTC, mkuznyetsov commented
Now returns workspace status

2017-01-06 08:32 UTC, evoevodin commented on dashboard/src/app/projects/create-project/create-project.controller.ts
> +    if (workspace.status === 'RUNNING') {
```javascript
if (workspace.status === 'RUNNING')
```
is not the same to 
```javascript
if (workspace.runtime)
```
it looks like 
```javascript
if (workspace.status !== 'STOPPED')
```
is the correct option here

2017-01-06 08:33 UTC, evoevodin commented
@ashumilova please review client-side changes

2017-01-06 10:40 UTC, ashumilova commented on dashboard/src/app/projects/create-project/create-project.controller.ts
> +    if (workspace.status === 'RUNNING') {
'RUNNING' is fine here, cause wait for this status to start importing projects

2017-01-06 10:54 UTC, garagatyi approved these changes

2017-01-06 11:27 UTC, ashumilova approved these changes

2017-01-06 12:03 UTC, voievodin approved these changes

2017-01-10 15:05 UTC, mkuznyetsov commented
same logic done for WorkspaceService#getByNamespace()

2017-01-10 15:34 UTC, merged