CHE-3720: Decouple different agents on different maven modules
eclipse/che pull request #3830
Opened 2017-01-20 13:10 UTC by tolusha

### What does this PR do?
Adds module per agent

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/3720

### Previous behavior
All agents are located in the same folder

### Tests written?
Yes

2017-01-20 14:15 UTC, skabashnyuk commented
Can you describe new folders structure?

2017-01-20 14:27 UTC, tolusha commented
```
├── che-core-api-agent
├── che-core-api-agent-shared
├── exec
├── ls-csharp
├── ls-json
├── ls-php
├── ls-python
├── ls-typescript
├── unison
├── ssh
└── pom.xml
```

An instance of the ssh agent folder structure:
```
ssh
├── pom.xml
├── src
   └── main
       ├── java
       │   └── org
       │       └── eclipse
       │           └── che
       │               └── api
       │                   └── agent
       │                       ├── SshAgent.java
       │                       ├── SshAgentLauncher.java
       │                       └── SshAgentModule.java
       └── resources
           ├── org.eclipse.che.ssh.json
           └── org.eclipse.che.ssh.script.sh
```

2017-01-20 14:31 UTC, tolusha commented
also:
```
wsagent
...
├── wsagent
│   ├── pom.xml
│   └── src
│       ├── main
│       │   ├── java
│       │   │   └── org
│       │   │       └── eclipse
│       │   │           └── che
│       │   │               └── api
│       │   │                   └── agent
│       │   │                       ├── WsAgent.java
│       │   │                       ├── WsAgentLauncher.java
│       │   │                       └── WsAgentModule.java
│       │   └── resources
│       │       ├── org.eclipse.che.ws-agent.json
│       │       └── org.eclipse.che.ws-agent.script.sh
│       └── test
│           └── java
│               └── org
│                   └── eclipse
│                       └── che
│                           └── api
│                               └── agent
│                                   └── WsAgentLauncherTest.java
...
```

2017-01-20 18:48 UTC, TylerJewell commented
That documentation helps.  I think @skabashnyuk - at the same time that this is merged, the wiki needs to be updated with an explanation of how this modifies the development workflow.  We have sections at the end of that wiki that explain the repository layout, and they need to be updated with this information.

2017-01-23 13:01 UTC, tolusha commented
@TylerJewell 
Does it mean the structure it is ok for you?

2017-01-23 15:25 UTC, TylerJewell commented
@tolusha - I think the code structure of `/wsagent` folder is really for @gazarenkov to comment on.  The `/agents` folder is ok for me.

2017-01-24 07:41 UTC, garagatyi requested changes

2017-01-24 07:41 UTC, garagatyi commented on agents/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/impl/AgentRegistryImpl.java
> +        agents.forEach(a -> this.agents.put(a.getId(), a));
Here it is possible that someone declared 2 equal agents. 
If all of them have equals and hashcode then multibinder will throw an error.
If multibinder is declared anywhere with support of duplicates then it won't throw exception.
If equals and hashcode is not overridden or overridden in a different ways then here duplicate agent will override previous one.

2017-01-24 07:55 UTC, garagatyi commented on agents/ls-csharp/src/main/java/org/eclipse/che/api/agent/LSCSharpAgent.java
> +public class LSCSharpAgent implements Agent {
Looks like all the agents are very similar. Please consider creation of abstract base class for them.

2017-01-24 08:04 UTC, garagatyi approved these changes
Looks good. Great job!
Please consider improvements I commented.

2017-01-25 07:54 UTC, skabashnyuk commented
ok

2017-01-25 18:42 UTC, merged