[cli] Improve UX of graceful shutdown message
eclipse/che pull request #4064
Opened 2017-02-08 17:48 UTC by benoitf

### What does this PR do?
Improve UX of graceful shutdown message
- base scripts : catch error code of action lifecycle and return it
- cha-lib : return error code based on http error code
- display better message when auth is required
- skip graceful mode when repo is mounted

### What issues does this PR fix or reference?
https://github.com/codenvy/codenvy/issues/1682

#### Changelog
Improve UX of graceful shutdown message

#### Release Notes
Improve UX of graceful shutdown message

#### Docs PR
Improvement on UX, command is the same

Change-Id: I1ad021426444b5b4d880df518512e53ef4828336
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>

2017-02-08 18:01 UTC, bmicklea approved these changes
tweaked release note entry

2017-02-09 08:51 UTC, garagatyi approved these changes
I'm not an expert in neither modern CLI code nor TS code we use, so can't do real technical review.
As for what I understand it looks good.

2017-02-09 13:12 UTC, benoitf commented
@garagatyi I mentioned you if you wanted to check it was now working as you're expecting based the issue you reported.

2017-02-11 17:02 UTC, TylerJewell requested changes

2017-02-11 17:04 UTC, benoitf commented on dockerfiles/base/scripts/base/commands/cmd_stop.sh
> +    warning "Development mode [skip graceful stop]"
In the issue ppl were asking for local repo mode
I'm also ok for local_assembly. I will add

2017-02-11 17:06 UTC, benoitf commented on dockerfiles/base/scripts/base/commands/cmd_stop.sh
> +        error "Authentication failed on the system. Please provide --user and -password values or user --skip:graceful to bypass graceful stop."
@TylerJewell in the issue it was requested to provide the argument for authentication (--user and --password) when auth is required

2017-02-11 17:06 UTC, benoitf commented on dockerfiles/base/scripts/base/commands/cmd_stop.sh
> +        error "We encountered an error -- see $CHE_HOST_CONFIG/cli.log. Graceful stop can be skipped with --skip:graceful"
shouldn't we add the hint on the fact that graceful stop can be skipped ?

2017-02-11 17:10 UTC, TylerJewell commented on dockerfiles/base/scripts/base/commands/cmd_stop.sh
> +        error "We encountered an error -- see $CHE_HOST_CONFIG/cli.log. Graceful stop can be skipped with --skip:graceful"
If you do it have it as (hint: `--skip:graceful` does not wait for workspace stop)

2017-02-11 17:10 UTC, benoitf commented on dockerfiles/base/scripts/base/commands/cmd_stop.sh
> +        error "We encountered an error -- see $CHE_HOST_CONFIG/cli.log. Graceful stop can be skipped with --skip:graceful"
ok

2017-02-13 11:32 UTC, benoitf commented
@TylerJewell updated

2017-02-13 16:16 UTC, TylerJewell approved these changes

2017-02-13 16:19 UTC, merged