Add Eclipse KeyScheme as Extension
eclipse/che pull request #4185
Opened 2017-02-20 13:37 UTC by akervern

Signed-off-by: Arnaud Kervern <akervern@nuxeo.com>

### What does this PR do?
It adds an Eclipse based key schema as a new IDE extension.
And expose actions ids as contants to let them accessible from another module.

But not sure if you prefer to have this Eclipse schema par default; or the previous one. The originating code set Eclipse as the default one, but it was empty; so all key bindings were the global ones.

#### Changelog
- New Eclipse based Key Schema

#### Release Notes
- New Eclipse based Key Schema

2017-02-20 14:20 UTC, TylerJewell commented
Thanks for making this contribution.  @JamesDrummond @akervern - the release notes will need to be written as if they were end user documentation.  So probably some questions about how to activate / deactivate this schema.  And we should probably also create a list of all of the bindings and their key strokes generated as well.  

I think we would largely have the release notes + documentation PR be identical in this regard.  I don't think we have ever generated key-binding or schema related documentation, so this might be the first instance of that.  It shouldn't be a lot of docs, but enough for end users to figure out their way.

2017-02-20 15:37 UTC, JamesDrummond requested changes
Would it make sense to map the keybinding as well? Maybe `keyBinding.getGlobal().addKey(new KeyBuilder().action().alt().charCode('n').build(), NAVIGATE_TO_FILE);` => `keyBinding.getGlobal().addKey(new KeyBuilder().action().alt().charCode(dictionaryObj.get(NAVIGATE_TO_FILE)).build(), NAVIGATE_TO_FILE);`

2017-02-21 15:38 UTC, akervern commented
Good idea, but i'm not sure to get exactly what you want. For me, an interesting improvement could be to have a map of keyBinding per action and registrating them at once using a lambda, it could make the code more readable and could be the first step for allowing import the key binding from a definition file outside of the compiled code to ease modification / contribution.

Can you explain why you would like to extract chars key without taking into account the modifiers; and I think it can be confusing as `CharCodeWithModifiers` handles uppercase chars the same way as a lowercase char + `shift` modifier.

2017-02-22 14:05 UTC, JamesDrummond commented
@akervern Yes I didn't take into account modifiers. I like your proposed idea. Are you able to implement this? Would be a great step forward.

2017-03-01 20:40 UTC, akervern commented
Hi, is this commit enough for you? Or do you need something more?

2017-03-07 20:29 UTC, vparfonov commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java
> +
Can you move this declarations to the che/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/action/IdeActions.java ?

2017-03-07 21:39 UTC, skabashnyuk commented on plugins/plugin-keybinding-eclipse/plugin-keybinding-eclipse-ide/pom.xml
> +                            <skip>true</skip>
What for?

2017-03-07 21:39 UTC, skabashnyuk commented on plugins/plugin-keybinding-eclipse/plugin-keybinding-eclipse-ide/pom.xml
> +                <artifactId>maven-surefire-plugin</artifactId>
What for?

2017-03-07 21:39 UTC, skabashnyuk commented on plugins/plugin-keybinding-eclipse/plugin-keybinding-eclipse-ide/src/main/resources/org/eclipse/che/plugin/keybinding/eclipse/EclipseKeyBinding.gwt.xml
> +</module>
new line

2017-03-07 21:55 UTC, akervern commented
@skabashnyuk You're right; copied/pasted from another plugin and useless.

2017-03-07 22:56 UTC, akervern commented on plugins/plugin-keybinding-eclipse/plugin-keybinding-eclipse-ide/pom.xml
> +                            <skip>true</skip>
In fact, after tries; not sure why and I can't investigate. 

But `dependency` plugin looks to not be able to resolve those dependencies as `used` and throw an error.
Of course, artifact won't compile if I remove them. So, there is certainly something wrong somewhere as several extensions are using this flag.

2017-03-09 15:19 UTC, vparfonov approved these changes

2017-03-09 15:54 UTC, JamesDrummond approved these changes

2017-03-10 16:14 UTC, vparfonov commented
@akervern Fixed conflict and merged here https://github.com/eclipse/che/pull/4394

2017-03-10 16:14 UTC, closed without merging

2017-03-10 16:26 UTC, akervern commented
Cool Thanks!