[WIP] Implement createExec() and startExec() in OpenShiftConnector
eclipse/che pull request #4264
Opened 2017-02-28 15:25 UTC by amisevsk

### What does this PR do?
Adds implementations of createExec and startExec. 

This is a work in progress, and not ready to merge. Before a merge can occur, CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12789 has to be completed and included in che-dependencies.

2017-02-28 15:25 UTC, amisevsk commented
@l0rd Please test this out and see if it works for you. I'll work on getting the code cleaned up.

2017-02-28 16:40 UTC, l0rd commented
@amisevsk I'm sorry but you need to rebase your commits

2017-02-28 17:36 UTC, amisevsk commented
@l0rd Ha, sorry. I didn't notice that commit had been merged :)

2017-03-01 07:43 UTC, skabashnyuk requested changes

2017-03-01 07:43 UTC, skabashnyuk commented on plugins/plugin-docker/che-plugin-openshift-client/pom.xml
> +            <version>2.1.1</version>
Are you sure this is approved version of client?
take a look https://github.com/eclipse/che-dependencies/blob/master/pom.xml#L53-L54

2017-03-01 07:43 UTC, skabashnyuk commented on plugins/plugin-docker/che-plugin-openshift-client/pom.xml
> +            <version>2.1.1</version>
Are you sure this is approved version of client?
take a look https://github.com/eclipse/che-dependencies/blob/master/pom.xml#L53-L54

2017-03-01 07:43 UTC, skabashnyuk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java
> +            e.printStackTrace();
LOG.error?

2017-03-01 07:43 UTC, skabashnyuk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/kubernetes/KubernetesOutputAdapter.java
> + *
javadoc

2017-03-01 08:51 UTC, l0rd commented on plugins/plugin-docker/che-plugin-openshift-client/pom.xml
> +            <version>2.1.1</version>
@skabashnyuk are you sure you have read the description of this PR?

2017-03-01 09:14 UTC, skabashnyuk commented on plugins/plugin-docker/che-plugin-openshift-client/pom.xml
> +            <version>2.1.1</version>
oops. sorry :)

2017-03-03 19:16 UTC, amisevsk commented
@skabashnyuk Sorry for the confusion, this was meant to be a WIP PR to get some extra eyes and opinions. 

We've since decided to move OpenShift integration to the openshift-connector branch, to avoid interfering with core Che development. I'm closing this PR and would like to move the discussion over to #4305.

2017-03-03 19:16 UTC, closed without merging