Implement getSystemInfo method in OpenShiftConnector
eclipse/che pull request #4424
Opened 2017-03-14 17:46 UTC by snjeza

What does this PR do?

Implements the getSystemInfo method in OpenShiftConnector.

The PR implements getSystemInfo partially.
The method requires the cluster-admin role which has already been added for the che service account.

This method isn't called anywhere in che. In order to test it, you need to debug che and call the method manually.

What issues does this PR fix or reference?

Che doesn't start on OpenShift if the Docker socket is not mounted.

2017-03-15 19:42 UTC, amisevsk requested changes
Thanks @snjeza! Just a few comments

2017-03-15 19:42 UTC, amisevsk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java
> +                .withLabel(OPENSHIFT_DEPLOYMENT_CONFIG_LABEL, OPENSHIFT_DEPLOYMENT_CONFIG_VALUE).list();
Is this step necessary? I feel like explicitly checking for `deploymentconfig=che` is prone to error if the deploy script is changed. Is it sufficient to just do `openShiftClient.pods().inNamespace(...).list()`?

2017-03-15 19:42 UTC, amisevsk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java
> +                containers += p.getSpec().getContainers().size();
In our current implementation, we are using 1 container/pod, so `containers` should just be equal to the number of pods in the eclipse-che namespace.

2017-03-16 16:59 UTC, amisevsk requested changes
Sorry to bring it up again, a few more things.

2017-03-16 16:59 UTC, amisevsk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java
> +    public SystemInfo getSystemInfo() throws IOException {
I think we should move the method up, to come right after `startExec()`. That way, the code is easier to read and all public methods are grouped together.

2017-03-16 16:59 UTC, amisevsk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java
> +            containers += pods.size();
These three lines can be merged into just one:

``` java
int containers = openShiftClient.pods().inNamespace(this.openShiftCheProjectName).list().getItems().size();
```

2017-03-16 16:59 UTC, amisevsk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java
> +                labels[i[0]++] =  k + "=" + v
WDYT about using streams here? 

```java
String[] labels = node.getMetadata()
                      .getLabels()
                      .entrySet().stream().map(e -> String.format("%s=%s", e.getKey(), e.getValue()))
                      .toArray(String[]::new);
```

2017-03-16 21:28 UTC, snjeza commented
@amisevsk 
I have updated the PR.

2017-03-17 01:05 UTC, amisevsk approved these changes

2017-04-17 14:46 UTC, TylerJewell commented
Added `target/branch` label to this PR.  Going forward, all non-master branch PRs will need this label.  Please apply going forward.

2017-09-13 14:43 UTC, benoitf commented
work is done by https://github.com/eclipse/che/pull/6218

2017-09-13 14:43 UTC, closed without merging