Spring Boot stack
eclipse/che pull request #4426
Opened 2017-03-15 09:28 UTC by gytis

### What does this PR do?
Adds the Spring Boot stack to the default Che assembly.

### What issues does this PR fix or reference?

#### Changelog
Adds the Spring Boot stack to the default Che assembly.

#### Release Notes
We've added a new stack for the Spring Boot framework. You can now build Spring Boot applications by simply creating a workspace from the Spring Boot stack - no configuration necessary!

#### Docs PR

2017-03-15 09:28 UTC, gytis commented
Recipe pull request: https://github.com/eclipse/che-dockerfiles/pull/76

2017-03-15 12:56 UTC, TylerJewell approved these changes

2017-03-16 08:51 UTC, l0rd approved these changes

2017-03-16 09:15 UTC, benoitf commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +        "version": "1.8.0_45"
JDK is quite old there ?

2017-03-16 09:43 UTC, gytis commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +        "version": "1.8.0_45"
I've used the same version as in other stacks in that file: https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L89

2017-03-16 09:44 UTC, benoitf commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +        "version": "1.8.0_45"
I would drop the _45 as from the docker recipe we don't know the version

2017-03-16 09:46 UTC, benoitf requested changes

2017-03-16 09:46 UTC, benoitf commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +        "version": "3.2.2"
You're installing maven 3.3
https://github.com/eclipse/che-dockerfiles/blob/2fe67f2254109dd2ed649042443998b2799af9e1/recipes/centos_spring_boot/Dockerfile#L18

2017-03-16 09:47 UTC, benoitf commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +      "name": "type-java.svg",
question: logo is java but shouldn't it be spring boot logo ?

2017-03-20 11:14 UTC, gytis commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +      "name": "type-java.svg",
Do you use a designer for these images or should I find one online?

2017-03-20 23:05 UTC, slemeur commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +      "name": "type-java.svg",
@gytis I'm happy to help you on that - no problem.
Could you tell me which icon do you wan to use?
- The spring leaf: https://en.wikipedia.org/wiki/File:Pivotal_Java_Spring_Logo.png
- The spring "power" button: http://stormpath.com/wp-content/uploads/2016/05/spring-boot-logo.jpg

Also, if you can point me to an SVG file, that would be ideal.

2017-03-21 10:20 UTC, gytis commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +      "name": "type-java.svg",
Since it's a Spring Boot stack, "power" button is more appropriate. Either green or black (like here https://spring.io/projects) up to you.

2017-03-27 09:52 UTC, slemeur commented
Added dedicated spring-boot icon

2017-03-27 11:03 UTC, ashumilova approved these changes

2017-03-27 11:41 UTC, benoitf commented on ide/che-core-ide-stacks/src/main/resources/images/type-spring-boot.svg
> +</svg>
there is a missing newline

2017-03-27 12:47 UTC, benoitf approved these changes

2017-03-27 12:48 UTC, merged