CHE-158 Adding TLS support for Workspace routes
eclipse/che pull request #4660
Opened 2017-03-31 13:06 UTC by ibuziuk

### What does this PR do?
Adding properties for possibility enabling secure external urls & OpenShift routes

### What issues does this PR fix or reference?
https://issues.jboss.org/browse/CHE-158

2017-03-31 15:54 UTC, ibuziuk commented
[test]

2017-04-03 05:05 UTC, amisevsk requested changes
Looks good!

Do you have instructions for deploying these changes on OpenShift? I tried setting the properties to true, but I just get "workspace is not responding" from the IDE.

2017-04-03 09:01 UTC, ibuziuk commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +# Create secure route against HTTPS
@amisevsk agree

2017-04-03 09:02 UTC, ibuziuk commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/LocalDockerSinglePortServerEvaluationStrategy.java
> +                                                         @Nullable @Named("che.docker.server_evaluation_strategy.secure.external.urls") Boolean secureExternalUrl) {
@amisevsk yeah, I will fix so that no NPE would be thrown ;-)

2017-04-03 09:09 UTC, ibuziuk commented
@amisevsk I guess you have `Error in connection establishment: net::ERR_INSECURE_RESPONSE` in the browser console - the default certificate is not trusted, so you first need to allow browser to use it. 
I have not tried yet but I think starting Chrome / Chromium with `--ignore-certificate-errors` should do the trick for minishift

2017-04-03 13:26 UTC, ibuziuk commented
@amisevsk PR has been updated. Running `google-chrome --ignore-certificate-errors` should work locally with minishift

2017-04-03 14:52 UTC, ibuziuk commented
@amisevsk @l0rd After rebase I have problems with starting Che - https://pastebin.com/bLjp1xLw
Do you have an idea what is wrong with the setup ?

2017-04-03 15:11 UTC, ibuziuk commented
hmmm.. having the same problem on openshift-connector branch without this changes :/

2017-04-03 15:19 UTC, l0rd commented
Try rebuilding che-dependencies

Il 03 apr 2017 17:11, "Ilya Buziuk" <notifications@github.com> ha scritto:

> hmmm.. having the same problem on openshift-connector branch without this
> changes :/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eclipse/che/pull/4660#issuecomment-291173242>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAlC7-OlGRnrnpuVs2MNZii-DxXdSNUKks5rsQwygaJpZM4MvpKU>
> .
>

2017-04-03 15:20 UTC, ibuziuk commented
@l0rd but aren't che-dependencies build on ./build.sh step?

2017-04-03 15:20 UTC, amisevsk commented
@ibuziuk had this issue before, I think it may be related to your che-dependencies. When it occurred for me, I think it was due to a wrong version of kubernetes-client or something being pulled in. It was fixed for me after doing a full rebuild (starting with che-dependencies). 

It may also be related to PR https://github.com/eclipse/che-dependencies/pull/38, but those changes did not cause issues for me.

2017-04-03 15:25 UTC, ibuziuk commented
ok, thanks - I will try rebuilding the whole thing starting from "che-dependencies"

2017-04-03 16:04 UTC, ibuziuk commented
@l0rd @amisevsk still having this issue after rebuilding che-dependencies &  che (both from openshift-connector) - will try to roll back to the previous client verion

2017-04-03 16:20 UTC, ibuziuk commented
@l0rd @amisevsk only rolling back to 2.1.1 of the K8S client helped to start dashboard...

2017-04-04 07:30 UTC, ibuziuk commented
@l0rd @amisevsk I have updated PR description with steps to verification

2017-04-04 14:15 UTC, amisevsk approved these changes

2017-04-04 16:51 UTC, l0rd commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +# Create secure route against HTTPS
@ibuziuk shouldn't we use just one property? I think that having 2 properties that actually mean the same thing (i.e. enable ssl) doesn't makes sense.

2017-04-04 17:02 UTC, ibuziuk commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +# Create secure route against HTTPS
@l0rd but than there will be dependency between evaluation strategy and openshift. Maybe having two properties make more sense for the sake of decoupling ?

2017-04-04 17:03 UTC, l0rd commented
@ibuziuk that's a great PR. I've added a comment about the properties but I don't know if that makes sense. And even if my comment makes sense we can address that in a separate PR. 

But what I think we should do when merging this PR is updating fabric8-online template and rh-che create-all.sh adding the new properties (and on fabric8-online https should be activated by default).

2017-04-04 18:38 UTC, l0rd approved these changes

2017-04-04 19:05 UTC, ibuziuk commented
@l0rd thanks for review! agree about template updates, one thing that I do not really know how to do is how exposing route against https for che-server should be done in create-all.sh - https://github.com/redhat-developer/rh-che/blob/master/scripts/create-all.sh#L109

I only know how to enable https for che-server manually

2017-04-04 20:11 UTC, merged