Add CentOS based nodejs4 stack to default assembly
eclipse/che pull request #4788
Opened 2017-04-12 10:12 UTC by dharmit

Signed-off-by: Dharmit Shah <dshah@redhat.com>

### What does this PR do?
Add NodeJS stack based on CentOS to the default assembly

#### Changelog

Add CentOS based nodejs4 stack to default assembly

#### Release Notes

Add CentOS based nodejs4 stack to default assembly

#### Docs PR

cc @l0rd

2017-04-13 17:40 UTC, l0rd requested changes

2017-04-13 17:40 UTC, l0rd commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +          "location": "dharmit/centos-nodejs",
Don't you want to use registry.centos registry here?

2017-04-17 03:17 UTC, dharmit commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +          "location": "dharmit/centos-nodejs",
@l0rd modified.

2017-04-18 23:58 UTC, l0rd requested changes
@dharmit thanks for your update. We have just figured out that there might be an issue with IDs containing spaces. Can you address that too? Thanks for your patience.

2017-04-18 23:58 UTC, l0rd commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +  "id": "CentOS nodejs",
All stacks, except centos nodejs and wildfly swarm have lowercase IDs without spaces. Can you please change the IDs into:
- nodejs4
- wildfly-swarm

2017-04-19 07:50 UTC, dharmit commented
@l0rd thanks for pointing that out. I updated the PR. Let me know if it looks good or needs further modification.

2017-04-20 09:58 UTC, l0rd approved these changes

2017-04-20 10:00 UTC, l0rd commented
Thanks @dharmit. I'm ok with the current state of this PR. @benoitf do you think we can merge this?

2017-04-20 15:11 UTC, benoitf approved these changes
@l0rd ok for me. Need a PM for release notes (added)

2017-06-16 15:51 UTC, slemeur approved these changes

2017-06-16 15:52 UTC, merged