Add Alpine support to ls-php
eclipse/che pull request #4946
Opened 2017-04-27 23:38 UTC by davidwindell

### What does this PR do?
Add's Alpine support to ls-php (the same as other agents)

2017-04-28 07:39 UTC, benoitf approved these changes

2017-04-28 07:39 UTC, ghost approved these changes

2017-04-28 07:45 UTC, benoitf commented
@davidwindell could you check the CLA /Signed-Off of the commit message so that the IP validation check become green ?
https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=5902f1a36c9d3

2017-04-28 07:45 UTC, benoitf requested changes
CLA needs to be valid

2017-04-28 09:59 UTC, davidwindell commented
@benoitf thanks, CLA signed. Any chance of tagging #4931 to 5.10.0 as well?

2017-04-28 11:59 UTC, benoitf approved these changes

2017-04-28 12:09 UTC, tolusha approved these changes

2017-06-26 10:30 UTC, slemeur approved these changes

2017-06-26 10:31 UTC, merged