Add Alpine support to ls-json
eclipse/che pull request #4947
Opened 2017-04-27 23:40 UTC by davidwindell

### What does this PR do?
Add's Alpine support to ls-json (the same as other agents)

2017-04-28 07:37 UTC, benoitf approved these changes

2017-04-28 07:39 UTC, ghost approved these changes

2017-04-28 07:41 UTC, tolusha requested changes

2017-04-28 07:41 UTC, tolusha commented on agents/ls-json/src/main/resources/org.eclipse.che.ls.json.script.sh
> +elif echo ${LINUX_TYPE} | grep -qi "alpine"; then
What about installing nodejs dependencies?
Are they required for alpine?

2017-04-28 07:46 UTC, benoitf requested changes
CLA is required or Signed-Off header needs to be added https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=5902f17391d65 for this PR

2017-04-28 10:10 UTC, davidwindell commented on agents/ls-json/src/main/resources/org.eclipse.che.ls.json.script.sh
> +elif echo ${LINUX_TYPE} | grep -qi "alpine"; then
:+1: done

2017-04-28 12:02 UTC, benoitf approved these changes

2017-04-28 12:08 UTC, tolusha approved these changes

2017-06-26 10:28 UTC, slemeur approved these changes

2017-06-26 10:29 UTC, merged