Revert WorkspaceFilesCleaner binding
eclipse/che pull request #5025
Opened 2017-05-09 11:12 UTC by l0rd

### What does this PR do?

Binds `WorkspaceFilesCleaner` to `LocalWorkspaceFilesCleaner` instead of `OpenShiftWorkspaceFilesCleaner.class` (the same as `master` branch).
We are reverting what was done in f3a9123be9f3e963635392a70cd4e01628913633 since that has been superseded by https://github.com/redhat-developer/rh-che/pull/57

2017-05-09 13:16 UTC, sunix commented
Can you amend the description of the commit with hash of the changeset it reverts ?

2017-05-09 13:17 UTC, sunix requested changes
Can you amend the description of the commit with hash of the changeset it reverts ?

2017-05-09 15:16 UTC, l0rd commented
@sunix done

2017-05-09 15:18 UTC, sunix approved these changes

2017-05-10 01:08 UTC, amisevsk approved these changes
Thanks Mario

2017-05-10 09:53 UTC, merged