[WIP] Refine terminal related UI
eclipse/che pull request #5070
Opened 2017-05-13 15:41 UTC by vzhukovskii

### What does this PR do?
This changes proposal provides several improvements related to the terminal related UI and refactoring. 

According to the _process tree_ there were made an improvement related to the displaying nodes, so the tree now looks like this:
![eclipse che - wksp-qq1f 2017-05-13 16-33-21](https://cloud.githubusercontent.com/assets/1968177/26026689/c1ba6ff4-3808-11e7-8501-53f6969cea76.png)

Besides UI, there were made decoupling of tree renderer into standalone strategies that are responsible for rendering own type of specific node. 

Signed-off-by: Vladyslav Zhukovskii <vzhukovskii@codenvy.com>

### What issues does this PR fix or reference?

#### Changelog
Refine terminal related UI

#### Release Notes
Refine terminal related UI

#### Docs PR
...

2017-05-15 09:15 UTC, AndrienkoAleksandr commented
Split renders logic by nodes it's a good idea. But in the description you wrote "Refine terminal related ui." But scope your changes covers process, ssh, root, machine, terminal nodes. You need apply more commons description.

2017-05-15 09:16 UTC, AndrienkoAleksandr requested changes

2017-05-15 09:16 UTC, AndrienkoAleksandr commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/MachineNodeRenderStrategy.java
> +            SpanElement newTerminalButton = Elements.createSpanElement(resources.getCss().newTerminalButton());
I think, we should create separate method for creating new terminal element "createNewTerminalElement" and use it here.

2017-05-15 09:16 UTC, AndrienkoAleksandr commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/MachineNodeRenderStrategy.java
> +            SpanElement sshButton = Elements.createSpanElement(resources.getCss().sshButton());
I think, we should create separate method for creating new ssh element "createNewSshElement" and use it here.

2017-05-15 09:16 UTC, AndrienkoAleksandr commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/ProcessTreeNode.java
> +        TERMINAL_NODE("terminal");
Where is "ssh" node?

2017-05-15 09:16 UTC, AndrienkoAleksandr commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/ProcessesGinModule.java
> +                    .to(TerminalNodeRenderStrategy.class);
Where is SSH node injection?

2017-05-15 09:19 UTC, vzhukovskii commented
@AndrienkoAleksandr as you can see, this is **_work in progress_** pull request. Full changes will be provided later.

2017-05-15 09:31 UTC, vzhukovskii commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/ProcessTreeNode.java
> +        TERMINAL_NODE("terminal");
Its a `COMMAND_NODE("command")`.

2017-05-15 09:32 UTC, vzhukovskii commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/ProcessesGinModule.java
> +                    .to(TerminalNodeRenderStrategy.class);
There is no injection for SSN node, because there is no ssh node.

2017-05-15 09:48 UTC, vzhukovskii commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/MachineNodeRenderStrategy.java
> + * @since 5.10.0
Thx, fixed

2017-05-15 11:21 UTC, AndrienkoAleksandr commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/ProcessTreeNode.java
> +        TERMINAL_NODE("terminal");
Yes, definitely you are right.

2017-05-15 11:21 UTC, AndrienkoAleksandr commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/processes/ProcessesGinModule.java
> +                    .to(TerminalNodeRenderStrategy.class);
Yes, definitely you are right.

2017-05-17 08:12 UTC, ashumilova commented
can you please attach selenium tests results

2017-05-17 08:27 UTC, AndrienkoAleksandr approved these changes

2017-05-18 08:30 UTC, vzhukovskii commented
@ashumilova sure
![a5-selenium-tests 9 test results jenkins 2017-05-18 11-29-45](https://cloud.githubusercontent.com/assets/1968177/26193257/6562c5fe-3bbd-11e7-92ff-ffbd855c8932.png)

2017-05-18 13:13 UTC, vzhukovskii commented
Locators in qa related tests will be updated after merge this PR.

2017-05-18 13:14 UTC, ashumilova approved these changes

2017-05-18 15:07 UTC, merged