CHE-220: Improving 'removeContainer' API. Refactoring
eclipse/che pull request #5157
Opened 2017-05-22 14:20 UTC by ibuziuk

### What does this PR do?
Enhance OpenShift resource deletion for workspaces (scaling deployment down before removing resources). Refactoring

### What issues does this PR fix or reference?
https://issues.jboss.org/browse/CHE-220

2017-05-22 14:31 UTC, ibuziuk commented
cc @mlabuda

2017-05-22 16:08 UTC, sunix commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java
> +    public static final int OPENSHIFT_WAIT_POD_TIMEOUT                   = 240;
are these ones real changes or just formatting ?

2017-05-22 16:22 UTC, ibuziuk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java
> +    public static final int OPENSHIFT_WAIT_POD_TIMEOUT                   = 240;
real change & 2 deliberate shifts of '=' sign

2017-05-23 05:23 UTC, mlabuda requested changes
One comment, otherwise LGTM.

2017-05-23 07:38 UTC, sunix approved these changes
LGTM

2017-05-23 07:49 UTC, ibuziuk commented
@mlabuda there is no comment ;-)

2017-05-23 08:56 UTC, mlabuda requested changes
Ah, my comment somehow disappeared between posting a comment and submitting review. See comment now.

2017-05-23 08:56 UTC, mlabuda commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftContainerRemover.java
> +        scaleDownDeployment(deploymentName, namespace);
did you check that waiting in scaleDownDeployment works? If you remember, there is that bug with k8 client in deployment config waitings (https://github.com/fabric8io/kubernetes-client/issues/699). If it is same for deployments, then it waits for fixed time and then continue...

2017-05-23 08:58 UTC, ibuziuk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftContainerRemover.java
> +        scaleDownDeployment(deploymentName, namespace);
@mlabuda it works for me just fine

2017-05-23 09:32 UTC, mlabuda commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftContainerRemover.java
> +        scaleDownDeployment(deploymentName, namespace);
If it works, +1 ;)

2017-05-23 09:32 UTC, mlabuda approved these changes

2017-05-23 11:34 UTC, l0rd reviewed
Great job @ibuziuk but I would rename `OpenShiftContainerRemover` class and `removeContainer()` method because we are not removing a container but a deployment. Maybe `OpenShiftDeploymentCleaner` and `cleanDeploymentResources()` are more indicated

2017-05-23 16:23 UTC, amisevsk requested changes
One typo that should be fixed, looks good to me apart from that. I've added a few comments for clarification as well.

2017-05-23 16:23 UTC, amisevsk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftContainerRemover.java
> +public class OpenShiftContainerRemover {
WDYT about making this class a static utility class? That way we don't have to inject it in OpenShiftConnector, and can instead refer to static methods. The OpenShiftConnector constructor is already getting quite unwieldy.

2017-05-23 16:23 UTC, amisevsk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftContainerRemover.java
> +    private void waitUntilWorspacePodIsDeleted(final String deploymentName, final String namespace) throws OpenShiftException {
Typo: waitUntilWor**k**spacePodIsDeleted

2017-05-23 16:23 UTC, amisevsk commented on plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftRouteCreator.java
> +    public void createRoute (final String namespace,
What do we gain by making this class non-static?

2017-05-23 16:24 UTC, amisevsk commented
+1 to the rename suggested by @l0rd

2017-05-23 17:48 UTC, amisevsk approved these changes

2017-05-23 18:27 UTC, ibuziuk commented
@amisevsk @l0rd rename & typo are fixed
in terms of static vs. singleton components (in our context it can be also rephrased to procedure programming vs OOP)

Basically, the rule-of-thumb is that static methods should be used for pure utilities like `KubernetesResourceUtil.java` and code reuse should be achieved via composition in OOP (via DI in our case).

However, I do agree that with the increasing number of components the constructor is becoming polluted with the args.  In Spring, for example, there is no such problem with polluted constructors - 
`@Autowired` and `@Value` annotations are used directly on class fields for injecting components / env vars. Maybe, it is possible to reimplement DI in OpenShiftConnector and inject properties without using constructor ? 

In general, I would  prefer to use `@Singleton` annotation for stateless components as much as possible a

2017-05-23 19:01 UTC, amisevsk commented
@ibuziuk Alright, makes sense. :+1:

2017-05-24 11:05 UTC, l0rd approved these changes

2017-05-24 11:06 UTC, l0rd commented
If @sunix is ok we can merge

2017-05-24 11:20 UTC, ibuziuk commented
cherry-picking to `openshift-connector-rebased` https://github.com/sunix/che/pull/1

2017-05-24 13:18 UTC, merged

2017-05-24 13:34 UTC, ibuziuk commented
cherry-picking to origin's `openshift-connector-rebased` https://github.com/eclipse/che/pull/5191