Correcting maven-dependency-plugin issue #5272
eclipse/che pull request #5277
Opened 2017-06-02 15:44 UTC by fliot

This pull request allow successfull maven build, without "<mdep.analyze.skip>true</mdep.analyze.skip>" profile settings.

It correspond to the issue #5272 

Regards.

2017-06-14 06:26 UTC, skabashnyuk commented
ci-build

2017-06-20 07:13 UTC, skabashnyuk commented
ci-build

2017-06-20 08:12 UTC, skabashnyuk requested changes
The source code is not compiling.

2017-06-20 08:12 UTC, skabashnyuk commented on wsmaster/che-core-api-auth/pom.xml
> +            <artifactId>everrest-core</artifactId>
11:02:07 /home/codenvy/workspace/che-pullrequests-build/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java:234: error: cannot access JsonValue
11:02:07             return JsonHelper.fromJson(urlInputStream, userClass, null);
11:02:07                              ^
11:02:07   class file for org.everrest.core.impl.provider.json.JsonValue not found
11:02:07 1 error
11:02:08 [JENKINS] Archiving disabled

2017-06-21 14:23 UTC, mkuznyetsov commented
Correct scopes have been set for all dependencies in this PR
https://github.com/eclipse/che/pull/5416

2017-06-22 06:03 UTC, closed without merging