Cli tests
eclipse/che pull request #5304
Opened 2017-06-08 14:28 UTC by riuvshin

### What does this PR do?
fix existing CLI tests and add some more:
- cmd config test
- cmd stop, restart tests
- cmd info test

logs:

```
Running tests in container from image eclipse/che-bats:nightly
Running functional bats tests for CLI prompts and usage
 ✓ test CLI prompt to provide volume for docker sock
 ✓ test CLI prompt to provide directory for user data
 ✓ test CLI 'usage' when running container without command

3 tests, 0 failures
Running functional bats tests for init and destroy commands
 ✓ test 'init' and 'destroy --quiet' with existing dir
 ✓ test 'init' and 'destroy --quiet' with non-existing dir
 ✓ test 'init' and 'destroy --quiet --cli' with existing dir
 ✓ test 'init' and 'destroy --quiet --cli' with non-existing dir

4 tests, 0 failures
Running functionals bats tests for start command
 ✓ test cli 'start' command with default settings
 ✓ test cli 'stop' command with default settings
 ✓ test cli 'restart' command with default settings
 ✓ test cli 'start' with custom port

4 tests, 0 failures
Running functionals bats tests for info command
 ✓ test CLI 'info' command

1 test, 0 failures
Running functionals bats tests for config command
 ✓ test CLI 'config' command

1 test, 0 failures
```

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5303

#### Changelog
fix existing CLI tests and add some more

2017-06-08 14:29 UTC, riuvshin commented
@mlabuda it would be awesome if you also will take a look on this :)

2017-06-09 05:37 UTC, mlabuda requested changes
At the time of writing those tests I was newborn to bash scripting, my bad for those bugs. 

PR review done. There are just 2 comments, otherwise LGTM.

2017-06-09 05:37 UTC, mlabuda commented on dockerfiles/cli/tests/cmd_start_stop_restart_tests.bats
> +  [[ "$(docker inspect --format='{{.State.Running}}' chetest)" == "" ]]
Is this necessary? In next step you check that there is no such container, thus this should always pass.

2017-06-09 05:37 UTC, mlabuda commented on dockerfiles/cli/tests/cmd_start_stop_restart_tests.bats
> +  [[ "$(docker inspect --format='{{.State.Running}}' chetest)" == "true" ]]
To verify that a container is running after performing restart command, I would rather choose more bulletproof check. This way, if restart would do nothing, container would still be in running state and those checks would pass.

I suggest to use e.g. .State.Pid value for check actual value of process id before and after restart. But bcs. pid is not unique, maybe better would be to use .State.StartedAt.

2017-06-09 07:48 UTC, riuvshin commented on dockerfiles/cli/tests/cmd_start_stop_restart_tests.bats
> +  [[ "$(docker inspect --format='{{.State.Running}}' chetest)" == "" ]]
agreed

2017-06-09 07:48 UTC, riuvshin commented on dockerfiles/cli/tests/cmd_start_stop_restart_tests.bats
> +  [[ "$(docker inspect --format='{{.State.Running}}' chetest)" == "true" ]]
good catch!

2017-06-09 11:39 UTC, mlabuda requested changes

2017-06-09 11:39 UTC, mlabuda commented on dockerfiles/cli/tests/cmd_start_stop_restart_tests.bats
> +  [[ "$(docker inspect --format="{{.Id}}" chetest)" != "$che_container_id" ]]
Does the restart command on docker CLI container delete a container and start a new one? If not and it just reuse `docker restart` with some more magic, then the container ID is still the same.

2017-06-10 10:28 UTC, riuvshin commented on dockerfiles/cli/tests/cmd_start_stop_restart_tests.bats
> +  [[ "$(docker inspect --format="{{.Id}}" chetest)" != "$che_container_id" ]]
yes, CLI restart command does CLI stop and CLI start commands, and CLI stop command stop and remove container.

2017-06-12 21:07 UTC, riuvshin commented
@mlabuda @benoitf @TylerJewell hey guys, I've updated PR with fixes and more tests. please review

2017-06-13 08:18 UTC, mlabuda requested changes

2017-06-13 08:18 UTC, mlabuda commented on dockerfiles/cli/tests/cmd_backup_restore_tests.bats
> +  ip_address=$(docker inspect -f {{.NetworkSettings.Networks.bridge.IPAddress}} che)
we are using those 3 lines on many places. Maybe we could extract them and parametrize to make it reusable. WDYT?

2017-06-13 08:18 UTC, mlabuda commented on dockerfiles/cli/tests/cmd_config_tests.bats
> +  docker run --rm -v "${SCRIPTS_DIR}":/scripts/base -v /var/run/docker.sock:/var/run/docker.sock -v "${tmp_path}":/data $CLI_IMAGE destroy --quiet --skip:nightly --skip:pull
See comment about setup/teardown above.

2017-06-13 08:18 UTC, mlabuda commented on dockerfiles/cli/tests/cmd_config_tests.bats
> +  [[ -f "${container_tmp_path}"/instance/che.ver.do_not_modify ]]
just a question, why do you check some files with -f and others with -e ?

2017-06-13 08:22 UTC, riuvshin commented on dockerfiles/cli/tests/cmd_config_tests.bats
> +  [[ -f "${container_tmp_path}"/instance/che.ver.do_not_modify ]]
there is no `-e` checks `-d` - test is it a dir and `-f` is it a file

2017-06-13 08:22 UTC, riuvshin commented on dockerfiles/cli/tests/cmd_backup_restore_tests.bats
> +  ip_address=$(docker inspect -f {{.NetworkSettings.Networks.bridge.IPAddress}} che)
+1 will do

2017-06-13 08:23 UTC, riuvshin commented on dockerfiles/cli/tests/cmd_backup_restore_tests.bats
> +  docker run --rm -v "${SCRIPTS_DIR}":/scripts/base -v /var/run/docker.sock:/var/run/docker.sock -v "${tmp_path}":/data $CLI_IMAGE stop --skip:nightly --skip:pull
agreed, that should be more stable. and now I;ve added separate test for `stop` command so  I will update this.

2017-06-13 09:29 UTC, mlabuda commented on dockerfiles/cli/tests/cmd_config_tests.bats
> +  [[ -f "${container_tmp_path}"/instance/che.ver.do_not_modify ]]
Sorry, placed on different line, bcs there are more such lines, see in all checks, there are few -e checks. There are -d tests for directories and -f tests for regular files, but there are also -e tests which match to any kind of file or link....

2017-06-13 10:09 UTC, mlabuda commented on dockerfiles/cli/tests/cmd_config_tests.bats
> +  [[ -f "${container_tmp_path}"/instance/che.ver.do_not_modify ]]
Yeah, it should be fine, I was just wondering why it is mixed, whether some of those files are just symlinks or whatever :)

2017-06-13 12:04 UTC, riuvshin commented on dockerfiles/cli/tests/cmd_backup_restore_tests.bats
> +  docker run --rm -v "${SCRIPTS_DIR}":/scripts/base -v /var/run/docker.sock:/var/run/docker.sock -v "${tmp_path}":/data $CLI_IMAGE stop --skip:nightly --skip:pull
done.

2017-06-13 12:04 UTC, riuvshin commented on dockerfiles/cli/tests/cmd_backup_restore_tests.bats
> +  ip_address=$(docker inspect -f {{.NetworkSettings.Networks.bridge.IPAddress}} che)
done.

2017-06-13 12:18 UTC, riuvshin commented
@mlabuda I also working on moving docker run to execute cli command to separate method

2017-06-13 14:54 UTC, riuvshin commented
@mlabuda it's done :) now it is way simpler and obvious.

2017-06-13 15:16 UTC, riuvshin commented
@mlabuda finally pushed :) now it is ready :) 
I've added `execute_cli_command` method to simplify cli commands invocation.

2017-06-14 08:18 UTC, mlabuda approved these changes

2017-06-14 08:20 UTC, mlabuda commented
LGTM. Just a question - I have noticed almost every execution of Che CLI has skip pull and skip nightly. Maybe it could be included by default in execution of Che CLI so we avoid more repetition. E.g having DEFAULT_EXTRA_OPTIONS appended to extra options and if user does not provide --che-cli-default-extra-opts then "-skip:nightly --skip:pull" will be used as default.

2017-06-14 08:39 UTC, riuvshin commented
@mlabuda yeah... I will take a look on this later. I just want to merge this and then will introduce another PR with more tests and improvements.

2017-06-14 09:38 UTC, benoitf approved these changes
tested and worked on my env

2017-06-14 09:44 UTC, riuvshin commented
Thanks guys!

2017-06-14 09:46 UTC, merged