adapt che-server entrypoint.sh to environments without write permissions in '/'
eclipse/che pull request #5344
Opened 2017-06-12 14:44 UTC by riuvshin

### What does this PR do?
proper fix for permission issue https://github.com/eclipse/che/pull/5305

after discussion with @davidfestal, we decided to check if we have write permissions to `/` we keep old logic which keep CLI and non-CLI use-cases not touched, but if there is no write permissions to `/` like in OS case we set **CHE_LOCAL_CONF_DIR** to **${CHE_DATA}/conf** `(/data/conf)`

#### Changelog
adapt che-server entrypoint.sh to environments without write permissions in '/'

2017-06-12 14:45 UTC, riuvshin commented
@davidfestal can you please test this PR with OS environment to make sure it works as expected ? :)

2017-06-12 14:47 UTC, benoitf approved these changes

2017-06-12 14:52 UTC, davidfestal commented
@riuvshin sure. I'll test is asap

2017-06-12 16:17 UTC, l0rd approved these changes
LGTM

2017-06-12 16:25 UTC, sunix commented on dockerfiles/che/entrypoint.sh
> +  if [ -w / ]; then
maybe also test write access to /conf ?

2017-06-12 16:53 UTC, davidfestal requested changes

2017-06-12 16:53 UTC, davidfestal commented on dockerfiles/che/entrypoint.sh
> +    echo "WARN: parent dir is not writeable, CHE_LOCAL_CONF_DIR will be set to ${CHE_DATA}/conf"
It was `CHE_DATA_HOST` and not `CHE_DATA`

2017-06-12 16:57 UTC, davidfestal commented on dockerfiles/che/entrypoint.sh
> +    echo "WARN: parent dir is not writeable, CHE_LOCAL_CONF_DIR will be set to ${CHE_DATA}/conf"
that was what was used before your inital change
in commit 4813a1a712abb1e0bb949b1c2dcdc7a7b206fd63
and this is the property that is used in the related Openshift deployment config.

2017-06-12 17:00 UTC, riuvshin commented on dockerfiles/che/entrypoint.sh
> +  if [ -w / ]; then
added checks

2017-06-12 17:01 UTC, riuvshin commented on dockerfiles/che/entrypoint.sh
> +    echo "WARN: parent dir is not writeable, CHE_LOCAL_CONF_DIR will be set to ${CHE_DATA}/conf"
that was a mistake, `CHE_DATA_HOST` is a path actual for user PC like `/home/roman/.che/data` but we need path actual for container `/data`

2017-06-12 17:03 UTC, riuvshin commented
PR updated, I also figured why @davidfestal had:

```
1) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=che.port) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=che.port)
    for the 5th parameter of org.eclipse.che.plugin.docker.machine.CustomServerEvaluationStrategy.<init>(CustomServerEvaluationStrategy.java:85)
  at org.eclipse.che.plugin.docker.machine.local.LocalDockerModule.configure(LocalDockerModule.java:62) (via modules: org.eclipse.che.api.deploy.WsMasterModule -> org.eclipse.che.plugin.docker.machine.local.LocalDockerModule)

1 error
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
    at com.google.inject.Guice.createInjector(Guice.java:99)
    at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
    at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
```
it was missing `export` on `CHE_PORT`, that is why it was working by passing it with `-e CHE_PORT=8080`

2017-06-13 08:44 UTC, davidfestal commented
I tested this on Minishift and can confirm it works as well in this Openshift use-case. Thanks @riuvshin

2017-06-13 08:45 UTC, davidfestal commented on dockerfiles/che/entrypoint.sh
> +    echo "WARN: parent dir is not writeable, CHE_LOCAL_CONF_DIR will be set to ${CHE_DATA}/conf"
OK, right

2017-06-13 08:45 UTC, davidfestal approved these changes
OK for me to merge

2017-06-13 08:49 UTC, merged