CHE-15 - Java stacktrace support (From Platform to Che Workspace)
eclipse/che pull request #5396
Opened 2017-06-16 14:36 UTC by vrubezhny

Adds the possibility to click on a stacktrace line in order to open
a specified class in editor.
Also fixes CHE-293 (#5001) - String Written to Dev-Machine stdout not Escaped Properly

Issue: https://issues.jboss.org/browse/CHE-15
Issue: https://issues.jboss.org/browse/CHE-293

see: https://github.com/eclipse/che/issues/5001

Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### What does this PR do?
Adds the possibility to click on a stacktrace line in order to open
a specified class in editor.
Also fixes CHE-293 (#5001) - String Written to Dev-Machine stdout not Escaped Properly

### What issues does this PR fix or reference?
Issue: https://issues.jboss.org/browse/CHE-15
Issue: https://issues.jboss.org/browse/CHE-293
(Issue: https://github.com/eclipse/che/issues/5001)

#### Changelog

#### Release Notes

#### Docs PR

2017-06-16 14:45 UTC, benoitf requested changes

2017-06-16 14:45 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputConsole.java
> +    private OutputCustomizer					customizer = null;
hello, is that the indent is expected ?

2017-06-16 14:45 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputConsole.java
> +
this line shouldn't be introduced

2017-06-16 14:45 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputConsole.java
> +
this line(spaces) shouldn't be introduced

2017-06-16 14:45 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputConsole.java
> +    	for (ActionDelegate actionDelegate : actionDelegates) {
indent is with spaces, not with tabs

2017-06-16 14:45 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputConsole.java
> +    	for (ActionDelegate actionDelegate : actionDelegates) {
you've to check in the whole file as I see mainly only tabs while spaces are expected.

2017-06-16 14:45 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java
> +    private EditorAgent editorAgent;
the indent looks odd

2017-06-16 14:45 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java
> +public class DefaultOutputCustomizer implements OutputCustomizer {
it is missing javadoc on the class. What it does, etc

2017-06-16 14:45 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java
> +	private static RegExp LINE_AT_EXCEPTION = compile("(\\s+at address:.+)");
it is missing the final keyword for the constants.

2017-06-16 14:45 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java
> +    	String customText = text;
the formatting looks like it is not the expected one

2017-06-16 14:45 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java
> +    	if(matcher != null) {
spaces around parenthesis

2017-06-16 14:46 UTC, benoitf commented
ci-build

2017-06-16 14:47 UTC, benoitf commented
as this issue is not a fix, it should include changelog and the release notes section.
@slemeur maybe documentation as well ?

2017-06-16 14:58 UTC, vrubezhny commented
@benoitf  I've added a couple of words to Change log. However, I don't know what is to be placed for Release Notes (especially once it not released yet)

2017-06-16 15:00 UTC, benoitf commented
@vrubezhny Changelog should be a one-line entry, so maybe move your "changelog" text as "Release notes" text and it should be ok

2017-06-16 15:04 UTC, benoitf commented
@vrubezhny also there was a compilation issue https://ci.codenvycorp.com/job/che-pullrequests-build/2833/

2017-06-16 15:48 UTC, slemeur commented
Hi @vrubezhny ! 
This seems really cool. 

@benoitf is right, this PR introduces a new feature so we need the release note section and the documentation prior to the merge. I can help on that. 
We'll also need the QA team to review and validate the changes: @musienko-maxim. 

Would you mind recording an animated gif to demo the new capability and attach it to the description of the PR?

2017-06-16 15:48 UTC, vrubezhny commented
@benoitf  The compilation is known: my to classes (intrf+impl) have "RedHat, Inc." in their headers instead of "Codenvy, S.A.". I don't feel like adding the whole che-core-ide-app as an exclusion to license-maven-plugin is a good approach. Is there a better solution? (Or I just have to use original CodeEnvy's header?)

2017-06-16 15:52 UTC, vrubezhny commented
@slemeur I've copied text of ChangeLog to Release Notes. Please let me know if it's not enough.

And I'll try to record an animated gif... (not sure if I can do it on Fedora, though)

2017-06-16 17:17 UTC, vrubezhny commented
@benoitf I believe I fixed formatting and other issues you pointed to, as well as the 'missing headers' one. Thanks for the review.

2017-06-16 17:35 UTC, vrubezhny commented
ci-build

2017-06-16 19:16 UTC, benoitf commented
ci-build

2017-06-16 19:18 UTC, benoitf commented
@vrubezhny as there is the use of regexp and parsing, IMHO a unit test should be added to cover the analysis of the stack trace.
Else it will be hard to track if it's still working or not upon refactoring.

2017-06-16 23:04 UTC, vrubezhny commented
@slemeur I've added the animated gifs to the PR description.

@benoitf The commit is updated due to the issue in my code, so ci-build is required for the PR once again. Sorry about that.

2017-06-17 09:40 UTC, benoitf commented
@vrubezhny Hello Vector. I'm not seing unit test as said yesterday. Also, could you add changes as adding a new commit (like using --fixup option) because, it's impossible to track what you changed between each review as we see only one commit even if you've done changes. Squashing/Rebasing can be done later when merging it. thanks.

2017-06-17 13:14 UTC, vrubezhny commented
@benoitf Yep, I haven't made JUnit test yet - I'll work on it on Monday. Thanks for pointing me to '--fixup' option, I'll follow this policy.

2017-06-19 10:06 UTC, slemeur commented
Hi @vrubezhny. Thanks for adding the animated gif, they are perfect. Looking at the code, I see that the regexp will properly cover java stacktraces. AFAIK it should also work for NodeJS but I'm bit worry that this might also create wrong interpretation for other type of stacktraces and bother the user. 

So to start the discussion, should we:
- check that the text found by the parser is actually a file before colorizing it and putting a link behind?
- should we also handle urls?
- allow the user to disable the smart selection in the console output
- have the ability for the user to add regular expressions (in preferences for example)?
- should we have the same behaviour in the terminal?

2017-06-20 14:36 UTC, vrubezhny commented
> Hi @vrubezhny. Thanks for adding the animated gif, they are perfect. Looking at the code, I see that the regexp will properly cover java stacktraces. AFAIK it should also work for NodeJS but I'm bit worry that this might also create wrong interpretation for other type of stacktraces and bother the user.

That's it. It's proposed to work with java-stacktraces printed out to a console, it's not intended to work with other kinds of stacktraces.  With proposed OutputCustomizer interface we can develop different kinds of customizer. Also, we can add preferences to allow enabling/disabling to the customizers, or configure different kinds of consoles to use different customizers.

> So to start the discussion, should we:
> - check that the text found by the parser is actually a file before colorizing it and putting a link behind?

We can't do that, first of all because of the performance reasons: it takes quite a lot of time (and I suppose a several asynchronous IO requests) to perform such a check. If we make it synchronously the console output would tend to freeze. Otherwise the text would not be printed in FIFO manner. As far as I know, desktop eclipse doesn't check for a file existence when a stacktrace is being printed out to a console, it performs searching when a user clicks on a colorized line.
The only thing I probably would verify (beside of matching the stacktrace line RegExp) is that file name really ends with ".java" to make sure that we're in "proper" stacktrace line.

> - should we also handle urls?

Not sure I understand right... Have an example of URLs appearance?

> - allow the user to disable the smart selection in the console output

Do you mean like "to disable" the console text customization (turning it to a link) and as such, not to provide a user with the possibility to search for a class by a stacktrace line? Not sure. I didn't see such a preference before.

> - have the ability for the user to add regular expressions (in preferences for example)?

If you're going to process the other kinds of stacktraces (like the javascript ones) then you should have the other kind of detection and post-processing (like parsing the line for packages/classes/file name/line number and/or adding, probably, javascript-to-java mappings to your search algorithm). This is not something that easy to realize as something that can be configured by preference and, imho, we should rather provide different customizers for users and let them a possibility to enable/disable them. Or hardly set up different customizers depending on the kind of console it should work on.  

> - should we have the same behaviour in the terminal?

As far as I understand, my change configures the terminal to use this customizer. So, if a java stacktrace would appear in terminal it will be customized as well. If it's not required I can try to disable/remove this behaviour from terminal.

2017-06-23 20:37 UTC, vrubezhny commented
@benoitf I'm going to add a commit with JUnit test to this PR. Should I use that `--fixup` option, or a separate commit would be OK?

2017-06-23 20:57 UTC, benoitf commented
@vrubezhny it is up to you, in all cases it will add a new commit (fixup is generating a commit as well)
At the end of the review you can either automatically rebase if you used fixup or manually rebase 
Or we squash commits when merging on github

2017-06-26 09:25 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java
> +                text = customText;
do you think that a String.format would be easier to read than concatenating tons of stuff ?

2017-06-26 09:27 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java
> +                for (Resource child : children) {
would it be simpler to read with streams / filter/ Collectors.toList() ?

2017-06-26 09:28 UTC, benoitf commented on ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/console/DefaultOutputCustomizerTest.java
> +}
an empty blank line is required at the end of the file

2017-06-26 13:05 UTC, benoitf commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java
> +                text = customText;
so bad idea as GWT is not supporting formatting 👎

2017-06-26 13:26 UTC, vrubezhny commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java
> +                text = customText;
String.format/MessageFormat.format/Formatter.format are not available for GWT application and it doesn't look like a GWT replacement exists.

2017-06-26 13:41 UTC, benoitf approved these changes

2017-06-26 13:48 UTC, vrubezhny commented
@benoitf I've added fixups for:
- turning org.eclipse.che.ide.console.DefaultOutputCustomizer.collectChildren(Container, Path) to use streams / filter/ Collectors.toList() 
- added new line to last line of DefaultOutputCustomizerTest
- added new line before DefaultOutputCustomizer.collectChildren() method's closing bracket (somehow lost on formatting)

2017-06-26 13:51 UTC, benoitf commented
@vparfonov ?

2017-06-27 16:33 UTC, slemeur approved these changes

2017-06-29 14:29 UTC, sunix approved these changes

2017-06-30 07:54 UTC, vparfonov approved these changes

2017-06-30 08:29 UTC, merged