Implement golang bootstrapper
eclipse/che pull request #5399
Opened 2017-06-19 08:23 UTC by evoevodin

Added golang app which implements bootstrapper [spec(bootstrapper - agents workflow)]( https://github.com/eclipse/che/issues/4096#issuecomment-283067971).

#### Usage
```
Usage of ./bootstrapper:
  -file string
        Path to configuration file on filesystem (default "/path/to/binary/location/config.json")
  -installer-timeout int
        Time(in seconds) given for one installer to complete its installation.
        If installation is not finished in time it will be interrupted (default 120)
  -machine-name string
        The name of the machine in which this bootstrapper is running
  -push-endpoint string
        WebSocket endpoint where to push statuses
  -push-logs-endpoint string
        WebSocket endpoint where to push logs
  -runtime-id string
        The identifier of the runtime in format 'workspace:environment:owner'
  -server-check-period int
        Time(in seconds) between servers availability checks.
        Once servers for one installer available checkers stops (default 3)
```

#### Assembly 
`mvn clean install` creates assemblies for the following architectures
```
linux_arm5
linux_arm6
linux_arm7
linux_amd64
linux_i386
```

#### Example
For the configuration file
```json
[
  {
    "id": "exec",
    "description": "Agent for command execution",
    "version": "1.0",
    "script": "printf \"1\n2\n3\n4\n5\n6\n7\n8\n9\n10\""
  },
  {
    "id": "agent",
    "description": "Agent",
    "version": "1.0",
    "script": "echo agent-007"
  },
  {
    "id": "agent-with-server",
    "description": "this is agent with server",
    "version": "1.0",
    "script": "set -e\ntdir\u003d$(mktemp -d)\ncd $tdir\nAGENT_TAR\u003dexec-agent-linux_amd64.tar.gz\nwget http://nightly.codenvy-stg.com/agent-binaries/linux_amd64/exec/${AGENT_TAR}\ntar -xzf ${AGENT_TAR}\n./exec-agent/che-exec-agent\n",
    "servers": {
      "exec": {
        "port": "9000/tcp",
        "protocol": "http"
      }
    }
  }
]
```
bootstrapper output will be 
```
2017/06/19 11:17:00 Bootstrapper Configuration
2017/06/19 11:17:00   Push Endpoint: ws://localhost:2288/logging-server-connect
2017/06/19 11:17:00   Push Logs Endpoint: ws://localhost:2288/logging-server-connect
2017/06/19 11:17:00   Runtime ID:
2017/06/19 11:17:00     Workspace: workspace
2017/06/19 11:17:00     Environment: env
2017/06/19 11:17:00     Owner: owner
2017/06/19 11:17:00   Machine Name: my-machine
2017/06/19 11:17:00   Installer Timeout: 120seconds
2017/06/19 11:17:00   Check Servers Period: 3seconds
2017/06/19 11:17:00 Planning to install
2017/06/19 11:17:00 - exec:1.0 - Agent for command execution
2017/06/19 11:17:00 - agent:1.0 - Agent
2017/06/19 11:17:00 - agent-with-server:1.0 - this is agent with server
2017/06/19 11:17:00 Starting installations
2017/06/19 11:17:00 Installing 'exec'
2017/06/19 11:17:00 Installation of 'exec' successfully finished
2017/06/19 11:17:00 Installing 'agent'
2017/06/19 11:17:00 Installation of 'agent' successfully finished
2017/06/19 11:17:00 Installing 'agent-with-server'
2017/06/19 11:17:15 Installation of 'agent-with-server' successfully finished
2017/06/19 11:17:15 All installations successfully finished
```

### What issues does this PR fix or reference?
resolves https://github.com/eclipse/che/issues/4099
spec - https://github.com/eclipse/che/issues/4096#issuecomment-283067971
new installation approach - https://github.com/eclipse/che/issues/3971

Please note that these changes are going to be merged into SPI branch.

2017-06-19 11:10 UTC, skabashnyuk commented on agents/go-agents/bootstrapper/booter/installations.go
> +	addr := "localhost:" + port
Are you sure ```localhost``` is always available?

2017-06-19 11:50 UTC, gazarenkov commented
Please specify what kind of events will be emitted during the sample bootstrapping
I think corresponding to this part of log:
2017/06/19 11:17:00 Starting installations
2017/06/19 11:17:00 Installing 'exec'
2017/06/19 11:17:00 Installation of 'exec' successfully finished
2017/06/19 11:17:00 Installing 'agent'
2017/06/19 11:17:00 Installation of 'agent' successfully finished
2017/06/19 11:17:00 Installing 'agent-with-server'
2017/06/19 11:17:15 Installation of 'agent-with-server' successfully finished
2017/06/19 11:17:15 All installations successfully finished

2017-06-19 12:12 UTC, evoevodin commented
ok

2017-06-19 16:50 UTC, gazarenkov approved these changes

2017-06-19 18:57 UTC, evoevodin commented on agents/go-agents/bootstrapper/booter/booter.go
> +// start exists returning that error.
thank you

2017-06-19 18:57 UTC, evoevodin commented on agents/go-agents/bootstrapper/booter/booter.go
> +		Add(installer)
makes sense

2017-06-20 06:45 UTC, skabashnyuk approved these changes

2017-06-20 09:06 UTC, garagatyi requested changes

2017-06-20 09:06 UTC, garagatyi commented on agents/go-agents/bootstrapper/booter/installations.go
> +			return fmt.Errorf("server address 'localhost:%s' already in use", server.Port)
I suppose that already running server is not a problem for an agent start. For example, [ubuntu_jdk8 image](https://hub.docker.com/r/eclipse/ubuntu_jdk8/~/dockerfile/) start SSHD as the main command of the container. So with this check SSH agent will fail on that image.

2017-06-20 09:14 UTC, garagatyi commented on agents/go-agents/bootstrapper/booter/installations.go
> +		return fmt.Errorf("Process of installation '%s' exited before server became available", svi.installer.ID)
I suppose in case SSHD is already running, installation script exits immediately, so this error will occur even if the server is available. WDYT?

2017-06-20 09:21 UTC, evoevodin commented on agents/go-agents/bootstrapper/booter/installations.go
> +		return fmt.Errorf("Process of installation '%s' exited before server became available", svi.installer.ID)
I thought that execution of scripts which install servers must not exit, but it turns out that 
exitCode == 0  + servers availability should be considered as successful installation.
I will rework it, thank you!

2017-06-20 09:45 UTC, evoevodin commented
@garagatyi fixed, please review changes

2017-06-20 11:14 UTC, garagatyi approved these changes
Looks good. Good job!

2017-06-20 12:54 UTC, merged