CHE-274 - Improve idling implementation
eclipse/che pull request #5425
Opened 2017-06-21 20:22 UTC by snjeza

Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

See https://github.com/eclipse/che/pull/5386

2017-06-22 06:06 UTC, skabashnyuk commented
Need to add docs, changes log, release notes section

2017-06-22 15:50 UTC, bmicklea commented
@snjeza I've added the template for PR descriptions here with hidden HTML comments on what each section means. Please fill it in as well as you can and I will review.

2017-06-22 19:00 UTC, snjeza commented
@bmicklea I have updated the PR description.

2017-06-23 13:29 UTC, bmicklea commented
Due to some administrative issue on the eclipse side I've lost committer rights temporarily so I can't update this myself which is what I'd normally do.

I think there's a typo in the changelog - it should be 3,600,000 not 360,000 right? And I noticed this is changed in che-properties, but is there an option added to `che.env` to allow users to change it?

Also, please add a label for `kind/enhancement`.

2017-06-26 09:58 UTC, slemeur approved these changes

2017-06-26 10:02 UTC, benoitf requested changes

2017-06-26 10:02 UTC, benoitf commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/LastAccessTimeFilter.java
> + * NOTICE:  All information contained herein is, and remains
copyright seems to be wrong. it should be EPL

2017-06-26 10:02 UTC, benoitf commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/WorkspaceActivityNotifier.java
> +package org.eclipse.che.api.agent.server.activity;
in che, copyrights are EPL

2017-06-26 10:02 UTC, benoitf commented
ci-build

2017-06-26 11:03 UTC, skabashnyuk commented
@snjeza  we need to do appropriate changes in codenvy to reuse this code. please do not merge until we will be ready.

2017-06-26 15:07 UTC, snjeza commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/WorkspaceActivityNotifier.java
> +package org.eclipse.che.api.agent.server.activity;
I have updated the PR.

2017-06-26 15:18 UTC, benoitf commented
ci-build

2017-06-27 07:43 UTC, benoitf commented
@snjeza build is failing : https://ci.codenvycorp.com/job/che-pullrequests-build/2909/org.eclipse.che.core$che-core-api-workspace/console

2017-06-27 14:53 UTC, snjeza commented
@benoitf There is a newer build - https://ci.codenvycorp.com/job/che-pullrequests-build/2920
It has a test failure that I can't reproduce it locally.

2017-06-27 14:54 UTC, benoitf commented
let's restart the build on jenkins

2017-06-27 14:54 UTC, benoitf commented
ci-build

2017-06-27 16:28 UTC, benoitf approved these changes
Will require changes in codenvy before merging

2017-06-28 08:09 UTC, sunix commented
@benoitf 

> Will require changes in codenvy before merging

is someone working on this ?

2017-06-28 08:25 UTC, benoitf commented
@sunix : iI suppose it's @skabashnyuk team

2017-07-03 06:32 UTC, mkuznyetsov commented
Copied content from this PR into new one: https://github.com/eclipse/che/pull/5512

2017-07-03 06:32 UTC, closed without merging