Make gwt-logger project m2e-compatible
eclipse/che pull request #5496
Opened 2017-06-29 09:27 UTC by tsmaeder

This PR restructures the project to work with Eclipse m2e maven tooling. The idea is to move the overridden classes in slf4j to a different source folder and to use the maven-resources-plugin to copy the source files to the output folder (instead of relying on default resource-copy mechanism).
The result is that the maven project can be properly parsed in Eclipse and compilation errors in the overridden classes show up in eclipse.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5487

2017-06-30 05:00 UTC, skabashnyuk commented
ci-build

2017-06-30 07:26 UTC, benoitf commented on ide/gwt-logger/pom.xml
> +		<plugins>
@tsmaeder you've introduced "tab" characters while the file is formatted with spaces.

what you can do is:
```
$  cd ide/gwt-logger
$ mvn -o com.google.code.sortpom:maven-sortpom-plugin:sort
```

2017-06-30 07:27 UTC, benoitf commented on ide/gwt-logger/pom.xml
> +						<!-- here the phase you need -->
I think this comment might be removed, it's more like a copy from a tutorial.

2017-06-30 08:31 UTC, benoitf requested changes
formatting issue

2017-06-30 11:43 UTC, tsmaeder commented on ide/gwt-logger/pom.xml
> +						<!-- here the phase you need -->
yup.

2017-06-30 11:44 UTC, tsmaeder commented on ide/gwt-logger/pom.xml
> +		<plugins>
That's the Eclipse xml formatter set to use tabs.

2017-06-30 12:17 UTC, benoitf approved these changes

2017-06-30 12:17 UTC, benoitf commented
ci-build

2017-06-30 13:22 UTC, benoitf commented
ci-build

2017-07-01 18:33 UTC, skabashnyuk reviewed
+0 up2 @vparfonov

2017-07-03 06:25 UTC, vparfonov approved these changes

2017-07-03 07:47 UTC, merged