Che 274a
eclipse/che pull request #5512
Opened 2017-07-03 06:31 UTC by mkuznyetsov

### What does this PR do?

Enable workspace shutdown after a specified inactivity period.

### What issues does this PR fix or reference?

https://issues.jboss.org/browse/CHE-274

### Changelog

Added the che.machine.ws.agent.inactive.stop.timeout.ms=3600000 and stop.workspace.scheduler.period property

### Release Notes

Per default, a workspace will be stopped after one hour of inactivity.

### Docs PR

N/A

See #5386

2017-07-03 07:51 UTC, benoitf approved these changes
I suppose there is a pending PR on codenvy repository as well ?

2017-07-03 07:54 UTC, benoitf commented
linked to https://github.com/codenvy/codenvy/pull/2297

2017-07-03 07:55 UTC, benoitf commented
@slemeur I think there is some doc required

2017-07-03 08:24 UTC, slemeur commented
added https://github.com/eclipse/che-docs/pull/253

2017-07-03 11:47 UTC, garagatyi commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +#     not interacted with the workspace, meaning that one of our agents has not received
One of the agents or any?

2017-07-03 11:47 UTC, garagatyi commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +#     this length of time. Idleness is determined by the length of time that a user has
I'd rather use `amount of time` instead of `length of time`

2017-07-03 11:47 UTC, garagatyi commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +stop.workspace.scheduler.period=60
Please prepend property name with `che.` and add measurement unit as a suffix of the property.

2017-07-03 11:47 UTC, garagatyi commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +che.machine.ws.agent.inactive.stop.timeout.ms=3600000
Part of a term that means single area are usually divided by underscores, e.g.  `che.machine.wsagent.inactive_stop_timeout_ms`

2017-07-03 11:47 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/LastAccessTimeFilter.java
> + * Counts every request to the agent as a workspace activity
Does it count frames in case of WebSocket connection or only connection itself?

2017-07-03 11:47 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/LastAccessTimeFilter.java
> +public class LastAccessTimeFilter implements Filter {
If this class is related to wsagent let's move it to wsagent related module

2017-07-03 11:47 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/LastAccessTimeFilter.java
> +public class LastAccessTimeFilter implements Filter {
Please add tests

2017-07-03 12:19 UTC, garagatyi requested changes
Mostly OK, but, please, add tests and take a look on my comments

2017-07-03 12:19 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/activity/WorkspaceActivityManager.java
> + * Stops the inactive workspaces by given expiration time.
As far as I can see this class not only stops workspaces but provides API for updating workspace activity timestamp. Can you rephrase javadocs in accordance with that?

2017-07-03 12:19 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/activity/WorkspaceActivityManager.java
> +                    LOG.info("Workspace already stopped");
Please ignore this exception - there is no need to log it

2017-07-05 11:55 UTC, slemeur approved these changes

2017-07-10 14:43 UTC, mkuznyetsov commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +che.machine.ws.agent.inactive.stop.timeout.ms=3600000
changed property name

2017-07-10 14:43 UTC, mkuznyetsov commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +stop.workspace.scheduler.period=60
changed property name

2017-07-10 14:46 UTC, mkuznyetsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/LastAccessTimeFilter.java
> +public class LastAccessTimeFilter implements Filter {
Moved to a separate module

2017-07-10 14:46 UTC, mkuznyetsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/LastAccessTimeFilter.java
> +public class LastAccessTimeFilter implements Filter {
Added tests

2017-07-10 14:48 UTC, mkuznyetsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/WorkspaceActivityNotifier.java
> +public class WorkspaceActivityNotifier {
Moved to separate module

2017-07-10 14:53 UTC, mkuznyetsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/activity/WorkspaceActivityManager.java
> + * Stops the inactive workspaces by given expiration time.
Javadoc updated

2017-07-10 14:53 UTC, mkuznyetsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/WorkspaceActivityNotifier.java
> + * Notifies master about activity in workspace, but not more often than once per minute.
Javadoc updated

2017-07-10 14:55 UTC, mkuznyetsov commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +#     this length of time. Idleness is determined by the length of time that a user has
thx, fixed

2017-07-10 14:56 UTC, mkuznyetsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/agent/server/activity/LastAccessTimeFilter.java
> + * Counts every request to the agent as a workspace activity
It would only react on HTTP requests going through the filter, updated Javadoc

2017-07-10 14:58 UTC, mkuznyetsov commented on assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
> +#     not interacted with the workspace, meaning that one of our agents has not received
removed this part

2017-07-11 07:09 UTC, garagatyi requested changes

2017-07-11 07:09 UTC, garagatyi commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/activity/WorkspaceActivityManager.java
> +public class WorkspaceActivityManager {
Please, add tests

2017-07-11 13:22 UTC, mkuznyetsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/activity/WorkspaceActivityManager.java
> + * Stops the inactive workspaces by given expiration time. Upon stopping, workspace attributes will be updated with
Corrected

2017-07-11 13:23 UTC, mkuznyetsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/activity/WorkspaceActivityManager.java
> +public class WorkspaceActivityManager {
Added WorkspaceActivityManagerTest

2017-07-11 13:23 UTC, mkuznyetsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/activity/WorkspaceActivityService.java
> + * Monitors the activity of the runtime workspace.
Corrected

2017-07-11 13:23 UTC, mkuznyetsov commented on wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/activity/WorkspaceActivityService.java
> +        final WorkspaceImpl workspace = workspaceManager.getWorkspace(wsId);
Added WorkspaceActivityServiceTest

2017-07-11 13:23 UTC, mkuznyetsov commented on wsagent/activity/src/main/test/org/eclipse/che/api/activity/LastAccessTimeFilterTest.java
> +        verify(workspaceActivityNotifier).onActivity();
fixed

2017-07-11 13:23 UTC, mkuznyetsov commented on wsagent/activity/src/main/test/org/eclipse/che/api/activity/LastAccessTimeFilterTest.java
> +    public void shouldLogExceptionUponActivityNotification() throws IOException, ServletException {
fixed name

2017-07-11 13:23 UTC, mkuznyetsov commented on wsagent/activity/src/main/java/org/eclipse/che/api/activity/WorkspaceActivityNotifier.java
> +    public WorkspaceActivityNotifier(HttpJsonRequestFactory httpJsonRequestFactory,
Added WorkspaceActivityNotifierTest

2017-07-11 13:37 UTC, garagatyi approved these changes

2017-07-12 09:09 UTC, benoitf approved these changes

2017-07-12 15:35 UTC, merged