CHE-5792: Add ability to adjust viewing 'maven module artifact id' in 'Appearance' preferences page
eclipse/che pull request #5849
Opened 2017-07-31 08:55 UTC by vinokurig

### What does this PR do?
Add ability to adjust viewing 'maven module artifact id' in 'Appearance' preferences page.
![maven_artifact_id](https://user-images.githubusercontent.com/7668752/28769579-c3bef300-75e4-11e7-96c4-4e7c9fd39fe9.png)

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5792

#### Changelog
Presense of Maven module artifact id in project explorer is adjusted in 'Appearance' preferences page.

#### Release Notes
Presence of Maven module artifact id in project explorer is adjusted in 'Appearance' preferences page.

#### Docs PR

N/A

2017-07-31 13:10 UTC, bmicklea approved these changes
updated changelog and label

2017-08-02 07:34 UTC, evidolob requested changes
All meven related preferences should be placed in maven plugin

2017-08-02 13:27 UTC, vinokurig commented
@evidolob Moved the code to maven plugin. Moved the check-box from 'Appearance' page to new 'Plugins' -> 'Maven' page in the preferences window.

2017-08-02 14:41 UTC, evidolob approved these changes

2017-08-02 14:46 UTC, vzhukovskii commented on plugins/plugin-maven/che-plugin-maven-ide/src/main/resources/org/eclipse/che/plugin/maven/client/MavenLocalizationConstant.properties
> +maven.preferences.show.artifact.id.checkbox.text=Show artifact id in project explorer (in project''s root item)
`(in project''s root item)` is odd, because artifact near presentable text may be present in sub modules, not only for the root project.

2017-08-02 14:46 UTC, vzhukovs approved these changes
Other ok.

2017-08-03 06:22 UTC, vinokurig commented on plugins/plugin-maven/che-plugin-maven-ide/src/main/resources/org/eclipse/che/plugin/maven/client/MavenLocalizationConstant.properties
> +maven.preferences.show.artifact.id.checkbox.text=Show artifact id in project explorer (in project''s root item)
Changed to `Show artifact id in project explorer`

2017-08-03 12:31 UTC, vparfonov approved these changes

2017-08-07 16:52 UTC, slemeur commented
@vinokurig I think we could add documentation for that new capability. What about a mention in this section: https://github.com/eclipse/che-docs/blob/master/src/main/_docs/ide/ide-projects.md#project-explorer ?

2017-08-07 16:53 UTC, slemeur commented
@vinokurig : Could you show an example of how this is handled when you display the maven module + the git branch?

2017-08-08 11:18 UTC, vinokurig commented
@slemeur 
![screenshot-172 17 0 1-8080-2017-08-08-14-14-04](https://user-images.githubusercontent.com/7668752/29069586-2eec47ee-7c44-11e7-874f-02237def11ca.png)

I will add docks PR

2017-08-08 12:07 UTC, slemeur commented
Ok great. Thanks !

2017-08-09 14:48 UTC, vinokurig commented
@slemeur @bmicklea Added docs

2017-08-09 15:02 UTC, slemeur approved these changes
Good for me

2017-08-14 05:22 UTC, merged