Che multiuser che theme
eclipse/che pull request #5859
Opened 2017-08-01 07:06 UTC by mmorhun

### What does this PR do?
Adds draft of Che theme for Keycloak login theme.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5786

#### Changelog
N/A Hasn't released yet.

#### Release Notes
N/A

2017-08-01 08:24 UTC, riuvshin approved these changes

2017-08-01 08:25 UTC, riuvshin commented
@mmorhun please check ci build fail report it failed due to 
"Some files do not have the expected license header"

2017-08-01 09:05 UTC, mmorhun commented
This error comes from master and has been fixed already.

2017-08-01 09:51 UTC, skabashnyuk approved these changes

2017-08-01 13:02 UTC, benoitf commented on dockerfiles/init/modules/keycloak/files/che/login/messages/messages_en.properties
> +product=Eclipse Che
how to we keep in sync this file with new keycloack releases ?
what are the changes with upstream project ?

should it be better to apply patches ? so we can track changes easily

2017-08-01 13:02 UTC, benoitf commented on dockerfiles/init/modules/keycloak/files/che/login/register.ftl
> +<#import "template.ftl" as layout>
maybe describe the changes with https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/register.ftl to better update with new upstream releases.

2017-08-02 08:04 UTC, mmorhun commented on dockerfiles/init/modules/keycloak/files/che/login/register.ftl
> +<#import "template.ftl" as layout>
I am not sure, whether I understood you correctly, but if you meant to roll our changes over base templates - I do not think that it is a good idea here. For example, they could redesign some pages, do we want to apply that? I think no.

2017-08-02 08:08 UTC, mmorhun commented on dockerfiles/init/modules/keycloak/files/che/login/messages/messages_en.properties
> +product=Eclipse Che
Do we need to replace our current messages with messages from new upstream releases?
I think we have our own Che theme and we shouldn't depend on changes in upstream themes.

2017-08-02 08:18 UTC, mshaposhnik approved these changes

2017-08-02 08:21 UTC, benoitf commented on dockerfiles/init/modules/keycloak/files/che/login/messages/messages_en.properties
> +product=Eclipse Che
I'm not asking to replace "our" messages with "upstream" messages.
but if you upgrade keycloak later, you may have new constants to update/change.
And how do we know what was the "customized" strings and the "upstream" strings.

Maybe that you've only changed product name and that's all but here we don't know what were the full changes.
By knowing the changes, then, it's easier to upgrade keycloak

2017-08-02 08:23 UTC, benoitf commented on dockerfiles/init/modules/keycloak/files/che/login/register.ftl
> +<#import "template.ftl" as layout>
@mmorhun how do you manage the upgrade of keycloak then ?
Let say they fix an issue in the base template. How the fix is then applied on our template ? it is not.

2017-08-02 08:27 UTC, skabashnyuk commented on dockerfiles/init/modules/keycloak/files/che/login/register.ftl
> +<#import "template.ftl" as layout>
@benoitf I think we don't know. If it will be an issue we will figure out.

2017-08-02 08:28 UTC, skabashnyuk commented on dockerfiles/init/modules/keycloak/files/che/login/messages/messages_en.properties
> +product=Eclipse Che
I think at this stage we don't need to dig that far. If and when it will be needed when we will work on that.

2017-08-02 08:30 UTC, benoitf commented on dockerfiles/init/modules/keycloak/files/che/login/register.ftl
> +<#import "template.ftl" as layout>
I prefer to deal with it now or the plan around it.

2017-08-02 08:30 UTC, benoitf commented on dockerfiles/init/modules/keycloak/files/che/login/messages/messages_en.properties
> +product=Eclipse Che
It will be needed for each update of the keycloak component. so the need will come sooner than never.

2017-08-02 08:31 UTC, benoitf requested changes
I don't see how we clearly manage the updates of the theme at each update of keycloak

2017-08-02 08:47 UTC, riuvshin commented
@benoitf current custom there is under puppet control, we generate it same way as from templates. If we will need to change theme we have to change source files here `dockerfiles/init/modules/keycloak/files` and puppet will regenerate it all and new updated theme will be mounted to keycloack image here https://github.com/eclipse/che/pull/5859/files#diff-d97c076dd428b95a4021cdc15fdebfcbR139

2017-08-02 08:53 UTC, benoitf commented
@riuvshin I'm not talking about how puppet is working.

But how we will ensure that bugfixes and new stuff (like new constant messages) in upstream(keycloak), when updating keycloak version here
https://github.com/eclipse/che/blob/f052d14bac5a470a2e32996d5c042cbb754875c4/dockerfiles/cli/images.template#L7

AFAIK it's error prone as ppl will only bump the version in the images.template (not checking what are the new contants, if there are some fixes in templates, etc)

2017-08-02 09:00 UTC, riuvshin commented
@benoitf ah :) well bumping version of key component is not something that happens like that. you can't just change version and commit it without tests of everything related to this. It is exactly same as we update swarm for example, it is one line change https://github.com/codenvy/codenvy/pull/2335/files with new version but to merge this we did huge amount of testing. 
It same way if you will upgrade some lib version in code. you upgrade and check is everything is working same way and if not you go and fix it because it is part of upgrade task to make sure that there is no regressions.

2017-08-02 09:03 UTC, mmorhun commented
@benoitf addressing you comments:
- If we'll upgrade Keycloak later it could use new constants, but we will use our own.
- We don't have to know what was the "customized" strings and the "upstream" strings. We just use our own from our own theme.
- We'll just update Keycloak. That's it. If they make significant changes in viewing area then describing changes (as you suggested) won't help.
- > Let say they fix an issue in the base template. How the fix is then applied on our template ?
  
  What kind of issue in template do you mean?

2017-08-02 09:04 UTC, benoitf commented
@riuvshin again, I'm talking about reporting changes from upstream and I was refering two usecases not covered by your scenario.
my usecases were:
1 - update of string constants.
   You can check that everything is working as you're telling. But let say there is an unexpected error at a time and that then it doesn't find the message as it is not in the constants file. I really doubt that "checking that all is working" will check all errors.

2 - backport of upstream fixes.
 again, you can check that all is working but if a fix was done upstream it will not be applied on your fork automatically.

2017-08-02 09:08 UTC, riuvshin commented
@benoitf I see your points but, how I don't see how we can do this in other way if no testing...
how we manage situations like that in other components in code?

2017-08-02 09:14 UTC, mmorhun commented
@benoitf again
1. > But let say there is an unexpected error at a time and that then it doesn't find the message as it is not in the constants file.

If I understood you correctly, this situation is impossible because we use our ouwn template with our own constants.

2. We change only theme, not engine! If they fix engine we'll get the fix. But what we have not touched is the theme html templates and constants.

2017-08-02 09:26 UTC, benoitf commented
> @benoitf again
> 
> But let say there is an unexpected error at a time and that then it doesn't find the message as it is not in the constants file.
> This situation is impossible because we use our ouwn template with our own constants.
> 

here
https://github.com/eclipse/che/blob/71e597727f056eceed8144e390e39625f42cc11e/dockerfiles/init/modules/keycloak/files/che/login/messages/messages_en.properties

are you really using all constants of this file ? AFAIK you've only added product constant on top of forking /opt/jboss/keycloak/themes/base/login/messages/messages_en.properties of the image.

shouldn't the file define only "product" constant ?
as "che" theme is based on "base" theme, all other messages should be inherited ?


> We change only theme, not engine! If they fix engine we'll get the fix. But what we have not touched is the theme html templates and constants.

You're forking a constant properties so fix could be on constant value or introducing new values.

2017-08-02 09:38 UTC, mmorhun commented
@benoitf 
> are you really using all constants of this file ? 
> shouldn't the file define only "product" constant ?

No, I use several constants.

Yes, I forked constant properties, what is the problem?
> fix could be on constant value

Again. Then it will change messages in our theme. Do we need that?
> could introducing new values

This won't affect us at all. We use our own templates and constants.

If you want a solution for all cases here, I am afraid, that it is just impossible.
From Keycloak docs (https://keycloak.gitbooks.io/documentation/server_development/topics/themes.html): 
> When extending a theme you can override individual resources (templates, stylesheets, etc.). If you decide to override HTML templates bear in mind that you may need to update your custom template when upgrading to a new release.

2017-08-02 09:41 UTC, benoitf commented
> > @benoitf
> > 
> > are you really using all constants of this file ?
> > shouldn't the file define only "product" constant ?
> > No, I use several constants.
> > 
> 
> Yes, I forked constant properties, what is the problem?
> 

It's the problem that I'm referring since my first comment.
We don't know what you've added, what you've changed in the forked file and how to manage upgrade.

2017-08-02 11:55 UTC, mmorhun commented
@benoitf I removed forked properties and left only new/redefined. But this could cause changes of  messages on Keycloak updates!

2017-08-02 12:05 UTC, benoitf approved these changes

2017-08-02 12:23 UTC, merged