Add implementation for 'Show message request' LS feature
eclipse/che pull request #5860
Opened 2017-08-01 07:33 UTC by evidolob

### What does this PR do?
Add implementation for 'Show message request' LS feature

### What issues does this PR fix or reference?
#1794

#### Changelog
Add implementation for [ShowMessage Request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#showmessage-request) Language Server protocol feature

#### Release Notes
Add implementation for [ShowMessage Request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#showmessage-request) Language Server protocol feature

2017-08-01 08:18 UTC, vparfonov commented on plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/window/dialog/MessageDialogFooter.ui.xml
> +</ui:UiBinder>
new line

2017-08-01 08:18 UTC, vparfonov commented on plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/window/dialog/MessageDialogPresenter.java
> +//    @Override
Do we need this comment code fragment?

2017-08-01 08:18 UTC, vparfonov commented on plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/window/dialog/MessageDialogPresenter.java
> +//        if (view.isOkButtonInFocus()) {
Do we need this comment code fragment?

2017-08-01 08:18 UTC, vparfonov commented on plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/window/dialog/MessageDialogViewImpl.ui.xml
> +</ui:UiBinder>
new line

2017-08-02 06:39 UTC, tolusha commented
Add `@author` annotation where it is absent.

2017-08-02 08:35 UTC, tsmaeder commented
@evidolob just wondering where the test launguage server is coming from?

2017-08-02 08:48 UTC, benoitf commented
@tsmaeder AFAIK https://github.com/eclipse/che-lib/pull/33

2017-08-16 11:14 UTC, skabashnyuk commented on agents/pom.xml
> +            <modules>
what are the purpose of this profile?

2017-08-16 11:14 UTC, skabashnyuk commented on agents/test-ls/src/main/java/org/eclipse/che/api/agent/TestLSAgent.java
> + *
too many spaces.

2017-08-16 11:14 UTC, skabashnyuk commented on agents/test-ls/src/main/java/org/eclipse/che/api/agent/TestLSModule.java
> + *
?

2017-08-16 11:14 UTC, skabashnyuk commented on core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/impl/JsonRpcModule.java
> +        return DtoFactory.getInstance().getGson();
very strange way to bind gson

2017-08-16 11:14 UTC, skabashnyuk commented on plugins/plugin-languageserver/che-plugin-test-ls/src/main/java/org/eclipse/che/plugin/test/ls/inject/TestLSModule.java
> + *
?

2017-08-16 11:14 UTC, skabashnyuk commented on wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/messager/ShowMessageJsonRpcTransmitter.java
> +//            result.completeExceptionally(new Exception("Can't send show message request, too meany clients"));
what is it?

2017-08-16 11:14 UTC, skabashnyuk commented on wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/registry/CheLanguageClient.java
> +                LOG.debug(message.getMessage());
default?

2017-08-16 11:14 UTC, skabashnyuk commented on wsagent/che-core-api-languageserver/src/test/java/org/eclipse/che/api/languageserver/LocalTestLSLauncher.java
> + *
?

2017-08-16 11:14 UTC, skabashnyuk commented on wsagent/che-core-api-languageserver/src/test/java/org/eclipse/che/api/languageserver/ShowMessageRequestTest.java
> +        Thread.sleep(1200);
what for?

2017-08-16 11:49 UTC, riuvshin commented
maven profile that affects final assembly is not acceptable solution here due to many reasons, for example how you would test tagged version if that profile is not default and should be included only for testing purposes. We have to rework this somehow to be able to enable / disable this without rebuild.

2017-08-16 14:24 UTC, dkulieshov approved these changes

2017-08-16 14:45 UTC, riuvshin requested changes
we should not have that profile, as we discussed that should be reworked to be configurable.

2017-08-22 09:30 UTC, vparfonov approved these changes

2017-08-22 09:44 UTC, riuvshin approved these changes
please do not merge this before release 5.17.0 is done.  And also please create an issue to use this test LS in QA tests

2017-09-04 06:32 UTC, tolusha approved these changes

2017-09-04 13:07 UTC, riuvshin commented
ci-build

2017-09-04 14:12 UTC, merged