CHE-5721: Importing java formatter for the project or workspace
eclipse/che pull request #6077
Opened 2017-08-23 13:12 UTC by svor

### What does this PR do?
Provides an ability to import eclipse java formatter. The formatter can be applied for the custom project or for the whole workspace.
![selection_012](https://user-images.githubusercontent.com/1271546/29617245-f40b09e6-881c-11e7-8041-c99be009c038.png)

Simple demo about how it works: https://youtu.be/oxi5OOvJsPQ

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5721

#### Changelog
Importing Eclipse formatter for the java classes

#### Release Notes
Importing Eclipse formatter for the java classes

2017-08-23 13:19 UTC, svor commented
ci-test

2017-08-23 13:58 UTC, evidolob approved these changes

2017-09-04 14:23 UTC, vparfonov approved these changes

2017-09-04 15:07 UTC, musienko-maxim commented
The stable part of selenium tests passed as expected

2017-09-04 15:08 UTC, musienko-maxim approved these changes

2017-09-05 08:09 UTC, skabashnyuk requested changes

2017-09-05 08:09 UTC, skabashnyuk commented on plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/jdt/internal/corext/format/CheCodeFormatterOptions.java
> +      parser.parse(new FileInputStream(file), parserXML);
Stream closing?

2017-09-05 08:42 UTC, svor commented on plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/jdt/internal/corext/format/CheCodeFormatterOptions.java
> +      parser.parse(new FileInputStream(file), parserXML);
fixed, thank you!

2017-09-05 08:43 UTC, svor commented
@slemeur please take a look

2017-09-05 09:05 UTC, skabashnyuk approved these changes

2017-09-08 13:19 UTC, merged

2017-09-08 14:06 UTC, slemeur commented
Wait wait wait - where is the release note and the documentation for that new feature?

2017-09-08 15:28 UTC, slemeur commented
@vparfonov ?