[WIP] : Integrating datasource extension
eclipse/che pull request #6099
Opened 2017-08-28 09:57 UTC by sudaraka94

### What does this PR do?
It ports the earlier version of datasource plugin to Che

2017-08-28 10:29 UTC, riuvshin requested changes

2017-08-28 10:29 UTC, riuvshin commented on pom.xml
> +                <version>6.0.6</version>
all deps versions must be defined in https://github.com/eclipse/che-dependencies/blob/master/pom.xml

2017-08-28 10:29 UTC, riuvshin commented on wsagent/che-datasource-api/pom.xml
> +        <version>5.16.0-SNAPSHOT</version>
version is outdated please set actual version from master branch.

2017-08-28 10:29 UTC, riuvshin commented on wsagent/che-datasource-ide/pom.xml
> +        <version>5.16.0-SNAPSHOT</version>
version is outdated please set actual version from master branch.

2017-08-28 10:29 UTC, riuvshin commented on wsagent/che-datasource-shared/pom.xml
> +        <version>5.16.0-SNAPSHOT</version>
version is outdated please set actual version from master branch.

2017-08-28 10:29 UTC, riuvshin commented on wsagent/che-datasource-ssl-socket-factory/pom.xml
> +        <version>5.16.0-SNAPSHOT</version>
version is outdated please set actual version from master branch.

2017-08-28 10:30 UTC, riuvshin commented
ci-build

2017-08-29 08:40 UTC, skabashnyuk commented
@sudaraka94 is this PR ready for review? Shall we start commenting?

2017-08-29 08:41 UTC, skabashnyuk commented
FYI. mysql driver has uncompatible license and can't be added to Eclipse Che.

2017-08-29 08:59 UTC, sudaraka94 commented
@skabashnyuk I think I will correct the issues mentioned by @riuvshin first. And then open the PR again for review

2017-08-29 09:00 UTC, closed without merging

2017-09-04 09:52 UTC, sunix commented
as discussed, this PR is not ready to be merged