workspace agent : avoid scan of WEB-INF/lib jars for classes
eclipse/che pull request #6186
Opened 2017-09-07 15:35 UTC by benoitf

### What does this PR do?
Define the list of modules to load by the workspace agent and disable the scan of the jar files.

Currently there is the flag metadata-complete=true in the web.xml file but jars are still scanned due to ServletContainerInitializer usage in che.

By using that approach, we avoid the scan and boot time is faster.

### What issues does this PR fix or reference?
#6169 

#### Changelog
workspace agent : avoid scan of WEB-INF/lib jars for classes

#### Release Notes
N/A

#### Docs PR
N/A

Change-Id: I8e33a2007a41482df7152d2bf875505053840e8a
Signed-off-by: Florent BENOIT <fbenoit@redhat.com>

2017-09-08 06:06 UTC, skabashnyuk commented
I think this is a step back in plugin development experience. Instead of "put your artifact in claspass aka declare in pom.xml" developer has to do some coding. All our archetypes, custom assemblies are based on this. All of that will be broken after this PR.

One of the alternatives is to prescan @Dynamodules on build time and put results in some index file and reuse it in CheButstrup in runtime. 

But let's step back and talk about the real numbers of seconds what we want to improve. At what cost? Does it worth it?

2017-09-08 08:29 UTC, benoitf commented
@skabashnyuk 

>  Instead of "put your artifact in claspass aka declare in pom.xml" developer has to do some coding. All our archetypes, custom assemblies are based on this. All of that will be broken after this PR.

AFAIK none of them will be broken. I studied it before and custom assemblies or archetype are using `che-wsagent-core` module. I only update the 'che wsagent' assembly so it impacts only 'che' but benefits to all Eclipse Che end-users.

> One of the alternatives is to prescan @dynamodules on build time and put results in some index file and reuse it in CheButstrup in runtime.
Yes I wanted to create this issue as well that so it can benefits to 'ALL' custom assemblies, archetypes, etc. But it's another item.

> But let's step back and talk about the real numbers of seconds what we want to improve. At what cost? Does it worth it?
For sure it worth it. It's how we optimize server side components. I don't see why Che would not be optimized as well.

2017-09-08 08:38 UTC, garagatyi commented
I think that kind of issue should be the enhancement, not the bug.
Listing of all the plugins modules contradicts pluggability which you were discussing on f2f. Can you elaborate on why you decided to even decrease pluggability in this PR?

2017-09-08 08:49 UTC, benoitf commented
@garagatyi 

> Listing of all the plugins modules contradicts pluggability which you were discussing on f2f. Can you elaborate on why you decided to even decrease pluggability in this PR?

It's not contradicting pluggability. As you need to rebuild the assembly currently it does not reduce it.
At F2F I was talking about "runtime pluggability" and it is not linked to that part as well as in my demo there was no scan of the classes as well to bring a plugin at runtime.

2017-09-08 08:51 UTC, benoitf commented
Also I wouldn't mix "developer experience" with "production experience" as usually there is a "developer mode" and "production mode"

2017-09-08 09:10 UTC, skabashnyuk requested changes
-1 I don't believe for now that win of a couple of seconds on ws start are worth of a headache with a support of Eclipse Che assembly and all existing and future assemblies based on Eclipse Che Full assembly. changing off the idea of @Dynamodule approach. 

Can this Module be generated like we doing with gwt.xml for instance? Have you consider other options that don't require Java code changes when you're adding a new plugin.

2017-09-08 09:21 UTC, benoitf commented
@skabashnyuk did you read what I've written.
it has **NO** impacts on custom assemblies and archetype.

2017-09-08 09:27 UTC, benoitf commented
> Can this Module be generated like we doing with gwt.xml for instance? Have you consider other options that don't require Java code changes when you're adding a new plugin.

yes it can but this is step 2 as described in my previous comments.
But step 2 is not mandatory for having immediate performance improvements.

2017-09-08 09:29 UTC, skabashnyuk commented
As an assembly maintainer, I have **opposite** opinion. And think that we should also consider some alternatives. I agree that jar scanning is the place where we can optimize agent performance but I don't agree with the way how it was made.

2017-09-08 09:31 UTC, benoitf commented
if you agree that we can optimize, then why it was not optimized ? or why it was not raised when you've done profiling on https://github.com/codenvy/codenvy/issues/1466 ?

2017-09-08 09:33 UTC, garagatyi commented
@benoitf @skabashnyuk all of us are maintainers in different parts of the system. Can we decrease the temperature in the room a bit?
@skabashnyuk can you elaborate on how this change will influence custom assemblies and archetypes?

2017-09-08 09:38 UTC, skabashnyuk commented
>if you agree that we can optimize, then why it was not optimized ? or why it was not raised when you've done profiling on codenvy/codenvy#1466 ?

Too complicated to solve  ~2 seconds on OSX, on Linux desktop, it's even less when what.  We have other different places to improve where developers suppose to spent much more when 2 seconds. For instance editor, language servers. 

>@skabashnyuk can you elaborate on how this change will influence custom assemblies and archetypes?

It requires additional steps to add the plugin.

2017-09-08 09:39 UTC, benoitf commented
>> @skabashnyuk

> can you elaborate on how this change will influence custom assemblies and archetypes?
>It requires additional steps to add the plugin.

I disagree, custom assemblies and archetypes have nothing to do after this PR

2017-09-08 09:40 UTC, garagatyi commented
> It requires additional steps to add the plugin.

So, basically, it will break current archetypes, right?

2017-09-08 09:41 UTC, benoitf commented
@garagatyi not at all as archetypes are based on ws-agent-core (and this one will scan the modules)

2017-09-08 09:47 UTC, skabashnyuk commented
>>@garagatyi not at all as archetypes are based on ws-agent-core (and this one will scan the modules)

And that exactly the problem. Your solution is fixing only this Eclipse Che Full assembly. All other
like archetypes don't get this boost or like Codenvy, or Codenvy OnPrem will get a headache to don't forget to put plugins in two places. If we start solving this performance problem let's solve it once and for all.

2017-09-08 09:49 UTC, benoitf commented
it's step 2 of the improvement to make it to the others.
Also you're shifting your initial remark.
At first you said it will be break all the assemblies and I was saying it will not, now you're saying that the boost should be applied for all assemblies

2017-09-08 09:55 UTC, skabashnyuk commented
>it's step 2 of the improvement to make it to the others.

I disagree. It means that it will be put on a long shelf and some one will have a headache

>Also you're shifting your initial remark.
>At first you said it will break all the assemblies and I was saying it will not, now you're saying >that the boost should be applied to all assemblies

No. It's just because I was wrong and you are right that Eclipse Che archetype will be no be broken.  They will work as it's now.

2017-09-08 10:14 UTC, slemeur commented
This change is going to highly impact the end-user experience, in a positive way. That's only what we should keep in mind. 

Maybe it will create

2017-09-08 10:17 UTC, sunix commented
Hi there, we are trying to speedup workspace startup which is very slow in openshift.io.
If there are any startup speedup improvements to make there and there, we should consider them.
I saw @benoitf 's demo and it seems that it's not about 2 secs ... but 40% of an overall time to start a workspace agent which is really awesome IMO.
I don't think it will change the developer experience that much and it won't be that hard to maintain, compared to what we will gain in performance improvement.

2017-09-08 10:43 UTC, skabashnyuk commented
> demo and it seems that it's not about 2 secs ... but 40% 

Ok 40%.


@sunix  I totally support the idea to improve performance. But let's take some time to make it general and without changing experience. 
What if WsAgentModuleList.java will be generated like many things in ide war https://github.com/eclipse/che/blob/master/assembly/assembly-ide-war/pom.xml#L268-L325

2017-09-08 11:36 UTC, benoitf commented
I would say that we should do more incremental steps instead of trying to apply it everywhere at once. (BTW this approach often fails)

short term : use it in Che and see how it behaves
mid term: introduce generation of the DynaModule list and use it in che then in codenvy.
mid term++: apply it everywhere (custom assemblies, archetype)

so it's better to see how it behaves and to see if there are impacts.

2017-09-08 12:07 UTC, skabashnyuk commented
-1 to experiment here.
if it's urgently needed on production lets experiment on production. https://github.com/redhat-developer/rh-che/tree/master/builds/fabric8-che/assembly/assembly-wsagent-war

Don't see a problem to start from ```mid term``` or ```mid term++``` in Eclipse Che from the beginning. This is not kind of problem that some one will die without it.

2017-09-08 12:10 UTC, benoitf commented
@skabashnyuk because from what I've seen, it has always failed to apply it everywhere at once.

2017-09-08 12:20 UTC, benoitf commented
@skabashnyuk also please clarify your -1.

It's not experimenting. It's optimizing Che first, and then propagate the change slightly to the other assemblies and the archetypes.

Because currently you're -1 is being against gaining seconds when booting up the Che workspace agent. (which can be 40% of the overall time)

2017-09-08 12:25 UTC, skabashnyuk commented
-1 
1. duplicate plugin declaration in pom.xml + java file.
2. To make it for Eclipse Che Full assembly only.

Proposal
1. Generate java file with all modules like we doing in https://github.com/eclipse/che/blob/master/assembly/assembly-ide-war/pom.xml#L268-L325
2. Reuse this approach in all assemblies based on Eclipse Che.
3. Turn off scanning annotation for all Eclipse Che web applications. 

> (which can be 40% of the overall time)

Just assumption. My best guess it's 2-5 sec on Mac, Linux can be completely different.

2017-09-08 12:31 UTC, benoitf commented
I never said that it will be only for Che forever, it's the principle of using iterative development.
Things are not black and white, there is a pattern that can bring the feature for everyone with small incremental steps.
It's strange to refuse step 1 and only wanting the whole steps at once.

Also when you're saying duplicate plugin declaration in pom.xml + java file.
we're already duplicating many stuff for all Guice modules that are not plugins so this argument is not really true.

2017-09-08 12:34 UTC, skabashnyuk commented
Ok. Don't agree that this is technically possible to generate WsAgentModuleList.java during build phase?

2017-09-08 12:35 UTC, benoitf commented
I never disagree and I said since my first reply that it's part of the step 2

2017-09-08 12:46 UTC, skabashnyuk commented
ok. I'm glad that we have the same view 😄  We both agree that this is just technical exercise. 
And since we both wrote some generators and knows that it's not what hard work. 
What if we collaborate and goes directly to the level 2 with a single step, as a team. You will write generator and adapt maven build, I'll handle archetypes, Codenvy, and all derivative assemblies.

2017-09-08 12:49 UTC, benoitf commented
ok let's do that.

2017-09-08 13:10 UTC, gorkem commented
Wow, What a read to start my day with. I feel like you guys should be hugging 🤗  though

2017-09-13 05:34 UTC, skabashnyuk commented
Comment from https://github.com/eclipse/che-dependencies/pull/55#issuecomment-328962472.
Let's sync our vision for WsAgentModuleList.java generation.
I thought plan would be:
In ws-agent(ws-master) war we have a couple of phases.
1. Before compile phase take a look on all dependencies with reflection tool, filter all classes annotated with ```@Dynamodule``` annotation.
2. Generate from template WsAgentModuleList.java and put it to   ```target/generated```
3. Add ```target/generated``` as maven source folder and compile it.
4. Add   WsAgentModuleList.class to the  tomcat annotation scanning list.

WDYT?

2017-09-13 05:56 UTC, benoitf commented
@skabashnyuk as I said in the che-dependencies repository

reflection tool is not a good candidate : it loads the classes . At compile time we may not have all required dependencies (and it is slow) but it's more about the process that there is a flaw.

To be the faster, we need to scan "ALL" the classes even those that are part of the war itself. So it must be at `process-classes`lifecycle to be sure that we scan all the classes.

so the plugin is doing at `process-classes` lifecycle
- scan all the classes
- generate the class providing the `getModules()` list.

and in web.xml absolute-ordering element is used and in context.xml we skip all the jars.

2017-09-13 06:04 UTC, skabashnyuk commented
Can we add ALL classes of war to scan annotation list? Or may define a list of it, for example, put it in some folder, etc? So we can move to ```generate-sources``` phase. That will allow us not to directly work with byte code generation that is quite complicated itself.

2017-09-13 06:07 UTC, benoitf commented
@skabashnyuk no, fully disabling scanning disable also the SCI components so we don't scan anything anymore at all.
BTW the plugin is ready and fully working.

2017-09-13 06:09 UTC, skabashnyuk commented
ok. just worried that it would be not trivial.

2017-09-13 08:17 UTC, benoitf commented
FYI here is the updated PR.
I've rewritten it including the description and updating code.

2017-09-13 10:03 UTC, gazarenkov commented
+1 for this.
I like decoupling "scanning" DynaModules from SCI in general (even out of startup time scope) and the ability to plug other mechanism via Service loading.

What I miss in discussion around performance though is numbers analyzing the overall start time, what and how much impacting on it in general (Docker, image, container, agent etc) and what we gain in percentage in each (this in particular) case. It would give us engineering view of problem.
@benoitf can you make this profiling/analysis as a separate task?

2017-09-13 10:05 UTC, benoitf commented
@gazarenkov 
Some details are there
https://github.com/eclipse/che/issues/6169#issuecomment-328064479

2017-09-13 11:55 UTC, skabashnyuk approved these changes

2017-09-13 15:34 UTC, benoitf commented
@skabashnyuk do you will handle codenvy and archetype inclusion  ?
Because right now if I merge this PR I think it will break codenvy as it relies on the ws-agent war of che
https://github.com/codenvy/codenvy/blob/master/assembly/assembly-wsagent-war/pom.xml#L56

2017-09-22 08:22 UTC, mkuznyetsov commented on core/che-core-dynamodule-maven-plugin/src/test/projects/project/pom.xml
> +</project>
new line?

2017-09-22 08:28 UTC, benoitf commented on core/che-core-dynamodule-maven-plugin/src/test/projects/project/pom.xml
> +</project>
fixed

2017-09-22 08:53 UTC, benoitf commented
I've rebased to current master (as it was providing 5.18.0-SNAPSHOT artifact)

2017-10-04 07:52 UTC, mkuznyetsov commented
If assembly uses another WAR as overlay, plugin should scan for dynamodules in it. Otherwise we would need to use it's `classes` artifacts

2017-10-20 14:13 UTC, mkuznyetsov commented
I've used Set to exclude generation of duplicating dynamodules

2017-10-20 14:13 UTC, mkuznyetsov approved these changes

2017-11-01 09:59 UTC, ashumilova approved these changes

2017-11-01 10:05 UTC, merged