Spi qa
eclipse/che pull request #6199
Opened 2017-09-08 14:44 UTC by Ohrimenko1988

### What does this PR do?
fixed selenium tests

### What issues does this PR fix or reference?

#### Changelog

#### Release Notes

#### Docs PR

2017-09-08 17:39 UTC, garagatyi requested changes
Please rewrite commits to have sensible descriptions.
Also, please, modify the description of this PR to match Che PRs template.

2017-09-11 06:18 UTC, tolusha approved these changes

2017-09-11 06:36 UTC, skabashnyuk commented on selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkspaceFromOfficialUbuntuImageStartTest.java
> +    //toastLoader.waitExpectedTextInToastLoader("Starting workspace runtime.", 200);
remove if not needed

2017-09-11 06:55 UTC, artaleks9 commented on selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/WorkspaceFromOfficialUbuntuImageStartTest.java
> +    //toastLoader.waitExpectedTextInToastLoader("Starting workspace runtime.", 200);
I have done it

2017-09-11 09:23 UTC, vparfonov approved these changes

2017-09-11 09:54 UTC, garagatyi approved these changes

2017-09-11 09:55 UTC, merged