CHE-5925: Add hotkeys to the most usable git actions
eclipse/che pull request #6247
Opened 2017-09-13 08:20 UTC by mmorhun

### What does this PR do?
Adds shortcuts for the following git actions:
- commit
- push
- pull
- manage branches dialog

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5925

#### Changelog
Added hotkeys to the most frequently used git actions.

#### Release Notes

#### Docs PR

2017-09-13 08:36 UTC, vinokurig approved these changes

2017-09-13 08:53 UTC, vparfonov approved these changes

2017-09-14 08:13 UTC, slemeur approved these changes

2017-09-14 10:59 UTC, tolusha requested changes
Make sure KeyBindingsTest passes.

2017-09-15 09:55 UTC, tolusha approved these changes

2017-09-15 09:56 UTC, mmorhun commented
ci-build

2017-09-15 12:28 UTC, merged