Fix locators in NavigateToFile page object
eclipse/che pull request #6266
Opened 2017-09-14 08:06 UTC by SkorikSergey

### What does this PR do?
Change locators in NavigateToFile page object which checks popup of the **Navigate To File** feature.

2017-09-14 08:34 UTC, tolusha requested changes
Add debug id to the all items and use them instead of xpaths

2017-09-14 11:25 UTC, SkorikSergey commented
All changed locators are used for searching dynamically created web elements .

2017-09-14 11:55 UTC, tolusha commented
This is a suggestion panel. You have to investigate corresponding source code to make assumption.

https://github.com/eclipse/che/blob/3cdf3b6eb713ba8a02fec8b3d148c4ef4363c421/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/navigation/NavigateToFileViewImpl.ui.xml#L74

2017-09-21 07:03 UTC, tolusha commented on selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/NavigateToFile.java
> +    String FILE_NAME_FIELD = "gwt-debug-navigateToFile-fileName";
The name of the constant should reflect its value.

2017-09-21 07:03 UTC, tolusha commented on selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/NavigateToFile.java
> +    String FILE_NAME_POPUP = "gwt-debug-navigateToFile-suggestionPanel";
The name of the constant should reflect its value.

2017-09-21 08:39 UTC, tolusha approved these changes

2017-09-21 08:42 UTC, merged