Add a che.env/che.properties property to skip docker unused containers and networks cleanup
eclipse/che pull request #6485
Opened 2017-09-28 13:47 UTC by sunix

[![Review](http://localhost:8080/factory/resources/factory-review.svg)](http://localhost:8080/f?id=factorycut9qcc8k66snadu)

### What does this PR do?
Add a che.env che.properties property to skip docker unused containers and networks cleanup. Can be useful in use cases where we want to run several che servers without having their workspaces being killed.

    CHE_DOCKER_CLEANUP__SKIP=true

### What issues does this PR fix or reference?

2017-09-28 14:41 UTC, benoitf approved these changes
I don't know but maybe it's better to have cleanup option with default to true instead of having a SKIP/false

2017-09-28 14:57 UTC, sunix commented
@benoitf yes that was a 2 days thinking from my side :)
I've chosen to use `skip` because performing the cleanup would be the default behaviour in most of the case. But I'm open if you think we should have a cleanup option.

2017-09-28 15:43 UTC, benoitf commented
@sunix I let comment the other reviewers ;-)

2017-09-29 00:17 UTC, l0rd approved these changes
LGTM but agree with @benoitf. The current name of the property recalls me `keycloak.disable=false`

2017-09-29 06:39 UTC, garagatyi requested changes
After a brief discussion with @skabashnyuk, I recalled that  you can disable execution by setting 
`che.docker.cleanup_period_min=-1`
So, I think we should go in that direction instead of adding new code which makes logic more complex.

2017-09-29 06:39 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/cleaner/DockerAbandonedResourcesCleaner.java
> +  @Named("che.docker.cleanup_skip")
+1 to @benoitf suggestion about the name of this property

2017-09-29 06:39 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/cleaner/DockerAbandonedResourcesCleaner.java
> +  @Inject(optional = true)
Can you elaborate on why have you decided to make it optional? 
I tend to avoid optional injection if possible and won't need workarounds.

2017-09-29 06:39 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/cleaner/DockerAbandonedResourcesCleaner.java
> +  private String skipCleaningProperty;
You can inject it as boolean directly to avoid manual parsing

2017-09-29 06:39 UTC, garagatyi commented on plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/cleaner/DockerAbandonedResourcesCleaner.java
> +      LOG.info("Skipping che unused containers and network cleanup ...");
FYI this code prevents the execution of code of cleanups but doesn't prevent spawning jobs periodically.

2017-09-29 08:57 UTC, sunix commented
@garagatyi Thanks, this is fine for me, I will test this -1 option and create a PR to update the description of the property.in che.properties/che.env.

2017-09-29 09:59 UTC, sunix commented
@garagatyi ok it seems to work fine with -1. I'm closing this one.

2017-09-29 10:02 UTC, sunix commented
Actually I have some errors in the logs with -1. So i'm going to investigate.

```
2017-09-29 09:57:20,169[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[.[/wsmaster] 4733]      - Exception sending context initialized event to listener instance of class org.eclipse.che.inject.CheBootstrap
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Error notifying InjectionListener org.eclipse.che.inject.lifecycle.ScheduleInjectionListener@3e480a96 of org.eclipse.che.plugin.docker.machine.cleaner.DockerAbandonedResourcesCleaner.
 Reason: java.lang.IllegalArgumentException
  at org.eclipse.che.plugin.docker.machine.DockerMachineModule.configure(DockerMachineModule.java:33) (via modules: org.eclipse.che.api.deploy.WsMasterModule -> org.eclipse.che.plugin.docker.machine.local.LocalDockerModule -> org.eclipse.che.plugin.docker.machine.DockerMachineModule)
  while locating org.eclipse.che.plugin.docker.machine.cleaner.DockerAbandonedResourcesCleaner
1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:565)
	at org.eclipse.che.commons.schedule.executor.ThreadPullLauncher.scheduleAtFixedRate(ThreadPullLauncher.java:102)
	at org.eclipse.che.inject.lifecycle.ScheduleInjectionListener.launch(ScheduleInjectionListener.java:126)
	at org.eclipse.che.inject.lifecycle.ScheduleInjectionListener.launch(ScheduleInjectionListener.java:147)
	at org.eclipse.che.inject.lifecycle.ScheduleInjectionListener.afterInjection(ScheduleInjectionListener.java:159)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 18 common frames omitted
2017-09-29 09:57:20,328[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[.[/wsmaster] 4733]      - Exception sending context initialized event to listener instance of class org.eclipse.che.everrest.ServerContainerInitializeListener
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at org.everrest.core.impl.RequestDispatcher.<init>(RequestDispatcher.java:84)
	at org.eclipse.che.everrest.ServerContainerInitializeListener.getEverrestProcessor(ServerContainerInitializeListener.java:195)
	at org.eclipse.che.everrest.ServerContainerInitializeListener.createWsServerEndpointConfig(ServerContainerInitializeListener.java:137)
	at org.eclipse.che.everrest.ServerContainerInitializeListener.contextInitialized(ServerContainerInitializeListener.java:96)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617
```

2017-09-29 10:08 UTC, skabashnyuk commented
```-1``` is not implemented feature(actually nice one). That is why it fails.
I think this check (time >0) should be implemented somewhere here https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-schedule/src/main/java/org/eclipse/che/commons/schedule/executor/ThreadPullLauncher.java
WDYT?

2017-09-29 13:46 UTC, sunix commented
@skabashnyuk yes I've started to implement that in https://github.com/eclipse/che/pull/6505, could you comment on this one and I will probably apply the same for @ScheduleDelay

2017-09-29 16:16 UTC, sunix commented
Replace this one with https://github.com/eclipse/che/pull/6505

2017-09-29 16:16 UTC, closed without merging