Fix CheckRestoringOfSplitEditor selenium test
eclipse/che pull request #6677
Opened 2017-10-11 11:40 UTC by SkorikSergey

We need fix **CheckRestoringOfSplitEditor** selenium test:
- change expected text in split-editor-restore-exp-text.txt resource file;
- change name of class to **CheckRestoringOfSplitEditorTest**;
- add checking that workspace restored properly after refresh;
- code cleanup.

2017-10-12 07:02 UTC, Ohrimenko1988 approved these changes

2017-10-13 07:26 UTC, tolusha requested changes
Rework the names of the variables.

2017-10-18 13:17 UTC, Ohrimenko1988 approved these changes

2017-10-20 10:57 UTC, tolusha commented on selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringOfSplitEditorTest.java
> +public class CheckRestoringOfSplitEditorTest {
Get rid of `of` in the class name.

2017-10-20 10:58 UTC, tolusha commented on selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/editor/CheckRestoringOfSplitEditorTest.java
> +      NameGenerator.generate(CheckRestoringOfSplitEditorTest.class.getSimpleName(), 4);
How many times I should say to use 
`NameGenerator.generate("project", 4);`
for project names?

2017-10-20 11:26 UTC, tolusha approved these changes

2017-10-20 12:29 UTC, merged