Add method 'getUserPublicEmail' to TestGitHubServiceClient
eclipse/che pull request #6865
Opened 2017-10-20 09:46 UTC by Ohrimenko1988

### What does this PR do?
Add ability to get github user public email by using github api .

### What issues does this PR fix or reference?
Issue https://github.com/eclipse/che/issues/6858

#### Release Notes

#### Docs PR

2017-10-20 10:49 UTC, dmytro-ndp commented on selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubServiceClient.java
> +        .collect(Collectors.joining());
What is the propose of joining() here? Did you try to test this method with github account with several public emails?

2017-10-20 12:17 UTC, Ohrimenko1988 commented
[INFO] Che Core :: IDE :: App ............................. FAILURE
...
Found 4 non-complying files

I think this is not this PR fault

2017-10-20 13:02 UTC, dmytro-ndp commented
It's a PR fault so as there are changes in master which should be merged in branch.

2017-10-20 13:07 UTC, dmytro-ndp requested changes
https://api.github.com/user/public_emails can return several emails: https://developer.github.com/v3/users/emails/#list-public-email-addresses-for-a-user
Please, take it into account.

2017-10-23 09:24 UTC, dmytro-ndp commented on selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubServiceClient.java
> +        .collect(Collectors.joining());
I would recommend to get first email from the map instead of joining all of them as a less error-prone variant.

2017-10-24 09:31 UTC, dmytro-ndp approved these changes

2017-10-24 09:35 UTC, merged