CHE-7881: Implement organize import action with advantage of jdt.ls
eclipse/che pull request #7902
Opened 2017-12-15 15:38 UTC by tolusha

Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

### What does this PR do?
Implement organize import action with advantage of jdt.ls

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/7881

#### Release Notes

#### Docs PR

2017-12-18 15:03 UTC, svor commented on plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaLanguageServerExtensionService.java
> +  }
I think you can simplify this method via replacing 
```
public WorkspaceEdit organizeImports(String path) {
      return doGetOne(Commands.ORGANIZE_IMPORTS_COMMAND, prefixURI(path), WorkspaceEdit.class);
}
```

2017-12-18 15:04 UTC, svor approved these changes

2017-12-19 08:27 UTC, mmorhun approved these changes

2017-12-21 10:00 UTC, tsmaeder requested changes
Just one more thing...

2017-12-21 12:00 UTC, tolusha commented
Fixed ;)

2017-12-22 08:14 UTC, tolusha commented
Fixed

2017-12-26 09:32 UTC, merged