CHE-7577 CHE6 UI refinements
eclipse/che pull request #8329
Opened 2018-01-17 12:15 UTC by vitaliy-guliy

### What does this PR do?
Improves UI widgets for dark theme.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/7577

![preferences](https://user-images.githubusercontent.com/1655894/35042294-b95ce5ac-fb90-11e7-835b-7a2d6f41ba78.png)

![revert commit](https://user-images.githubusercontent.com/1655894/35042297-bc3ad2d4-fb90-11e7-82c3-3b4b7f0386ee.png)

![search](https://user-images.githubusercontent.com/1655894/35042299-beac65b4-fb90-11e7-9c47-a2c16679a813.png)

#### Release Notes

#### Docs PR

2018-01-17 12:49 UTC, vzhukovs requested changes

2018-01-17 12:49 UTC, vzhukovskii commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/json/ImportFromConfigViewImpl.java
> +    buttonImport.addStyleName(resources.windowCss().primaryButton());
Take a look on other three methods `createButton` in Window class, there is another method which provide _Primary_ style and custom alignment.

2018-01-17 12:49 UTC, vzhukovskii commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/resources/selector/SelectPathViewImpl.java
> +    submitBtn.addStyleName(resources.windowCss().primaryButton());
Take a look on above comment

2018-01-17 12:49 UTC, vzhukovskii commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/upload/file/UploadFileViewImpl.java
> +    btnUpload.addStyleName(resources.windowCss().primaryButton());
Take a look on above comment

2018-01-17 12:49 UTC, vzhukovskii commented on ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/upload/folder/UploadFolderFromZipViewImpl.java
> +    btnUpload.addStyleName(resources.windowCss().primaryButton());
Take a look on above comment

2018-01-17 12:49 UTC, vzhukovskii commented on ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/cellview/cellTable.css
> +    /*border: 1px solid cellEvenRow;*/
Remove commented code

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/checkout/CheckoutReferenceViewImpl.java
> +    btnCheckout.addStyleName(resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/CompareViewImpl.java
> +    btnSaveChanges.addStyleName(resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/fetch/FetchViewImpl.java
> +    btnFetch.addStyleName(super.resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/history/HistoryViewImpl.java
> +    btnCompare.addStyleName(resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/merge/MergeViewImpl.java
> +    btnMerge.addStyleName(super.resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/pull/PullViewImpl.java
> +    btnPull.addStyleName(super.resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/push/PushToRemoteViewImpl.java
> +    btnPush.addStyleName(super.resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/remote/RemoteViewImpl.java
> +    btnAdd.addStyleName(super.resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/reset/commit/ResetToCommitViewImpl.java
> +    btnReset.addStyleName(super.resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/reset/files/ResetFilesViewImpl.java
> +    btnReset.addStyleName(super.resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/revert/RevertCommitViewImpl.java
> +    btnRevert.addStyleName(resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 12:49 UTC, vzhukovskii commented on plugins/plugin-help/che-plugin-help-ext-client/src/main/java/org/eclipse/che/ide/ext/help/client/about/AboutViewImpl.java
> +    btnOk.addStyleName(resources.windowCss().primaryButton());
Take a look on above comments

2018-01-17 13:31 UTC, vitaliy-guliy commented on ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/cellview/cellTable.css
> +    /*border: 1px solid cellEvenRow;*/
Done

2018-01-17 13:31 UTC, vitaliy-guliy commented
ci-build

2018-01-17 13:31 UTC, vitaliy-guliy commented
ci-test

2018-01-17 13:31 UTC, vzhukovs approved these changes

2018-01-17 13:52 UTC, vitaliy-guliy commented
ci-build

2018-01-17 15:34 UTC, vitaliy-guliy commented
ci-build

2018-01-18 09:34 UTC, vitaliy-guliy commented
ci-test

2018-01-18 13:03 UTC, ashumilova approved these changes

2018-01-18 13:40 UTC, vparfonov approved these changes

2018-01-19 14:03 UTC, SkorikSergey approved these changes

2018-01-19 14:05 UTC, merged