Remove "source" field from stack object
eclipse/che pull request #8407
Opened 2018-01-22 16:46 UTC by mkuznyetsov

### What does this PR do?
Remove "source" from Stack objects, as for it being redundant

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/7722

2018-01-23 08:55 UTC, skabashnyuk approved these changes

2018-01-23 09:04 UTC, garagatyi approved these changes

2018-01-23 09:20 UTC, riuvshin approved these changes

2018-01-23 12:14 UTC, mkuznyetsov commented
ci-test

2018-01-24 12:15 UTC, ashumilova approved these changes

2018-01-24 12:29 UTC, ashumilova requested changes
Should be changed here as well:
1. https://github.com/eclipse/che/blob/che-7722/dashboard/src/app/stacks/stack-details/stack-validation.service.ts#L29
2. https://github.com/eclipse/che/blob/che-7722/dashboard/src/components/typings/che.d.ts#L267
3. Are test fails on stacks (`Expected condition failed: waiting for visibility of element located by By.xpath: //div[@data-stack-id='java-default']`) expected?

2018-01-24 14:10 UTC, mkuznyetsov commented
ci-test

2018-01-25 09:57 UTC, ashumilova approved these changes

2018-01-25 13:21 UTC, musienko-maxim commented
After selenium cycle new bugs are not found

2018-01-25 13:53 UTC, merged