Custom socket provider and java language server in sidecar
eclipse/che pull request #9616
Opened 2018-05-04 13:57 UTC by JPinkney

Signed-off-by: jpinkney <josh.pinkney@mail.utoronto.ca>

### What does this PR do?
Adds the ability to run jdt.ls in a sidecar and allows custom socket launchers.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/8874

2018-05-07 05:55 UTC, eivantsov commented on wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/remote/CustomSocketLsLauncherProvider.java
> + * Copyright (c) 2012-2018 Red Hat, Inc.
@JPinkney do we really need this? Maybe I am missing smth, but reading ws config and grabbing servers of a special type has been already implemented by @dkuleshov https://github.com/eclipse/che/blob/master/wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/remote/SocketLsLauncherProvider.java Can't we just reuse it?

2018-05-07 06:11 UTC, skabashnyuk commented on multiuser/api/che-multiuser-api-workspace-activity/pom.xml
> +            <artifactId>che-multiuser-api-resource</artifactId>
why do you need this artifact?

2018-05-07 06:11 UTC, skabashnyuk commented on plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaSocketLanguageServerLauncher.java
> +
javadoc

2018-05-07 06:11 UTC, skabashnyuk commented on wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/remote/SocketLanguageServerLauncher.java
> +
javadoc

2018-05-07 06:11 UTC, skabashnyuk commented on wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/remote/SocketLanguageServerLauncher.java
> +      Socket socket = new Socket(host, port);
are you going to close this Socket on ```@PreDestroy```?

2018-05-08 07:11 UTC, eivantsov commented
@JPinkney can you write a short how-to with what one can do to test this PR? I have an image with jdt.ls starting in tcp mode.

Also, why does the server need to have attributes - `serverAttributes.get("custom_launcher").equals("true"))`? Right now, it is enought to have `"type": "lsp"` in server attributes in order for this server to be counted as a remote language server.

2018-05-08 10:59 UTC, tolusha commented on wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/remote/SocketLsLauncherProvider.java
> +              && serverAttributes.get("custom_launcher").equals("true")) {
It is better to use here `equalsIgnoreCase`

2018-05-08 11:49 UTC, tolusha commented on plugins/plugin-java/che-plugin-java-server/src/main/java/org/eclipse/che/plugin/java/languageserver/JavaSocketLanguageServerLauncher.java
> +      Socket socket = new Socket(host, port);
Should we close this socket later?

2018-05-08 11:50 UTC, tolusha commented on ide/che-core-ide-stacks/src/main/resources/stacks.json
> +]
Don't forget to add empty line.

2018-05-08 19:17 UTC, JPinkney commented
To test the instructions are almost the same as the regular sidecar instructions with a few exceptions.

    1. Change the custom recipe to include che-jdt-ls/java-ls as the image (or your own image)
    2. Set the id in the workspace config as "org.eclipse.che.plugin.java.languageserver",  port as 5555, and languageID as java
    3. Mount /home/user/jdtls as a volume for the java-machine-ls

2018-05-08 19:25 UTC, eivantsov commented
> 2. Set the id in the workspace config as "org.eclipse.che.plugin.java.languageserver",  port as 5555, and languageID as java

Can you share an example? Where exactly in a workspace config should I provide it?

2018-05-08 19:59 UTC, JPinkney commented
Inside the server like this

```
"servers": {
  "ls": {
    "attributes": {
      "internal": "true",
      "type": "ls",
      "config": "{\"id\":\"org.eclipse.che.plugin.java.languageserver\", \"languageIds\":[java]}"
    },
    "protocol": "tcp",
    "port": "5555"
  }
}
```

2018-05-08 20:02 UTC, eivantsov commented
So, server attributes :)

Thanks, I will give it a try,

2018-05-11 09:21 UTC, tsmaeder requested changes

2018-05-16 13:36 UTC, eivantsov commented
@JPinkney yes, that worked - `org.eclipse.che.plugin.java.languageserver` did the trick. I did not expect that since for other LS I am able to assign random IDs.

2018-05-16 13:42 UTC, eivantsov commented
Got this in ws agent logs when expanding the project. Otherwise, simple refactoring, auto completion, go to definition, java doc worked fine.
```
Resource '/web-java-spring' already exists.
org.eclipse.core.internal.resources.ResourceException(/web-java-spring)[374]: java.lang.Exception: Resource '/web-java-spring' already exists.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:39)
	at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:306)
	at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:293)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:53)
	at org.eclipse.core.internal.resources.Project.create(Project.java:264)
	at org.eclipse.core.internal.resources.Project.create(Project.java:248)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.create(ProjectConfigurationManager.java:995)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:35)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:162)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:143)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:151)
2018-05-16 13:38:12,957[pool-9-thread-1]  [ERROR] [o.e.c.a.l.r.CheLanguageClient 74]    - May 16, 2018 1:37:46 PM Error updating workspace folders
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
2018-05-16 13:38:12,960[kspaceUpdater-0]  [ERROR] [.c.p.j.l.WorkspaceSynchronizer 58]   - Workspace updated. Result code: '0', message: 'Error updating workspace folders'. Added projects: '[file:///projects/spring]', removed projects: '[]'
 
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$3.runInWorkspace(ProjectsManager.java:162)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.access$1(ProjectsManager.java:126)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:132)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:133)
```

2018-06-20 07:39 UTC, tsmaeder approved these changes

2018-07-06 12:53 UTC, merged