Removed things relating to quick documentation/javadoc
eclipse/che pull request #9656
Opened 2018-05-09 18:17 UTC by JPinkney

Signed-off-by: jpinkney <josh.pinkney@mail.utoronto.ca>

### What does this PR do?
Cleans:
- Quick documentation things
- JavadocService

### What issues does this PR fix or reference?
Part of https://github.com/eclipse/che/issues/8666

2018-05-09 19:05 UTC, tolusha approved these changes

2018-05-11 09:02 UTC, tsmaeder requested changes

2018-05-11 09:02 UTC, tsmaeder commented on plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/jdt/internal/ui/text/java/AbstractJavaCompletionProposal.java
> +      String info = "";
Did we lose the displaying javadoc in the completion proposals here? If so, we would have to open an issue to restore the functionality.

2018-05-11 09:02 UTC, tsmaeder commented on plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/jdt/internal/ui/text/java/AbstractJavaCompletionProposal.java
>        if (info != null && info.length() > 0) {
This is dead code now.

2018-05-22 01:25 UTC, closed without merging